// Generate a LikeC4 model from the component docs `/soleur:sync` already writes.
//
// WHY A RELATIONSHIP-COUNT GATE EXISTS. The dependency convention this parses is
// EMERGENT, not specified. Until #7332 the only place it was written down was a
// prose placeholder in the component template; nothing ever told the producing
// side to emit a parseable form. Skouer's docs happen to use markdown links,
// Soleur's own use prose ("None (agents are standalone)") 4 times out of 4. So
// the failure mode this module is built around is not a crash — it is a corpus
// that yields elements, exits 0, validates clean, and renders a diagram of
// DISCONNECTED BOXES reported as a successful result. `assessRender` reports that
// state as `degraded`: the docs are the defect, not the run.
//
// VALIDATION MIRRORS scripts/regenerate-c4-model.sh:85-97, NOT c4-render.ts.
// The two in-repo precedents deliberately disagree. `c4-render.ts` gates on
// element count only, reasoning that likec4's stderr wording drifts across patch
// versions — correct for a RUNTIME save path that cannot pin the CLI. This
// producer pins `likec4@1.50.0` (asserted by a drift guard against both
// precedents), so the wording is fixed and both gates are safe. That pin is load
// bearing: if it moves, the diagnostic gate is the thing that breaks.
//
// This module is PURE — parsing, edge building, and string generation only. All
// filesystem writes and the likec4 invocation live in the executable wrapper,
// plugins/soleur/scripts/generate-c4-from-components.ts, mirroring the
// heartbeat-live-reconcile.ts -> reconcile-live-heartbeats.ts split.

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * Pinned likec4 CLI version. MUST stay equal to `LIKEC4_VERSION` in
 * scripts/regenerate-c4-model.sh and the `likec4@…` pin in
 * apps/web-platform/server/c4-render.ts — a drift guard asserts all three.
 */
export const LIKEC4_VERSION = "1.50.0";

/** Provenance stamp. A file without this as its FIRST line is never overwritten. */
export const GENERATED_HEADER =
  "// GENERATED by /soleur:sync c4 — hand edits will be overwritten";

/**
 * Source-fault detector, behaviourally equivalent to `DIAG_RE` in
 * scripts/regenerate-c4-model.sh:94. likec4@1.50.0 exits 0 on a syntax error —
 * it drops the bad fragment, prints `Invalid <file>` / `Line N:`, and still emits
 * a non-empty but INCOMPLETE model, which element-count alone cannot see.
 *
 * The anchors are deliberate: likec4 echoes `workspace: /abs/path`, so an
 * unanchored `Invalid` would false-fail for a checkout directory whose name
 * happens to contain the marker word.
 */
export const DIAG_RE = /^Invalid |Could not resolve|^\s+Line [0-9]+:/m;

export type DepSource = "frontmatter" | "links" | "none";

export type ParsedComponent = {
  /** Sanitized LikeC4 identifier (alphanumeric, camelCase). */
  id: string;
  /** Original kebab-case `component:` value — the key dependencies refer to. */
  name: string;
  /** Human-readable title for the diagram node. */
  title: string;
  /** Resolved dependency names, sorted. */
  deps: string[];
  /**
   * Where `deps` came from. `"frontmatter"` with an empty list means the author
   * DECLARED no dependencies; `"none"` means they declared nothing at all. The
   * coverage summary needs that distinction — a corpus of silent docs must not
   * read as a corpus of genuine leaves.
   */
  depSource: DepSource;
};

export type Edge = { from: string; to: string };

export type RenderVerdict = {
  status: "ok" | "degraded" | "failed";
  reason?: string;
};

// ---------------------------------------------------------------------------
// frontmatter
// ---------------------------------------------------------------------------

type Frontmatter = {
  component?: string;
  status?: string;
  /** `undefined` = absent; `[]` = explicitly declared empty. */
  dependencies?: string[];
};

function splitFrontmatter(source: string): string | null {
  if (!source.startsWith("---")) return null;
  const end = source.indexOf("\n---", 3);
  if (end === -1) return null;
  return source.slice(source.indexOf("\n") + 1, end);
}

function parseFrontmatter(source: string): Frontmatter {
  const block = splitFrontmatter(source);
  if (block === null) return {};

  const fm: Frontmatter = {};
  const lines = block.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_]*):[ \t]*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    const inline = kv[2].trim();

    if (key === "component" || key === "status") {
      fm[key] = inline.replace(/^["']|["']$/g, "");
      continue;
    }

    if (key !== "dependencies") continue;

    // Inline form: `dependencies: []` or `dependencies: [a, b]`.
    if (inline.startsWith("[")) {
      const inner = inline.slice(1, inline.lastIndexOf("]")).trim();
      fm.dependencies = inner === "" ? [] : inner.split(",").map((s) => s.trim()).filter(Boolean);
      continue;
    }

    // Block form: collect the following `  - item` lines. An empty value with no
    // following items is still a DECLARATION, so seed with [].
    const items: string[] = [];
    for (let j = i + 1; j < lines.length; j++) {
      const item = lines[j].match(/^[ \t]+-[ \t]+(.*)$/);
      if (!item) break;
      const v = item[1].trim().replace(/^["']|["']$/g, "");
      if (v) items.push(v);
    }
    fm.dependencies = items;
  }

  return fm;
}

// ---------------------------------------------------------------------------
// parsing
// ---------------------------------------------------------------------------

/** Sanitize a kebab-case component name into a LikeC4 identifier. */
export function toId(name: string): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "component";
  const head = parts[0].toLowerCase();
  const tail = parts.slice(1).map((p) => p[0].toUpperCase() + p.slice(1).toLowerCase());
  const id = head + tail.join("");
  return /^[0-9]/.test(id) ? `c${id}` : id;
}

function titleFor(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join(" ");
}

/**
 * Parse one component doc. Returns `null` for a `status: deprecated` doc —
 * sync.md's contract is "Removed components: add `status: deprecated` (do not
 * delete)", so without this filter the element set accretes deleted components
 * forever and their declared dependencies create dangling edges.
 */
export function parseComponentDoc(source: string, fallbackName: string): ParsedComponent | null {
  const fm = parseFrontmatter(source);
  if (fm.status === "deprecated") return null;

  const name = fm.component ?? fallbackName;

  let deps: string[];
  let depSource: DepSource;

  if (fm.dependencies !== undefined) {
    deps = fm.dependencies;
    depSource = "frontmatter";
  } else {
    // Fallback for docs written before the frontmatter contract: extract markdown
    // links from the prose `**Internal**` line. Prose without links yields
    // nothing — deliberately. Inferring edges from prose would invent
    // architecture, which is worse than reporting degraded.
    const internal = source.match(/^[ \t]*[-*][ \t]*\*\*Internal\*\*[ \t]*:(.*)$/m);
    const links = internal ? [...internal[1].matchAll(/\[([^\]]+)\]\([^)]*\)/g)] : [];
    if (links.length > 0) {
      deps = links.map((m) => m[1].trim());
      depSource = "links";
    } else {
      deps = [];
      depSource = "none";
    }
  }

  const unique = [...new Set(deps.filter((d) => d && d !== name))].sort();

  return { id: toId(name), name, title: titleFor(name), deps: unique, depSource };
}

/** Load and parse every `*.md` in a directory, dropping deprecated docs. Sorted by name. */
export function loadComponentDir(dir: string): ParsedComponent[] {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();

  const docs: ParsedComponent[] = [];
  for (const f of files) {
    const parsed = parseComponentDoc(readFileSync(join(dir, f), "utf8"), f.replace(/\.md$/, ""));
    if (parsed) docs.push(parsed);
  }
  return docs.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

// ---------------------------------------------------------------------------
// edges
// ---------------------------------------------------------------------------

/**
 * Build the edge set, dropping any dependency whose target is not a live element.
 * An edge to a missing or deprecated component makes likec4 emit
 * `Could not resolve …`, which the diagnostic gate treats as a hard failure — so
 * the producer must not emit it in the first place.
 */
export function buildEdges(components: ParsedComponent[]): Edge[] {
  const live = new Set(components.map((c) => c.name));
  const edges: Edge[] = [];

  for (const c of components) {
    for (const dep of c.deps) {
      if (live.has(dep)) edges.push({ from: c.name, to: dep });
    }
  }

  return edges.sort((a, b) =>
    a.from < b.from ? -1 : a.from > b.from ? 1 : a.to < b.to ? -1 : a.to > b.to ? 1 : 0,
  );
}

// ---------------------------------------------------------------------------
// non-destructive write contract
// ---------------------------------------------------------------------------

/**
 * True when the producer may write this path. `/soleur:architecture` writes
 * spec.c4 / model.c4 / views.c4 cwd-relative, and the agent sandbox pins
 * `cwd = workspacePath` — two writers, one directory. A tester who hand-corrects
 * a wrong edge must not have it silently reverted by the next sync.
 *
 * The header must be the FIRST line, not merely present somewhere in the body
 * (cq-assert-anchor-not-bare-token): a hand-authored file that happens to quote
 * the header in a comment is still a hand-authored file.
 */
export function canOverwrite(existing: string | null): boolean {
  if (existing === null) return true;
  return existing.split("\n", 1)[0].trim() === GENERATED_HEADER;
}

// ---------------------------------------------------------------------------
// generation
// ---------------------------------------------------------------------------

function escapeC4(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Emit the composing model file. Deterministic by construction: no timestamp, no
 * run id, sorted inputs — an unchanged component-doc set must produce a
 * byte-identical file, or every sync emits a diff forever.
 */
export function generateC4(components: ParsedComponent[], edges: Edge[]): string {
  const byName = new Map(components.map((c) => [c.name, c]));
  const out: string[] = [GENERATED_HEADER, "", "model {", ""];

  for (const c of components) {
    out.push(`  ${c.id} = component "${escapeC4(c.title)}" {`);
    out.push(`    description "${escapeC4(`Component: ${c.name}`)}"`);
    out.push("  }");
  }

  if (edges.length > 0) {
    out.push("");
    for (const e of edges) {
      const from = byName.get(e.from);
      const to = byName.get(e.to);
      if (!from || !to) continue;
      out.push(`  ${from.id} -> ${to.id} "depends on"`);
    }
  }

  out.push("}", "");
  return out.join("\n");
}

/**
 * Minimal `specification` block, emitted ONLY when the diagrams directory has no
 * other file declaring one. Without a `component` element kind, every generated
 * element is an unresolved reference and the whole render fails.
 */
export function generateSpecC4(): string {
  return [
    GENERATED_HEADER,
    "",
    "specification {",
    "  element component {",
    '    notation "Component"',
    "    style {",
    "      shape rectangle",
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
}

/** Minimal view so the model renders in the KB viewer. */
export function generateViewsC4(): string {
  return [
    GENERATED_HEADER,
    "",
    "views {",
    "  view generatedComponents {",
    '    title "Components (generated from knowledge base)"',
    "    include *",
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * The markdown page carrying the view embed. The KB viewer renders a diagram only
 * for a markdown page with a `likec4-view` fence — three .c4 files alone are not
 * enough (api/kb/c4/project/route.ts also returns MODEL_NOT_BUILT without a
 * committed model.likec4.json).
 */
export function generateViewPage(viewId = "generatedComponents"): string {
  return [
    "# Components",
    "",
    "Generated by `/soleur:sync c4` from the component docs in",
    "`knowledge-base/project/components/`. Edges come from each doc's",
    "`dependencies:` frontmatter.",
    "",
    "```likec4-view",
    viewId,
    "```",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// validation
// ---------------------------------------------------------------------------

/**
 * Count elements and relationships in a rendered `model.likec4.json`.
 *
 * ‼️ The relationship key is `relations`, NOT `relationships`. Reading the wrong
 * key returns `undefined` -> 0, which makes `assessRender` report EVERY corpus as
 * degraded — a gate that always fires is exactly as useless as one that never
 * does, and no unit test over `assessRender` (which takes plain numbers) can see
 * it. `countModelJson` exists so the key mapping itself is pinned by a test
 * against a real likec4 artifact.
 *
 * Non-object shapes yield 0 rather than throwing: likec4 can emit a null/array
 * field, and a bare `Object.keys` on those would silently produce a wrong count.
 */
export function countModelJson(json: string): { elements: number; relationships: number } {
  try {
    const model = JSON.parse(json) as Record<string, unknown>;
    const size = (v: unknown) =>
      v && typeof v === "object" && !Array.isArray(v) ? Object.keys(v).length : 0;
    return { elements: size(model.elements), relationships: size(model.relations) };
  } catch {
    return { elements: 0, relationships: 0 };
  }
}

/**
 * The three gates. Order matters: a source fault is a hard failure regardless of
 * counts, an empty model is a failure, and only then is a zero-relationship model
 * classified — as `degraded`, never `failed`. The docs are the defect there, not
 * the run, and failing the sync over it would punish the tester for a corpus
 * Soleur itself taught them to write.
 */
export function assessRender(input: {
  diagnostics: string;
  elementCount: number;
  relationshipCount: number;
}): RenderVerdict {
  if (DIAG_RE.test(input.diagnostics)) {
    const line = input.diagnostics.split("\n").find((l) => DIAG_RE.test(l)) ?? "";
    return { status: "failed", reason: `likec4 reported a source fault: ${line.trim()}` };
  }
  if (input.elementCount === 0) {
    return { status: "failed", reason: "likec4 produced an empty/degenerate model" };
  }
  if (input.relationshipCount === 0) {
    return {
      status: "degraded",
      reason:
        "0 relationships — component docs declare no parseable dependencies, " +
        "so the diagram is a set of disconnected boxes",
    };
  }
  return { status: "ok" };
}
