#!/usr/bin/env bash
# Follow-through verification stub (template).
#
# Mirror of scripts/followthroughs/sentry-checkins-3859.sh.
# Generated by /ship Phase 7 Step 3.5; customize the TODO block below.
#
# Exit semantics (enforced by scripts/sweep-followthroughs.sh):
#   0 = PASS         (close-criteria met; sweeper closes the issue)
#   1 = FAIL         (criteria not met; sweeper comments, leaves open)
#   * = TRANSIENT    (network error, unexpected state; sweeper retries next sweep)
#
# Required secrets: declare via the directive `secrets=` clause AND add to
# .github/workflows/scheduled-followthrough-sweeper.yml env: block.
#
# Convention: knowledge-base/engineering/operations/runbooks/followthrough-convention.md

set -uo pipefail

# REFUSE TO RUN UNDER XTRACE (#7797). A probe receives its secrets from the
# sweeper's env, and tracing echoes commands AFTER expansion -- so a credential
# leaks the moment it is used, and the sweeper posts probe output into a public
# issue comment. Unconditional is the safe default for a scaffold, because the
# template cannot know which credentials this probe will end up reading.
#
# If your probe INHERITS a known, fixed set of credentials, you may narrow this
# to a hatch that keeps the script traceable when they are unset:
#
#   case "$-" in
#     *x*)
#       if [ -n "${YOUR_TOKEN:+x}" ]; then   # `:+x` -- `:-` would PRINT the value
#         printf '[FATAL] refusing to trace with a live credential set (see #7797)\n' >&2
#         exit 78
#       fi
#       ;;
#   esac
#
# Keep it directly below `set ...`: `scripts/lint-shell-trace-credential-refusal.py`
# requires the refusal in the prologue, before any command that could be traced.
case "$-" in
  *x*) printf '[FATAL] refusing to run under xtrace: this probe handles live credentials and -x would print them (see #7797)\n' >&2; exit 78 ;;
esac

# soleur:followthrough-stub v1

# Re-evaluation trigger (dependency): the leader-loop 429 relabel needs the
# leader-loop suite on the shared step harness, which #8764 tracks. PASS when
# #8764 is closed, so the deferred fix is picked back up.
state="$(gh issue view 8764 --repo jikig-ai/soleur --json state --jq .state 2>/dev/null)" || {
  echo "TRANSIENT: gh issue view 8764 failed" >&2
  exit 2
}
case "$state" in
  CLOSED) echo "PASS: #8764 closed — re-evaluate the leader-loop 429 relabel"; exit 0 ;;
  OPEN) echo "FAIL: #8764 still open"; exit 1 ;;
  *) echo "TRANSIENT: unexpected state '$state'" >&2; exit 2 ;;
esac
