#!/usr/bin/env bash
# Follow-through verification stub (template).
#
# Mirror of scripts/followthroughs/sentry-checkins-3859.sh.
# Generated by /ship Phase 7 Step 3.5; customize the TODO block below.
#
# Exit semantics (enforced by scripts/sweep-followthroughs.sh):
#   0 = PASS         (close-criteria met; sweeper closes the issue)
#   1 = FAIL         (criteria not met; sweeper comments, leaves open)
#   * = TRANSIENT    (network error, unexpected state; sweeper retries next sweep)
#
# Required secrets: declare via the directive `secrets=` clause AND add to
# .github/workflows/scheduled-followthrough-sweeper.yml env: block.
#
# Convention: knowledge-base/engineering/operations/runbooks/followthrough-convention.md

set -uo pipefail

# soleur:followthrough-stub v1

# Probe: the set -e sweep across the 7 pre-existing SSH remote-exec
# provisioners in apps/web-platform/infra/server.tf has landed. Counts
# inline blocks whose FIRST element is "set -e" — 9 = the 7 siblings fixed
# plus the 2 cron_egress_firewall blocks that already ship with it (#5089).
TF="apps/web-platform/infra/server.tf"
[[ -f "$TF" ]] || { echo "TRANSIENT: $TF not found (checkout shape changed?)" >&2; exit 2; }
COUNT="$(grep -c '"set -e",' "$TF" || true)"
echo "set -e gated inline blocks in server.tf: $COUNT (need >= 9)"
if [[ "$COUNT" -ge 9 ]]; then
  exit 0
fi
exit 1
