#!/usr/bin/env bash
# sentinel-pr.sh — automated Phase 8 sentinel PRs (closes #3908).
#
# Verifies the live cla-evidence sidecar end-to-end by opening one or two
# synthetic PRs and polling `inspect-evidence.sh by-pr <N>` against R2 for
# the resulting evidence record. Modes:
#   human   — opens a "human signer" sentinel (operator's GitHub identity)
#             and posts a `recheck` comment to trigger the upstream CLA
#             action's evidence write path.
#   bypass  — opens a sentinel labeled `bypass-allowlist` so the action's
#             allowlist-bypass path fires; the sidecar writes the bypass
#             record under allowlist/.
#   both    — runs human then bypass.
#
# Each sentinel:
#   1. Touches a single docs-only marker file under
#      knowledge-base/project/learnings/.cla-sentinel-<mode>-<ts>.md
#      (low blast radius; no production code change).
#   2. Pushes a branch + opens a PR labeled `cla-sentinel` (+ `bypass-allowlist`
#      for bypass mode). The CI workflow `cla-evidence.yml` runs and writes
#      to R2 in the normal flow.
#   3. Polls `inspect-evidence.sh by-pr <N>` for up to 5 minutes (30 retries
#      at 10s intervals). Exit code 0 = record found; non-zero = timeout.
#   4. Auto-closes the PR with --delete-branch to avoid history pollution.
#
# Pre-flight: creates the `cla-sentinel` label if missing (idempotent via
# `--force`). The `bypass-allowlist` label is expected to exist (configured
# by the upstream contributor-assistant action).
#
# Dry-run: `SENTINEL_DRY_RUN=1 sentinel-pr.sh <mode>` stubs `gh pr create`
# and `inspect-evidence.sh by-pr` for testing.
#
# Exit codes:
#   0  — all requested sentinels passed
#   2  — at least one inspect-evidence poll timed out
#   3  — pre-flight failure (gh not authed, label create failed, etc.)
#   64 — usage error

set -euo pipefail

usage() {
  cat >&2 <<USAGE
Usage:
  sentinel-pr.sh {human|bypass|both}
  SENTINEL_DRY_RUN=1 sentinel-pr.sh {human|bypass|both}
USAGE
  exit 64
}

mode="${1:-}"
case "$mode" in
  human|bypass|both) ;;
  "") usage ;;
  *)  echo "::error::unknown mode: $mode" >&2; usage ;;
esac

DRY_RUN="${SENTINEL_DRY_RUN:-0}"
REPO="${SENTINEL_REPO:-jikig-ai/soleur}"
BASE_BRANCH="${SENTINEL_BASE_BRANCH:-main}"
POLL_RETRIES="${SENTINEL_POLL_RETRIES:-30}"
POLL_INTERVAL="${SENTINEL_POLL_INTERVAL:-10}"

red()    { printf '\033[31m%s\033[0m\n' "$*" >&2; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
step()   { printf '\n→ %s\n' "$*"; }

# ─────────────────────────────────────────────────────────────────────────
# Pre-flight: gh auth + label creation
# ─────────────────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" != "1" ]]; then
  command -v gh >/dev/null || { red "missing gh on PATH"; exit 3; }
  gh auth status >/dev/null 2>&1 || { red "gh not authenticated"; exit 3; }
  gh label create cla-sentinel \
    --description "Synthetic PR opened by sentinel-pr.sh to verify cla-evidence end-to-end" \
    --color "0E8A16" \
    --force \
    --repo "$REPO" >/dev/null 2>&1 \
    || { red "failed to create/refresh cla-sentinel label"; exit 3; }
fi

# ─────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────

# poll_inspect <pr-number> — returns 0 if the record lands within the poll
# window, 2 on timeout. In dry-run mode, succeeds on the first call.
poll_inspect() {
  local pr="$1"
  if [[ "$DRY_RUN" == "1" ]]; then
    green "  [dry-run] inspect-evidence.sh by-pr $pr → OK"
    return 0
  fi
  local i
  for ((i = 1; i <= POLL_RETRIES; i++)); do
    if bash "$(dirname "${BASH_SOURCE[0]}")/inspect-evidence.sh" by-pr "$pr" >/dev/null 2>&1; then
      green "  inspect-evidence.sh by-pr $pr → OK (after $i tries)"
      return 0
    fi
    sleep "$POLL_INTERVAL"
  done
  red "  inspect-evidence.sh by-pr $pr timed out after $((POLL_RETRIES * POLL_INTERVAL))s"
  return 2
}

# open_sentinel <mode> — opens a sentinel PR; prints its number on stdout.
# In dry-run mode, prints a fake PR number 999999.
open_sentinel() {
  local m="$1"
  local ts marker_path branch pr_num labels
  ts=$(date -u +%Y%m%d%H%M%S)
  marker_path="knowledge-base/project/learnings/.cla-sentinel-${m}-${ts}.md"
  branch="cla-sentinel/${m}-${ts}"
  labels="cla-sentinel"
  [[ "$m" == "bypass" ]] && labels="cla-sentinel,bypass-allowlist"

  if [[ "$DRY_RUN" == "1" ]]; then
    green "  [dry-run] would open $m sentinel PR (branch=$branch labels=$labels)"
    echo 999999
    return 0
  fi

  # Write a small marker file with provenance info so the PR has a single
  # tracked file; auto-closed after R2 verification.
  mkdir -p "$(dirname "$marker_path")"
  cat > "$marker_path" <<EOF
# cla-sentinel marker: $m / $ts

Auto-generated by \`apps/cla-evidence/scripts/sentinel-pr.sh\`.
Verifies the cla-evidence sidecar writes to R2 for this synthetic PR.
PR will auto-close after R2 verification.
EOF

  git checkout -b "$branch" "origin/${BASE_BRANCH}" >/dev/null 2>&1
  git add "$marker_path"
  git commit -m "chore(cla-evidence): ${m} sentinel ${ts}" >/dev/null
  git push -u origin "$branch" >/dev/null 2>&1
  pr_num=$(gh pr create \
    --repo "$REPO" \
    --base "$BASE_BRANCH" \
    --head "$branch" \
    --title "chore(cla-evidence): ${m} sentinel ${ts}" \
    --body "Sentinel PR (mode=${m}) for cla-evidence #3908. Auto-closes after R2 verification." \
    --label "$labels" \
    | awk -F/ '/pull\// {print $NF; exit}')
  if [[ -z "$pr_num" ]]; then
    red "gh pr create returned no PR number"
    return 3
  fi
  echo "$pr_num"
}

# close_sentinel <pr-number>
close_sentinel() {
  local pr="$1"
  if [[ "$DRY_RUN" == "1" ]]; then
    green "  [dry-run] gh pr close $pr --delete-branch"
    return 0
  fi
  gh pr close "$pr" --repo "$REPO" --delete-branch --comment "Sentinel verification complete; closing." >/dev/null 2>&1 \
    || yellow "  gh pr close $pr returned non-zero (already closed?)"
}

# run_sentinel <mode>
run_sentinel() {
  local m="$1" pr rc=0
  step "Sentinel: $m"
  pr=$(open_sentinel "$m") || return $?
  green "  opened PR #$pr"
  poll_inspect "$pr" || rc=$?
  close_sentinel "$pr"
  return "$rc"
}

# ─────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────
overall=0
case "$mode" in
  human)  run_sentinel human  || overall=$? ;;
  bypass) run_sentinel bypass || overall=$? ;;
  both)
    run_sentinel human  || overall=$?
    run_sentinel bypass || overall=$?
    ;;
esac

if [[ "$overall" -eq 0 ]]; then
  green ""
  green "sentinel-pr.sh: all requested sentinels verified."
else
  red ""
  red "sentinel-pr.sh: at least one sentinel failed (rc=$overall)."
fi
exit "$overall"
