#!/usr/bin/env bash
# Probe + sampler table for the GHCR deny probe in cron-egress-resolve.sh (#9275,
# ADR-096 5.3b-iii). Guard 2 of the plan's Guard Contract.
#
# NO LOGIC COPY: ghcr_probe_verdict / ghcr_probe_blind_step / run_ghcr_probe /
# filter_ghcr_probe_drops and the GHCR_PROBE_* / CIDR_FILE assignments are extracted from
# the resolver by awk/grep on their definition lines and `source`d. Seams stubbed: the
# state dir (FAILCOUNT_DIR under a mktemp root), the clock (run_ghcr_probe's $1),
# sentry_event / container_running / log (recording functions), docker + nft (PATH shims
# that read canned output per probed name). Every table is driven by an array whose row
# count is floored, so a runner that iterates zero rows is RED, not green.
# shellcheck disable=SC2329,SC2016  # stubs are invoked via the sourced library; payloads are intentionally single-quoted
set -uo pipefail

export TMPDIR="${TMPDIR:-/var/tmp}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLVER="${RESOLVER:-$SCRIPT_DIR/cron-egress-resolve.sh}"

PASS=0
FAIL=0
pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }
check() { # check "label" want got
  if [[ "$2" == "$3" ]]; then pass "$1"; else fail "$1 (want='$2' got='$3')"; fi
}

assert_fixture_dir() {
  case "${1-}" in
    "") printf 'FATAL: fixture dir is EMPTY; git -C "" would operate on %s\n' "$PWD" >&2; exit 2 ;;
    */../*|*/..) printf 'FATAL: fixture dir %s contains ..; refusing\n' "$1" >&2; exit 2 ;;
    /proc/*|/sys/*|/dev/*) printf 'FATAL: fixture dir %s is a synthetic-fs path; refusing\n' "$1" >&2; exit 2 ;;
    /|//|/.) printf 'FATAL: fixture dir resolves to the filesystem root; refusing\n' >&2; exit 2 ;;
    /*) : ;;
    *)  printf 'FATAL: fixture dir %s is RELATIVE; refusing\n' "$1" >&2; exit 2 ;;
  esac
}

WORK="$(mktemp -d "${TMPDIR}/ghcr-probe-test.XXXXXX")"
assert_fixture_dir "$WORK"
cleanup() { assert_fixture_dir "$WORK"; rm -rf "$WORK"; }
trap cleanup EXIT

[[ -f "$RESOLVER" ]] || { echo "FATAL: resolver not found: $RESOLVER" >&2; exit 2; }

# --- extraction (no logic copy) --------------------------------------------------------
extract_fn() { # extract_fn name  (definition line `name() {` through the closing `}` at col 0)
  awk -v n="$1" '
    $0 == n "() {" { p = 1 }
    p { print }
    p && $0 == "}" { exit }' "$RESOLVER"
}

CIDR_FIXTURE="$WORK/cidr.txt"
export CIDR_FILE="$CIDR_FIXTURE"
LIB="$WORK/probe-lib.sh"
assert_fixture_dir "$WORK"
{
  echo '# generated by cron-egress-ghcr-probe.test.sh from cron-egress-resolve.sh'
  grep -E '^GHCR_PROBE_[A-Z_]+=' "$RESOLVER"
  # The resolver's CIDR_FILE default is env-overridable; the test pre-exports CIDR_FILE.
  grep -E '^CIDR_FILE=' "$RESOLVER"
  for fn in ghcr_probe_verdict ghcr_probe_blind_step run_ghcr_probe filter_ghcr_probe_drops; do
    extract_fn "$fn"
  done
} > "$LIB"

echo "-- extraction (non-vacuous) --"
for fn in ghcr_probe_verdict ghcr_probe_blind_step run_ghcr_probe filter_ghcr_probe_drops; do
  n="$(extract_fn "$fn" | wc -l)"
  if [[ "$n" -ge 6 ]]; then pass "extracted $fn ($n lines)"; else fail "extracted $fn ($n lines; expected >= 6)"; fi
done
for c in GHCR_PROBE_PORT_LO GHCR_PROBE_PORT_HI GHCR_PROBE_INTERVAL GHCR_PROBE_BLIND_AT GHCR_PROBE_NAMES; do
  if grep -qE "^$c=" "$LIB"; then pass "constant $c extracted"; else fail "constant $c extracted"; fi
done
if bash -n "$LIB"; then pass "extracted library parses"; else fail "extracted library parses"; fi

# --- stubs ------------------------------------------------------------------------------
MOCK="$WORK/mock"
SHIM="$WORK/shim"
EVENTS="$WORK/events.tsv"
FAILCOUNT_DIR="$WORK/state"
export FAILCOUNT_DIR
assert_fixture_dir "$WORK"
mkdir -p "$MOCK" "$SHIM" "$FAILCOUNT_DIR"

cat > "$SHIM/docker" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$MOCK_DIR/docker.args"
url="${*: -1}"; name="${url#https://}"; name="${name%/}"
if [[ -f "$MOCK_DIR/$name.out" ]]; then cat "$MOCK_DIR/$name.out"; fi
rc=0
if [[ -f "$MOCK_DIR/$name.rc" ]]; then rc="$(cat "$MOCK_DIR/$name.rc")"; fi
exit "$rc"
SHIM_EOF
cat > "$SHIM/nft" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$MOCK_DIR/nft.args"
rc=1
if [[ -f "$MOCK_DIR/nft.rc" ]]; then rc="$(cat "$MOCK_DIR/nft.rc")"; fi
exit "$rc"
SHIM_EOF
chmod +x "$SHIM/docker" "$SHIM/nft"
export MOCK_DIR="$MOCK"
export PATH="$SHIM:$PATH"

CONTAINER="soleur-web-platform"
CONTAINER_UP=1
log() { :; }
container_running() { [[ "$CONTAINER_UP" == "1" ]]; }
sentry_event() { # msg op extra  -> one TSV row: op, msg, compact extra ('' when extra is not JSON)
  local compact
  compact="$(jq -c . <<<"$3" 2>/dev/null || true)"
  printf '%s\t%s\t%s\n' "$2" "$1" "$compact" >> "$EVENTS"
}

# shellcheck disable=SC1090
source "$LIB"

new_state() { # fresh state dir, event log, mock outputs, docker/nft history
  assert_fixture_dir "$WORK"
  rm -rf "$FAILCOUNT_DIR" "$MOCK"
  mkdir -p "$FAILCOUNT_DIR" "$MOCK"
  : > "$EVENTS"
  CONTAINER_UP=1
  unset CRON_EGRESS_FROM_LOADER
  SECONDS=0
}
mock_probe() { # mock_probe name rc raw
  assert_fixture_dir "$WORK"
  printf '%s' "$3" > "$MOCK/$1.out"
  printf '%s' "$2" > "$MOCK/$1.rc"
}
ev_count() { # ev_count [op]  (count of recorded events, optionally for one op)
  if [[ -n "${1:-}" ]]; then
    awk -F'\t' -v op="$1" '$1 == op { n++ } END { print n + 0 }' "$EVENTS"
  else
    awk 'END { print NR + 0 }' "$EVENTS"
  fi
}
docker_calls() { if [[ -f "$MOCK/docker.args" ]]; then wc -l < "$MOCK/docker.args"; else echo 0; fi; }
counter() { # counter name -> counter-file content ('absent' when missing)
  if [[ -f "$FAILCOUNT_DIR/ghcr_probe.$1.blind" ]]; then cat "$FAILCOUNT_DIR/ghcr_probe.$1.blind"; else echo absent; fi
}

# --- 1. verdict table (strict-mode child per row: nothing may abort the tick) ------------
echo "-- ghcr_probe_verdict table --"
V_LABEL=(); V_RC=(); V_RAW=(); V_WANT=()
vadd() { V_LABEL+=("$1"); V_RC+=("$2"); V_RAW+=("$3"); V_WANT+=("$4"); }

TENKB="$(head -c 10000 /dev/zero | tr '\0' 'A')"
vadd "held: dropped connect, resolver answered"            28  "0.012 0.000000 "                       "held 0.012 0.000000 -"
vadd "held (must-PASS non-canonical): rc28 nl=0.012 tc=0"  28  "0.012000 0.000000 "                     "held 0.012000 0.000000 -"
vadd "hung resolver is NOT held (rc28, nl=0)"              28  "0.000000 0.000000 "                     "inconclusive 0.000000 0.000000 -"
vadd "reached: handshake completed"                         0  "0.012 0.401402 140.82.121.34"          "reached 0.012 0.401402 140.82.121.34"
vadd "reached even when TLS fails after connect (rc35)"    35  "0.012 0.200000 140.82.121.34"          "reached 0.012 0.200000 140.82.121.34"
vadd "reached with a 1ms connect"                           0  "0.001 0.001 140.82.121.33"             "reached 0.001 0.001 140.82.121.33"
vadd "DNS failure (rc6) is inconclusive"                    6  "0.000000 0.000000 "                     "inconclusive 0.000000 0.000000 -"
vadd "connection refused (rc7) is inconclusive"             7  "0.010 0.000000 "                        "inconclusive 0.010 0.000000 -"
vadd "docker exec 125 is inconclusive"                    125  ""                                        "inconclusive - - -"
vadd "docker exec 126 is inconclusive"                    126  ""                                        "inconclusive - - -"
vadd "docker exec 127 (curl missing) is inconclusive"     127  ""                                        "inconclusive - - -"
vadd "timeout(1) kill 124 is inconclusive"                124  ""                                        "inconclusive - - -"
vadd "rc0 with tc=0 is inconclusive"                        0  "0.012 0.000000 "                        "inconclusive 0.012 0.000000 -"
vadd "empty output, rc28 is inconclusive"                  28  ""                                        "inconclusive - - -"
vadd "hostile time_connect: command substitution"          28  '0.012 a[$(touch '"$WORK"'/PWNED)] 1.2.3.4' "inconclusive - - -"
vadd "hostile time_connect: backticks"                     28  '0.012 `touch '"$WORK"'/PWNED` '          "inconclusive - - -"
vadd "hostile time_namelookup"                             28  '$(touch '"$WORK"'/PWNED) 0.000000 '      "inconclusive - - -"
vadd "10 kB single line"                                   28  "$TENKB"                                  "inconclusive - - -"
vadd "10 kB line after valid prefix fields"                 0  "0.012 0.400 $TENKB"                     "reached 0.012 0.400 -"
vadd "scientific notation timing is rejected"              28  "0.012 1e-3 "                             "inconclusive - - -"
vadd "negative timing is rejected"                         28  "0.012 -0.5 "                            "inconclusive - - -"
vadd "extra trailing field is rejected"                     0  "0.012 0.4 140.82.121.34 EXTRA"         "inconclusive - - -"
vadd "reached with a non-IPv4 remote_ip (name kept out)"    0  "0.012 0.4 not-an-ip"                    "reached 0.012 0.4 -"
vadd "reached with an out-of-range octet"                   0  "0.012 0.4 999.1.1.1"                    "reached 0.012 0.4 -"
vadd "reached with a leading-zero octet"                    0  "0.012 0.4 01.2.3.4"                     "reached 0.012 0.4 -"
vadd "reached with a shell-metachar remote_ip"              0  '0.012 0.4 1.2.3.4;rm'                   "reached 0.012 0.4 -"
vadd "multi-line output: only the first line is read"       0  $'0.012 0.4 1.1.1.1\n{"x":1}'            "reached 0.012 0.4 1.1.1.1"
vadd "non-numeric rc"                                    "x1"  "0.012 0.000000 "                        "inconclusive - - -"
vadd "IPv6 remote_ip is not IPv4"                           0  "0.012 0.4 2606:50c0:8000::154"          "reached 0.012 0.4 -"

ROWS_RUN=0
for i in "${!V_LABEL[@]}"; do
  ROWS_RUN=$((ROWS_RUN + 1))
  got="$(bash -euo pipefail -c 'source "$1"; ghcr_probe_verdict "$2" "$3"' _ "$LIB" "${V_RC[$i]}" "${V_RAW[$i]}" 2>/dev/null || echo "ABORTED-rc=$?")"
  check "verdict: ${V_LABEL[$i]}" "${V_WANT[$i]}" "$got"
done
check "verdict table instrument: every row ran" "${#V_LABEL[@]}" "$ROWS_RUN"
if [[ "$ROWS_RUN" -ge 25 ]]; then pass "verdict table instrument: row-count floor (>= 25, ran $ROWS_RUN)"; else fail "verdict table instrument: row-count floor (ran $ROWS_RUN)"; fi
if [[ ! -e "$WORK/PWNED" ]]; then pass "hostile output executed nothing (no PWNED file)"; else fail "hostile output created $WORK/PWNED"; fi

# --- 2. blind counter ---------------------------------------------------------------------
echo "-- ghcr_probe_blind_step --"
new_state
seq_out=""
for _ in $(seq 1 13); do seq_out+="$(ghcr_probe_blind_step inconclusive ghcr.io) "; done
check "counter counts 1..13 on consecutive inconclusive" "1 2 3 4 5 6 7 8 9 10 11 12 13 " "$seq_out"
check "held resets the counter" "0" "$(ghcr_probe_blind_step held ghcr.io)"
check "held removes the state file" "absent" "$(counter ghcr.io)"
ghcr_probe_blind_step inconclusive docker.pkg.github.com >/dev/null
ghcr_probe_blind_step absent docker.pkg.github.com >/dev/null
check "absent increments like inconclusive" "2" "$(counter docker.pkg.github.com)"
check "reached resets the counter" "0" "$(ghcr_probe_blind_step reached docker.pkg.github.com)"
check "counters are per name" "absent" "$(counter ghcr.io)"
printf 'garbage' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
check "corrupt counter file restarts at 1" "1" "$(ghcr_probe_blind_step inconclusive ghcr.io)"
printf '$(touch %s/PWNED)' "$WORK" > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
check "hostile counter file is not evaluated" "1" "$(ghcr_probe_blind_step inconclusive ghcr.io)"
if [[ ! -e "$WORK/PWNED" ]]; then pass "hostile counter file executed nothing"; else fail "hostile counter file created PWNED"; fi

# --- 3. dispatch ----------------------------------------------------------------------------
echo "-- run_ghcr_probe dispatch --"
HELD="0.012 0.000000 "
REACHED="0.012 0.401402 140.82.121.34"

new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "both names probed on a compliant first run (second name not skipped)" "2" "$(docker_calls)"
check "held on both names emits nothing" "0" "$(ev_count)"
check "stamp file written" "10000" "$(cat "$FAILCOUNT_DIR/ghcr_probe.stamp" 2>/dev/null || echo absent)"
args="$(cat "$MOCK/docker.args")"
for want in 'ghcr.io/' 'docker.pkg.github.com/'; do
  if grep -qF "https://$want" <<<"$args"; then pass "probed https://$want"; else fail "probed https://$want"; fi
done
first="$(sed -n 1p "$MOCK/docker.args")"
if [[ "$first" == "exec $CONTAINER curl -q -s -o /dev/null --noproxy * --connect-timeout 5 --max-time 8 --local-port 49100-49199 -w "* ]]; then
  pass "curl argv: container name, -q first, --noproxy '*', timeouts, reserved port range"
else
  fail "curl argv shape: $first"
fi
if grep -q -- '--retry' <<<"$args"; then fail "no --retry flag"; else pass "no --retry flag"; fi

echo "-- cadence gate --"
run_ghcr_probe 10100;  check "100s later: no probe" "2" "$(docker_calls)"
run_ghcr_probe 10269;  check "269s later: no probe" "2" "$(docker_calls)"
run_ghcr_probe 10270;  check "270s later: probe runs (>= 270)" "4" "$(docker_calls)"
run_ghcr_probe 10271;  check "1s after a probe: no probe" "4" "$(docker_calls)"
run_ghcr_probe 10540;  check "270s after the second probe: runs again" "6" "$(docker_calls)"
printf 'garbage' > "$FAILCOUNT_DIR/ghcr_probe.stamp"
run_ghcr_probe 10541;  check "corrupt stamp counts as due" "8" "$(docker_calls)"

new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
CRON_EGRESS_FROM_LOADER=1 run_ghcr_probe 10000
check "loader-invoked tick: probe skipped" "0" "$(docker_calls)"
check "loader-invoked tick: no stamp" "absent" "$(cat "$FAILCOUNT_DIR/ghcr_probe.stamp" 2>/dev/null || echo absent)"
SECONDS=61; run_ghcr_probe 10000
check "tick older than 60s: probe skipped" "0" "$(docker_calls)"
check "tick older than 60s: no stamp (retried next tick)" "absent" "$(cat "$FAILCOUNT_DIR/ghcr_probe.stamp" 2>/dev/null || echo absent)"
SECONDS=60; run_ghcr_probe 10000
check "tick at exactly 60s still probes" "2" "$(docker_calls)"

echo "-- reached -> ghcr_deny_lost --"
new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "one lost event (one name reached)" "1" "$(ev_count ghcr_deny_lost)"
check "no other event" "1" "$(ev_count)"
msg1="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $2; exit }' "$EVENTS")"
extra1="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
if [[ "$msg1" != *'$'* && "$msg1" != *140.82* && "$msg1" != *ghcr.io* && -n "$msg1" ]]; then pass "lost message is static (no IP, no name, no \$)"; else fail "lost message not static: $msg1"; fi
check "lost extra.name" "ghcr.io" "$(jq -r .name <<<"$extra1")"
check "lost extra.remote_ip" "140.82.121.34" "$(jq -r .remote_ip <<<"$extra1")"
check "lost extra.time_connect" "0.401402" "$(jq -r .time_connect <<<"$extra1")"
check "lost extra.in_allow_cidr (nft miss -> false)" "false" "$(jq -r .in_allow_cidr <<<"$extra1")"
if jq -e '.file_sha256 and .remediation' <<<"$extra1" >/dev/null; then pass "lost extra carries file_sha256 and remediation"; else fail "lost extra fields: $extra1"; fi
if grep -qF "get element ip filter soleur_egress_allow_cidr { 140.82.121.34 }" "$MOCK/nft.args" 2>/dev/null; then pass "in_allow_cidr read from the live set via nft get element"; else fail "nft get element call"; fi

new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 0 "0.01 0.3 140.82.121.33"
printf '0' > "$MOCK/nft.rc"
run_ghcr_probe 10000
check "both reached: two lost events" "2" "$(ev_count ghcr_deny_lost)"
check "both lost events share ONE message (one Sentry issue group)" "1" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $2 }' "$EVENTS" | sort -u | wc -l)"
check "in_allow_cidr true when the live set admits the IP" "true" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS" | jq -r .in_allow_cidr)"
run_ghcr_probe 10300
check "reached on every due run (not once)" "4" "$(ev_count ghcr_deny_lost)"

new_state
mock_probe ghcr.io 0 '0.012 0.4 "},"injected":"x'
mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
extra_h="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
check "hostile remote_ip cannot inject an extra key" "name,remote_ip,time_connect,in_allow_cidr,file_sha256,remediation" "$(jq -r 'keys_unsorted | join(",")' <<<"$extra_h" 2>/dev/null || echo INVALID)"
check "hostile remote_ip is replaced by '-'" "-" "$(jq -r .remote_ip <<<"$extra_h" 2>/dev/null || echo INVALID)"

echo "-- sequence: counter 11 then reached --"
new_state
printf '11' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "11-then-reached: exactly one lost" "1" "$(ev_count ghcr_deny_lost)"
check "11-then-reached: no blind event" "0" "$(ev_count ghcr_deny_probe_blind)"
check "11-then-reached: counter reset" "absent" "$(counter ghcr.io)"

echo "-- held resets a prior counter (must-PASS non-canonical row) --"
new_state
printf '7' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 28 "0.012 0.000000 "; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "rc28 nl=0.012 tc=0 with prior 7: held, counter reset" "absent" "$(counter ghcr.io)"
check "...and no event" "0" "$(ev_count)"

echo "-- blind: twelve inconclusive due runs --"
new_state
mock_probe ghcr.io 127 ""; mock_probe docker.pkg.github.com 28 "0.000000 0.000000 "
now=10000
for i in $(seq 1 11); do run_ghcr_probe "$now"; now=$((now + 300)); done
check "11 inconclusive runs: no blind event yet" "0" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"; now=$((now + 300))
check "12th inconclusive run: one blind event per name (2)" "2" "$(ev_count ghcr_deny_probe_blind)"
reasons="$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3 }' "$EVENTS" | jq -r .reason | sort -u | tr '\n' ',')"
check "blind reason is inconclusive" "inconclusive," "$reasons"
run_ghcr_probe "$now"; now=$((now + 300))
check "13th run: not re-emitted (exactly once at 12)" "2" "$(ev_count ghcr_deny_probe_blind)"
blind_msgs="$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $2 }' "$EVENTS" | sort -u | wc -l)"
check "blind message is one static literal" "1" "$blind_msgs"
if awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $2 }' "$EVENTS" | grep -qE '[$]|ghcr[.]io'; then fail "blind message not static"; else pass "blind message has no \$ / name"; fi
check "blind extra.last_rc" "127" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .last_rc)"
check "blind extra.name present" "ghcr.io" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .name)"

echo "-- blind: container absent x12 (counted skip, not silent) --"
new_state
CONTAINER_UP=0
now=10000
for i in $(seq 1 11); do run_ghcr_probe "$now"; now=$((now + 300)); done
check "11 absent runs: no blind event yet" "0" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"
check "12th absent run: blind event per name" "2" "$(ev_count ghcr_deny_probe_blind)"
check "absent runs never touch docker" "0" "$(docker_calls)"
check "blind reason is container_absent" "container_absent," "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3 }' "$EVENTS" | jq -r .reason | sort -u | tr '\n' ',')"
check "absent skip never emits lost" "0" "$(ev_count ghcr_deny_lost)"

echo "-- hostile probe output through dispatch --"
new_state
mock_probe ghcr.io 28 '0.012 a[$(touch '"$WORK"'/PWNED)] 1.2.3.4'
mock_probe docker.pkg.github.com 0 "$TENKB"
run_ghcr_probe 10000
check "hostile outputs: inconclusive, no event" "0" "$(ev_count)"
check "hostile outputs counted toward blind" "1" "$(counter ghcr.io)"
if [[ ! -e "$WORK/PWNED" ]]; then pass "dispatch executed nothing from hostile output"; else fail "dispatch created PWNED"; fi

echo "-- independent per-name state --"
new_state
mock_probe ghcr.io 127 ""; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "ghcr.io inconclusive counter" "1" "$(counter ghcr.io)"
check "docker.pkg.github.com held counter" "absent" "$(counter docker.pkg.github.com)"

# --- 4. sampler filter -----------------------------------------------------------------------
echo "-- filter_ghcr_probe_drops --"
assert_fixture_dir "$WORK"
cat > "$CIDR_FIXTURE" <<'CIDR_EOF'
# Container egress CIDR allowlist (synthesized fixture)
# Excluded (GitHub Packages frontends): 140.82.121.33/32
# Excluded (GitHub Packages frontends): 140.82.121.34/32
# Excluded (GitHub Packages frontends): 192.30.255.164/31
140.82.112.0/20
CIDR_EOF
kline() { # kline spt dpt dst [src]
  printf 'Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 SRC=%s DST=%s LEN=60 TOS=0x00 PROTO=TCP SPT=%s DPT=%s WINDOW=64240 SYN\n' "${4:-172.17.0.2}" "$3" "$1" "$2"
}
S_LABEL=(); S_LINE=(); S_WANT=()
sadd() { S_LABEL+=("$1"); S_LINE+=("$2"); S_WANT+=("$3"); }
sadd "probe SYN to carved /32 is dropped"                    "$(kline 49150 443 140.82.121.34)" drop
sadd "probe SYN to the other carved /32 is dropped"          "$(kline 49150 443 140.82.121.33)" drop
sadd "probe SYN to first address of the /31 is dropped"      "$(kline 49150 443 192.30.255.164)" drop
sadd "probe SYN to second address of the /31 is dropped"     "$(kline 49150 443 192.30.255.165)" drop
sadd "address after the /31 stays counted"                   "$(kline 49150 443 192.30.255.166)" keep
sadd "address before the /31 stays counted"                  "$(kline 49150 443 192.30.255.163)" keep
sadd "neighbour .32 of a carved /32 stays counted"           "$(kline 49150 443 140.82.121.32)" keep
sadd "neighbour .35 of a carved /32 stays counted"           "$(kline 49150 443 140.82.121.35)" keep
sadd "sub-mutation: in-range SPT to an unrelated DST stays counted" "$(kline 49150 443 8.8.8.8)" keep
sadd "sub-mutation: carved DST from a non-probe port stays counted" "$(kline 40000 443 140.82.121.34)" keep
sadd "carved DST, in-range SPT, wrong DPT stays counted"     "$(kline 49150 80 140.82.121.34)" keep
sadd "SPT just below the range stays counted"                "$(kline 49099 443 140.82.121.34)" keep
sadd "SPT just above the range stays counted"                "$(kline 49200 443 140.82.121.34)" keep
sadd "SPT at range low bound is dropped"                     "$(kline 49100 443 140.82.121.34)" drop
sadd "SPT at range high bound is dropped"                    "$(kline 49199 443 140.82.121.34)" drop
sadd "carved address only as SRC (not DST) stays counted"    "$(kline 49150 443 10.0.0.1 140.82.121.34)" keep
sadd "dns-exfil line from the range, DPT 53, stays counted"  "Oct  1 12:00:00 host kernel: egress-dns-exfil: IN=docker0 SRC=172.17.0.2 DST=9.9.9.9 PROTO=UDP SPT=49150 DPT=53" keep
sadd "line with no SPT/DPT/DST fields stays counted"         "Oct  1 12:00:00 host kernel: egress-blocked: garbled" keep

run_filter() { printf '%s\n' "$1" | filter_ghcr_probe_drops; }
SROWS=0
for i in "${!S_LABEL[@]}"; do
  SROWS=$((SROWS + 1))
  out="$(run_filter "${S_LINE[$i]}")"
  if [[ -z "$out" ]]; then got=drop; else got=keep; fi
  check "sampler: ${S_LABEL[$i]}" "${S_WANT[$i]}" "$got"
done
check "sampler table instrument: every row ran" "${#S_LABEL[@]}" "$SROWS"
if [[ "$SROWS" -ge 15 ]]; then pass "sampler table instrument: row-count floor (>= 15, ran $SROWS)"; else fail "sampler table instrument: row-count floor (ran $SROWS)"; fi

echo "-- filter fails toward counting on any parse problem --"
ONE="$(kline 49150 443 140.82.121.34)"
try_cidr() { # try_cidr label  <file content from stdin>  -> expect the probe line kept
  assert_fixture_dir "$WORK"
  cat > "$CIDR_FIXTURE"
  if [[ -n "$(run_filter "$ONE")" ]]; then pass "no suppression: $1"; else fail "suppressed despite: $1"; fi
}
try_cidr "no Excluded header at all" <<<$'140.82.112.0/20'
try_cidr "header /16 (shorter than /28)" <<<$'# Excluded (GitHub Packages frontends): 140.82.0.0/16'
try_cidr "header /0" <<<$'# Excluded (GitHub Packages frontends): 0.0.0.0/0'
try_cidr "header /27" <<<$'# Excluded (GitHub Packages frontends): 140.82.121.32/27'
try_cidr "header not a CIDR" <<<$'# Excluded (GitHub Packages frontends): garbage'
try_cidr "header with a leading-zero octet" <<<$'# Excluded (GitHub Packages frontends): 140.82.121.034/32'
try_cidr "header octet > 255" <<<$'# Excluded (GitHub Packages frontends): 140.82.121.300/32'
try_cidr "header with trailing junk" <<<$'# Excluded (GitHub Packages frontends): 140.82.121.34/32 trailing'
try_cidr "one good header plus one bad header" <<<$'# Excluded (GitHub Packages frontends): 140.82.121.33/32\n# Excluded (GitHub Packages frontends): 140.82.121.34/99'
try_cidr "empty header value" <<<$'# Excluded (GitHub Packages frontends): '
try_cidr "header with a different label" <<<$'# Excluded (Other): 140.82.121.34/32'
try_cidr "header missing the space after #" <<<$'#Excluded (GitHub Packages frontends): 140.82.121.34/32'
CIDR_FILE="$WORK/does-not-exist.txt"
if [[ -n "$(run_filter "$ONE")" ]]; then pass "no suppression: CIDR file missing"; else fail "suppressed despite: CIDR file missing"; fi
CIDR_FILE="$CIDR_FIXTURE"
# control: the same single-line fixture, well-formed, MUST suppress (else the rows above prove nothing)
assert_fixture_dir "$WORK"
printf '# Excluded (GitHub Packages frontends): 140.82.121.34/32\n' > "$CIDR_FIXTURE"
if [[ -z "$(run_filter "$ONE")" ]]; then pass "control: a well-formed single header DOES suppress the probe SYN"; else fail "control: well-formed header did not suppress"; fi

# --- 5. resolver wiring (static anchors for what the extraction cannot see) ---------------
echo "-- resolver wiring --"
ln_call="$(grep -n '^run_ghcr_probe ||' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_heal="$(grep -n 'enforcement rules missing' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_drops="$(grep -n 'filter_ghcr_probe_drops ||' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_ok="$(grep -n '^sentry_checkin ok' "$RESOLVER" | head -1 | cut -d: -f1)"
if [[ -n "$ln_call" && -n "$ln_heal" && -n "$ln_drops" && -n "$ln_ok" && "$ln_heal" -lt "$ln_call" && "$ln_call" -lt "$ln_drops" && "$ln_drops" -lt "$ln_ok" ]]; then
  pass "probe call sits after self-heal, before the drop sampler and sentry_checkin ok"
else
  fail "probe call ordering (heal=$ln_heal call=$ln_call drops=$ln_drops ok=$ln_ok)"
fi
n_lo="$(grep -cF 'GHCR_PROBE_PORT_LO' "$RESOLVER")"
if [[ "$n_lo" -ge 3 ]]; then pass "GHCR_PROBE_PORT_LO referenced at definition, curl flag and sampler ($n_lo)"; else fail "GHCR_PROBE_PORT_LO references ($n_lo)"; fi
if grep -qF -- '--local-port "${GHCR_PROBE_PORT_LO}-${GHCR_PROBE_PORT_HI}"' "$RESOLVER"; then pass "curl --local-port derives from the constants"; else fail "curl --local-port constants"; fi
if grep -qF -- '-v plo="$GHCR_PROBE_PORT_LO" -v phi="$GHCR_PROBE_PORT_HI"' "$RESOLVER"; then pass "sampler awk derives from the constants"; else fail "sampler awk constants"; fi
if grep -qE "egress-\(blocked\|dns-exfil\): " "$RESOLVER"; then pass "both drop prefixes (trailing space) still counted"; else fail "drop-prefix literal"; fi

echo
echo "ghcr-probe suite: $PASS passed, $FAIL failed"
if [[ "$FAIL" -gt 0 ]]; then exit 1; fi
exit 0
