#!/usr/bin/env bash
# Probe + sampler table for the GHCR deny probe in cron-egress-resolve.sh (#9275,
# ADR-096 5.3b-iii). Guard 2 of the plan's Guard Contract.
#
# NO LOGIC COPY: ghcr_probe_verdict / ghcr_probe_blind_step / run_ghcr_probe /
# filter_ghcr_probe_drops / ghcr_probe_filter_or_keep / strict_ipv4_lines and the
# GHCR_PROBE_* / CIDR_FILE assignments are extracted from the resolver by awk/grep on
# their definition lines and `source`d. Seams stubbed: the state dir (FAILCOUNT_DIR under
# a mktemp root), the clock (run_ghcr_probe's $1), sentry_event / container_running / log
# (recording functions), docker + nft (PATH shims that read canned output per probed
# name). Every table is driven by an array whose row count is floored, so a runner that
# iterates zero rows is RED, not green.
#
# Accounting: every verdict is recorded through check() or okc(), each of which bumps
# CASES at the call site before it records exactly one PASS or FAIL. The suite end asserts
# PASS + FAIL == CASES (a branch that records nothing, or a stray direct pass/fail call, is
# RED) and the helpers themselves are negative-controlled before any real row runs.
# shellcheck disable=SC2329,SC2016  # stubs are invoked via the sourced library; payloads are intentionally single-quoted
set -uo pipefail

export TMPDIR="${TMPDIR:-/var/tmp}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLVER="${RESOLVER:-$SCRIPT_DIR/cron-egress-resolve.sh}"
COMMITTED_CIDR="$SCRIPT_DIR/cron-egress-allowlist-cidr.txt"

PASS=0
FAIL=0
CASES=0
pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }
check() { # check "label" want got
  CASES=$((CASES + 1))
  if [[ "$2" == "$3" ]]; then pass "$1"; else fail "$1 (want='$2' got='$3')"; fi
}
okc() { # okc "label" <exit status of the test just run>  (0 = holds)
  CASES=$((CASES + 1))
  if [[ "$2" == "0" ]]; then pass "$1"; else fail "$1"; fi
}

assert_fixture_dir() {
  case "${1-}" in
    "") printf 'FATAL: fixture dir is EMPTY; git -C "" would operate on %s\n' "$PWD" >&2; exit 2 ;;
    */../*|*/..) printf 'FATAL: fixture dir %s contains ..; refusing\n' "$1" >&2; exit 2 ;;
    /proc/*|/sys/*|/dev/*) printf 'FATAL: fixture dir %s is a synthetic-fs path; refusing\n' "$1" >&2; exit 2 ;;
    /|//|/.) printf 'FATAL: fixture dir resolves to the filesystem root; refusing\n' >&2; exit 2 ;;
    /*) : ;;
    *)  printf 'FATAL: fixture dir %s is RELATIVE; refusing\n' "$1" >&2; exit 2 ;;
  esac
}

WORK="$(mktemp -d "${TMPDIR}/ghcr-probe-test.XXXXXX")"
assert_fixture_dir "$WORK"
cleanup() { assert_fixture_dir "$WORK"; rm -rf "$WORK"; }
trap cleanup EXIT

[[ -f "$RESOLVER" ]] || { echo "FATAL: resolver not found: $RESOLVER" >&2; exit 2; }

# --- negative control of the verdict-owning helpers -------------------------------------------
# Drive check() and okc() once with a MISMATCH and once with a match, redirected so the
# deliberate FAIL never reaches the transcript. FAIL must move for the mismatch and PASS for the
# match; then PASS/FAIL/CASES are unwound. Reported with printf + exit directly (never through
# check/fail): a helper that always passes would otherwise vouch for itself.
nc_p=$PASS; nc_f=$FAIL; nc_c=$CASES
check "negative-control mismatch" "want-A" "got-B" > "$WORK/nc1.out"
okc "negative-control failing condition" 1 > "$WORK/nc2.out"
check "negative-control match" "same" "same" > "$WORK/nc3.out"
okc "negative-control holding condition" 0 > "$WORK/nc4.out"
if (( FAIL - nc_f != 2 || PASS - nc_p != 2 || CASES - nc_c != 4 )) \
  || ! grep -q '^  FAIL: negative-control mismatch' "$WORK/nc1.out" \
  || ! grep -q '^  FAIL: negative-control failing condition' "$WORK/nc2.out" \
  || ! grep -q '^  PASS: negative-control match' "$WORK/nc3.out" \
  || ! grep -q '^  PASS: negative-control holding condition' "$WORK/nc4.out"; then
  printf '[FATAL] negative control: check()/okc() did not record the expected PASS/FAIL (dP=%d dF=%d dC=%d); the helpers cannot vouch for any row.\n' \
    "$((PASS - nc_p))" "$((FAIL - nc_f))" "$((CASES - nc_c))" >&2
  exit 1
fi
PASS=$nc_p; FAIL=$nc_f; CASES=$nc_c
echo "-- negative control: check()/okc() record a deliberate mismatch as FAIL (unwound) --"

# --- extraction (no logic copy) --------------------------------------------------------
extract_fn() { # extract_fn name  (definition line `name() {` through the closing `}` at col 0)
  awk -v n="$1" '
    $0 == n "() {" { p = 1 }
    p { print }
    p && $0 == "}" { exit }' "$RESOLVER"
}

CIDR_FIXTURE="$WORK/cidr.txt"
export CIDR_FILE="$CIDR_FIXTURE"
LIB="$WORK/probe-lib.sh"
LIB_FNS="ghcr_probe_verdict ghcr_probe_blind_step run_ghcr_probe filter_ghcr_probe_drops ghcr_probe_filter_or_keep strict_ipv4_lines"
assert_fixture_dir "$WORK"
{
  echo '# generated by cron-egress-ghcr-probe.test.sh from cron-egress-resolve.sh'
  grep -E '^GHCR_PROBE_[A-Z_]+=' "$RESOLVER"
  # The resolver's CIDR_FILE default is env-overridable; the test pre-exports CIDR_FILE.
  grep -E '^CIDR_FILE=' "$RESOLVER"
  for fn in $LIB_FNS; do
    extract_fn "$fn"
  done
} > "$LIB"

echo "-- extraction (non-vacuous) --"
EXTRACT_ROWS=0
for fn in $LIB_FNS; do
  EXTRACT_ROWS=$((EXTRACT_ROWS + 1))
  n="$(extract_fn "$fn" | wc -l)"
  [[ "$n" -ge 6 ]]; okc "extracted $fn ($n lines; expected >= 6)" $?
done
for c in GHCR_PROBE_PORT_LO GHCR_PROBE_PORT_HI GHCR_PROBE_INTERVAL GHCR_PROBE_BLIND_AT GHCR_PROBE_NAMES GHCR_PROBE_BUDGET_SECS; do
  EXTRACT_ROWS=$((EXTRACT_ROWS + 1))
  grep -qE "^$c=" "$LIB"; okc "constant $c extracted" $?
done
bash -n "$LIB"; okc "extracted library parses" $?
if [[ "$EXTRACT_ROWS" -lt 12 ]]; then
  printf '[FATAL] extraction table: only %d rows ran, expected >= 12.\n' "$EXTRACT_ROWS" >&2
  exit 1
fi

# --- stubs ------------------------------------------------------------------------------
MOCK="$WORK/mock"
SHIM="$WORK/shim"
EVENTS="$WORK/events.tsv"
LOGF="$WORK/log.txt"
FAILCOUNT_DIR="$WORK/state"
export FAILCOUNT_DIR
assert_fixture_dir "$WORK"
mkdir -p "$MOCK" "$SHIM" "$FAILCOUNT_DIR"

cat > "$SHIM/docker" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$MOCK_DIR/docker.args"
url="${*: -1}"; name="${url#https://}"; name="${name%/}"
if [[ -f "$MOCK_DIR/$name.out" ]]; then cat "$MOCK_DIR/$name.out"; fi
if [[ -f "$MOCK_DIR/$name.flood" ]]; then
  # 5 MB of junk after the real output. tr's status is 141 when the reader hung up early
  # (the cap held) and 0 when every byte was consumed (the cap is missing).
  head -c 5242880 /dev/zero | tr '\0' 'A'
  echo "${PIPESTATUS[1]}" > "$MOCK_DIR/$name.producer_rc"
fi
rc=0
if [[ -f "$MOCK_DIR/$name.rc" ]]; then rc="$(cat "$MOCK_DIR/$name.rc")"; fi
exit "$rc"
SHIM_EOF
cat > "$SHIM/nft" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$MOCK_DIR/nft.args"
rc=1
case "$*" in
  *soleur_egress_allow_cidr*) f="$MOCK_DIR/nft.cidr.rc" ;;
  *) f="$MOCK_DIR/nft.name.rc" ;;
esac
if [[ -f "$f" ]]; then rc="$(cat "$f")"; fi
exit "$rc"
SHIM_EOF
chmod +x "$SHIM/docker" "$SHIM/nft"
export MOCK_DIR="$MOCK"
export PATH="$SHIM:$PATH"

CONTAINER="soleur-web-platform"
CONTAINER_UP=1
CR_CALLS=0
log() { echo "$*" >> "$LOGF"; }
container_running() { CR_CALLS=$((CR_CALLS + 1)); [[ "$CONTAINER_UP" == "1" ]]; }
sentry_event() { # msg op extra  -> one TSV row: op, msg, compact extra ('' when extra is not JSON)
  local compact
  compact="$(jq -c . <<<"$3" 2>/dev/null || true)"
  printf '%s\t%s\t%s\n' "$2" "$1" "$compact" >> "$EVENTS"
}

# shellcheck disable=SC1090
source "$LIB"

new_state() { # fresh state dir, event log, mock outputs, docker/nft history
  assert_fixture_dir "$WORK"
  rm -rf "$FAILCOUNT_DIR" "$MOCK"
  mkdir -p "$FAILCOUNT_DIR" "$MOCK"
  : > "$EVENTS"
  : > "$LOGF"
  CONTAINER_UP=1
  CR_CALLS=0
  unset CRON_EGRESS_FROM_LOADER
  SECONDS=0
}
mock_probe() { # mock_probe name rc raw
  assert_fixture_dir "$WORK"
  printf '%s' "$3" > "$MOCK/$1.out"
  printf '%s' "$2" > "$MOCK/$1.rc"
}
mock_nft() { # mock_nft cidr_rc name_rc  (exit status of `nft get element` per set)
  printf '%s' "$1" > "$MOCK/nft.cidr.rc"
  printf '%s' "$2" > "$MOCK/nft.name.rc"
}
ev_count() { # ev_count [op]  (count of recorded events, optionally for one op)
  if [[ -n "${1:-}" ]]; then
    awk -F'\t' -v op="$1" '$1 == op { n++ } END { print n + 0 }' "$EVENTS"
  else
    awk 'END { print NR + 0 }' "$EVENTS"
  fi
}
docker_calls() { if [[ -f "$MOCK/docker.args" ]]; then wc -l < "$MOCK/docker.args"; else echo 0; fi; }
counter() { # counter name -> counter-file content ('absent' when missing)
  if [[ -f "$FAILCOUNT_DIR/ghcr_probe.$1.blind" ]]; then cat "$FAILCOUNT_DIR/ghcr_probe.$1.blind"; else echo absent; fi
}
stamp_of() { cat "$FAILCOUNT_DIR/ghcr_probe.stamp" 2>/dev/null || echo absent; }
blind_reasons() { awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3 }' "$EVENTS" | jq -r .reason | sort -u | tr '\n' ','; }

# --- 1. verdict table (strict-mode child per row: nothing may abort the tick) ------------
echo "-- ghcr_probe_verdict table --"
V_LABEL=(); V_RC=(); V_RAW=(); V_WANT=()
vadd() { V_LABEL+=("$1"); V_RC+=("$2"); V_RAW+=("$3"); V_WANT+=("$4"); }

TENKB="$(head -c 10000 /dev/zero | tr '\0' 'A')"
vadd "held: dropped connect, resolver answered"            28  "0.012 0.000000 "                       "held 0.012 0.000000 -"
vadd "held (must-PASS non-canonical): rc28 nl=0.012 tc=0"  28  "0.012000 0.000000 "                     "held 0.012000 0.000000 -"
vadd "hung resolver is NOT held (rc28, nl=0)"              28  "0.000000 0.000000 "                     "inconclusive 0.000000 0.000000 -"
vadd "reached: handshake completed"                         0  "0.012 0.401402 140.82.121.34"          "reached 0.012 0.401402 140.82.121.34"
vadd "reached even when TLS fails after connect (rc35)"    35  "0.012 0.200000 140.82.121.34"          "reached 0.012 0.200000 140.82.121.34"
vadd "reached even at rc28 when time_connect > 0 (TLS stall after the handshake)" 28 "0.012 0.4 140.82.121.34" "reached 0.012 0.4 140.82.121.34"
vadd "reached with a 1ms connect"                           0  "0.001 0.001 140.82.121.33"             "reached 0.001 0.001 140.82.121.33"
vadd "DNS failure (rc6) is inconclusive"                    6  "0.000000 0.000000 "                     "inconclusive 0.000000 0.000000 -"
vadd "connection refused (rc7) is inconclusive"             7  "0.010 0.000000 "                        "inconclusive 0.010 0.000000 -"
vadd "docker exec 125 is inconclusive"                    125  ""                                        "inconclusive - - -"
vadd "docker exec 126 is inconclusive"                    126  ""                                        "inconclusive - - -"
vadd "docker exec 127 (curl missing) is inconclusive"     127  ""                                        "inconclusive - - -"
vadd "timeout(1) kill 124 is inconclusive"                124  ""                                        "inconclusive - - -"
vadd "rc0 with tc=0 is inconclusive"                        0  "0.012 0.000000 "                        "inconclusive 0.012 0.000000 -"
vadd "empty output, rc28 is inconclusive"                  28  ""                                        "inconclusive - - -"
vadd "hostile time_connect: command substitution"          28  '0.012 a[$(touch '"$WORK"'/PWNED)] 1.2.3.4' "inconclusive - - -"
vadd "hostile time_connect: backticks"                     28  '0.012 `touch '"$WORK"'/PWNED` '          "inconclusive - - -"
vadd "hostile time_namelookup"                             28  '$(touch '"$WORK"'/PWNED) 0.000000 '      "inconclusive - - -"
vadd "10 kB single line"                                   28  "$TENKB"                                  "inconclusive - - -"
vadd "10 kB line after valid prefix fields"                 0  "0.012 0.400 $TENKB"                     "reached 0.012 0.400 -"
vadd "scientific notation timing is rejected"              28  "0.012 1e-3 "                             "inconclusive - - -"
vadd "negative timing is rejected"                         28  "0.012 -0.5 "                            "inconclusive - - -"
vadd "extra trailing field is rejected"                     0  "0.012 0.4 140.82.121.34 EXTRA"         "inconclusive - - -"
vadd "reached with a non-IPv4 remote_ip (name kept out)"    0  "0.012 0.4 not-an-ip"                    "reached 0.012 0.4 -"
vadd "reached with an out-of-range octet"                   0  "0.012 0.4 999.1.1.1"                    "reached 0.012 0.4 -"
vadd "reached with octet 256 (one past the bound)"          0  "0.012 0.4 1.2.3.256"                    "reached 0.012 0.4 -"
vadd "reached with octet 255 (the bound itself is valid)"   0  "0.012 0.4 255.255.255.255"              "reached 0.012 0.4 255.255.255.255"
vadd "reached with a leading-zero octet"                    0  "0.012 0.4 01.2.3.4"                     "reached 0.012 0.4 -"
vadd "reached with a shell-metachar remote_ip"              0  '0.012 0.4 1.2.3.4;rm'                   "reached 0.012 0.4 -"
vadd "multi-line output: only the first line is read"       0  $'0.012 0.4 1.1.1.1\n{"x":1}'            "reached 0.012 0.4 1.1.1.1"
vadd "non-numeric rc"                                    "x1"  "0.012 0.000000 "                        "inconclusive - - -"
vadd "IPv6 remote_ip is not IPv4"                           0  "0.012 0.4 2606:50c0:8000::154"          "reached 0.012 0.4 -"

table_verdict() { # table_verdict tag  -> runs every row; prints nothing but rows; sets ROWS_RUN
  ROWS_RUN=0
  local i got
  for i in "${!V_LABEL[@]}"; do
    ROWS_RUN=$((ROWS_RUN + 1))
    got="$(bash -euo pipefail -c 'source "$1"; ghcr_probe_verdict "$2" "$3"' _ "$LIB" "${V_RC[$i]}" "${V_RAW[$i]}" 2>/dev/null || echo "ABORTED-rc=$?")"
    check "${1}verdict: ${V_LABEL[$i]}" "${V_WANT[$i]}" "$got"
  done
}
table_verdict ""
check "verdict table instrument: every row ran" "${#V_LABEL[@]}" "$ROWS_RUN"
if [[ "$ROWS_RUN" -lt 32 ]]; then
  printf '[FATAL] verdict table: only %d rows ran, expected >= 32.\n' "$ROWS_RUN" >&2
  exit 1
fi
[[ ! -e "$WORK/PWNED" ]] && c=0 || c=1; okc "hostile output executed nothing (no PWNED file)" "$c"

# --- 2. blind counter ---------------------------------------------------------------------
echo "-- ghcr_probe_blind_step --"
new_state
seq_out=""
for _ in $(seq 1 13); do seq_out+="$(ghcr_probe_blind_step inconclusive ghcr.io) "; done
check "counter counts 1..13 on consecutive inconclusive" "1 2 3 4 5 6 7 8 9 10 11 12 13 " "$seq_out"
check "held resets the counter" "0" "$(ghcr_probe_blind_step held ghcr.io)"
check "held removes the state file" "absent" "$(counter ghcr.io)"
ghcr_probe_blind_step inconclusive docker.pkg.github.com >/dev/null
ghcr_probe_blind_step absent docker.pkg.github.com >/dev/null
check "absent increments like inconclusive" "2" "$(counter docker.pkg.github.com)"
check "reached resets the counter" "0" "$(ghcr_probe_blind_step reached docker.pkg.github.com)"
check "counters are per name" "absent" "$(counter ghcr.io)"
printf 'garbage' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
check "corrupt counter file restarts at 1" "1" "$(ghcr_probe_blind_step inconclusive ghcr.io)"
printf '$(touch %s/PWNED)' "$WORK" > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
check "hostile counter file is not evaluated" "1" "$(ghcr_probe_blind_step inconclusive ghcr.io)"
[[ ! -e "$WORK/PWNED" ]] && c=0 || c=1; okc "hostile counter file executed nothing" "$c"

# --- 3. dispatch ----------------------------------------------------------------------------
echo "-- run_ghcr_probe dispatch --"
HELD="0.012 0.000000 "
REACHED="0.012 0.401402 140.82.121.34"

new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "both names probed on a compliant first run (second name not skipped)" "2" "$(docker_calls)"
check "held on both names emits nothing" "0" "$(ev_count)"
check "stamp file written" "10000" "$(stamp_of)"
args="$(cat "$MOCK/docker.args")"
for want in 'ghcr.io/' 'docker.pkg.github.com/'; do
  grep -qF "https://$want" <<<"$args"; okc "probed https://$want" $?
done
first="$(sed -n 1p "$MOCK/docker.args")"
[[ "$first" == "exec $CONTAINER curl -q -s -o /dev/null --noproxy * --connect-timeout 5 --max-time 8 --local-port 49100-49199 -w "* ]] && c=0 || c=1
okc "curl argv: container name, -q first, --noproxy '*', timeouts, reserved port range ($first)" "$c"
if grep -q -- '--retry' <<<"$args"; then rc_retry=1; else rc_retry=0; fi
okc "no --retry flag" "$rc_retry"
check "held rows: rc 28 survives the capped pipeline (counters never rose)" "absent" "$(counter ghcr.io)"

echo "-- container output is capped before it is buffered --"
new_state
mock_probe ghcr.io 0 "$REACHED"$'\n'; mock_probe docker.pkg.github.com 28 "$HELD"$'\n'
: > "$MOCK/ghcr.io.flood"; : > "$MOCK/docker.pkg.github.com.flood"
t0="$(date +%s%N)"
run_ghcr_probe 10000
t1="$(date +%s%N)"
# `tr` exits 141 when the reader hangs up and SIGPIPE is default, and 1 (a write error) when the
# runner's environment ignores SIGPIPE (GitHub Actions does): both mean the cap held. 0 means every
# byte was consumed, i.e. the cap is missing.
producer_cut() { local rc; rc="$(cat "$MOCK/$1.producer_rc" 2>/dev/null || echo absent)"; if [[ "$rc" == 141 || "$rc" == 1 ]]; then echo cut; else echo "$rc"; fi; }
check "flooding container (5 MB): the reader hung up early (producer cut short, never wrote it all)" "cut" "$(producer_cut ghcr.io)"
check "flooding container, second name: reader hung up early" "cut" "$(producer_cut docker.pkg.github.com)"
check "flooding container: reached verdict still correct (one lost event)" "1" "$(ev_count ghcr_deny_lost)"
check "flooding container: lost event carries the real remote_ip" "140.82.121.34" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS" | jq -r .remote_ip)"
check "flooding container: rc 28 + held prefix still reads held (counter absent, no blind)" "absent" "$(counter docker.pkg.github.com)"
[[ $(( (t1 - t0) / 1000000 )) -lt 5000 ]] && c=0 || c=1; okc "flooding container: whole probe returned in under 5 s ($(( (t1 - t0) / 1000000 )) ms)" "$c"
grep -qF -- 'head -c 256' "$RESOLVER"; okc "wiring: capture pipes through head -c 256" $?
grep -qF -- 'exit "${PIPESTATUS[0]}")" || rc=$?' "$RESOLVER"; okc "wiring: exit code taken from PIPESTATUS[0], rc=0/|| rc=\$? form kept" $?
grep -qF -- 'timeout -k 2 15 docker exec' "$RESOLVER"; okc "wiring: timeout carries -k 2 (a docker exec that ignores TERM is killed)" $?

echo "-- rc 28 does not depend on pipefail --"
new_state
printf '7' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
set +o pipefail
run_ghcr_probe 10000
set -o pipefail
check "pipefail OFF: held (rc 28 via PIPESTATUS[0]) still resets the counter" "absent" "$(counter ghcr.io)"

echo "-- cadence gate --"
new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
run_ghcr_probe 10100;  check "100s later: no probe" "2" "$(docker_calls)"
run_ghcr_probe 10269;  check "269s later: no probe" "2" "$(docker_calls)"
run_ghcr_probe 10270;  check "270s later: probe runs (>= 270)" "4" "$(docker_calls)"
run_ghcr_probe 10271;  check "1s after a probe: no probe" "4" "$(docker_calls)"
run_ghcr_probe 10540;  check "270s after the second probe: runs again" "6" "$(docker_calls)"
printf 'garbage' > "$FAILCOUNT_DIR/ghcr_probe.stamp"
run_ghcr_probe 10541;  check "corrupt stamp counts as due" "8" "$(docker_calls)"

echo "-- budget gate (30 s: 10 + 2x17 + 2x10 post-gate, +20 sampler, inside the 120 s unit) --"
new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
CRON_EGRESS_FROM_LOADER=1 run_ghcr_probe 10000
check "loader-invoked tick: probe skipped" "0" "$(docker_calls)"
check "loader-invoked tick: no stamp" "absent" "$(stamp_of)"
SECONDS=99 CRON_EGRESS_FROM_LOADER=1 run_ghcr_probe 10000
check "loader-invoked tick is NOT counted as blind (even when old)" "absent" "$(counter ghcr.io)"
SECONDS=31; run_ghcr_probe 10000
check "tick older than 30s: probe skipped" "0" "$(docker_calls)"
check "tick older than 30s: container_running not consulted (no 10 s docker ps)" "0" "$CR_CALLS"
check "tick older than 30s: no stamp (retried next tick)" "absent" "$(stamp_of)"
check "budget skip steps ghcr.io's blind counter" "1" "$(counter ghcr.io)"
check "budget skip steps docker.pkg.github.com's blind counter" "1" "$(counter docker.pkg.github.com)"
check "a single budget skip emits nothing" "0" "$(ev_count)"
SECONDS=30; run_ghcr_probe 10000
check "tick at exactly 30s still probes" "2" "$(docker_calls)"
check "a real held run resets the budget-skip counter" "absent" "$(counter ghcr.io)"
SECONDS=99; run_ghcr_probe 10100
check "not-yet-due tick is never counted, however old" "2" "$(docker_calls)"
check "not-yet-due old tick leaves counters alone" "absent" "$(counter docker.pkg.github.com)"

echo "-- reached -> ghcr_deny_lost --"
new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "one lost event (one name reached)" "1" "$(ev_count ghcr_deny_lost)"
check "no other event" "1" "$(ev_count)"
msg1="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $2; exit }' "$EVENTS")"
extra1="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
[[ "$msg1" != *'$'* && "$msg1" != *140.82* && "$msg1" != *ghcr.io* && -n "$msg1" ]] && c=0 || c=1; okc "lost message is static (no IP, no name, no \$): $msg1" "$c"
check "lost extra.name" "ghcr.io" "$(jq -r .name <<<"$extra1")"
check "lost extra.remote_ip" "140.82.121.34" "$(jq -r .remote_ip <<<"$extra1")"
check "lost extra.time_connect" "0.401402" "$(jq -r .time_connect <<<"$extra1")"
check "lost extra.in_allow_cidr (nft miss -> false)" "false" "$(jq -r .in_allow_cidr <<<"$extra1")"
check "lost extra.in_allow_name (nft miss -> false)" "false" "$(jq -r .in_allow_name <<<"$extra1")"
jq -e '.file_sha256 and .remediation' <<<"$extra1" >/dev/null; okc "lost extra carries file_sha256 and remediation: $extra1" $?
grep -qF "get element ip filter soleur_egress_allow_cidr { 140.82.121.34 }" "$MOCK/nft.args" 2>/dev/null; okc "in_allow_cidr read from the live CIDR set via nft get element" $?
grep -qF "get element ip filter soleur_egress_allow { 140.82.121.34 }" "$MOCK/nft.args" 2>/dev/null; okc "in_allow_name read from the live by-name set via nft get element" $?

new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 0 "0.01 0.3 140.82.121.33"
mock_nft 0 0
run_ghcr_probe 10000
check "both reached: two lost events" "2" "$(ev_count ghcr_deny_lost)"
check "both lost events share ONE message (one Sentry issue group)" "1" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $2 }' "$EVENTS" | sort -u | wc -l)"
check "in_allow_cidr true when the live CIDR set admits the IP" "true" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS" | jq -r .in_allow_cidr)"
check "in_allow_name true when the by-name set admits the IP" "true" "$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS" | jq -r .in_allow_name)"
run_ghcr_probe 10300
check "reached on every due run (not once)" "4" "$(ev_count ghcr_deny_lost)"

new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
mock_nft 1 0
run_ghcr_probe 10000
extra_n="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
check "carved IP admitted only by NAME: in_allow_cidr false" "false" "$(jq -r .in_allow_cidr <<<"$extra_n")"
check "carved IP admitted only by NAME: in_allow_name true (the two fields are independent)" "true" "$(jq -r .in_allow_name <<<"$extra_n")"
new_state
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
mock_nft 0 1
run_ghcr_probe 10000
extra_c="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
check "IP in the CIDR set only: in_allow_cidr true" "true" "$(jq -r .in_allow_cidr <<<"$extra_c")"
check "IP in the CIDR set only: in_allow_name false" "false" "$(jq -r .in_allow_name <<<"$extra_c")"

new_state
mock_probe ghcr.io 0 "0.012 0.4 not-an-ip"; mock_probe docker.pkg.github.com 28 "$HELD"
mock_nft 0 0
run_ghcr_probe 10000
extra_u="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
check "invalid remote_ip: still a lost event" "1" "$(ev_count ghcr_deny_lost)"
check "invalid remote_ip: remote_ip is '-'" "-" "$(jq -r .remote_ip <<<"$extra_u")"
check "invalid remote_ip: in_allow_cidr is unknown" "unknown" "$(jq -r .in_allow_cidr <<<"$extra_u")"
check "invalid remote_ip: in_allow_name is unknown" "unknown" "$(jq -r .in_allow_name <<<"$extra_u")"
check "invalid remote_ip: nft is never asked about it" "absent" "$(cat "$MOCK/nft.args" 2>/dev/null || echo absent)"

new_state
mock_probe ghcr.io 0 '0.012 0.4 "},"injected":"x'
mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
extra_h="$(awk -F'\t' '$1 == "ghcr_deny_lost" { print $3; exit }' "$EVENTS")"
check "hostile remote_ip cannot inject an extra key" "name,remote_ip,time_connect,in_allow_cidr,in_allow_name,file_sha256,remediation" "$(jq -r 'keys_unsorted | join(",")' <<<"$extra_h" 2>/dev/null || echo INVALID)"
check "hostile remote_ip is replaced by '-'" "-" "$(jq -r .remote_ip <<<"$extra_h" 2>/dev/null || echo INVALID)"

echo "-- sequence: counter 11 then reached --"
new_state
printf '11' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "11-then-reached: exactly one lost" "1" "$(ev_count ghcr_deny_lost)"
check "11-then-reached: no blind event" "0" "$(ev_count ghcr_deny_probe_blind)"
check "11-then-reached: counter reset" "absent" "$(counter ghcr.io)"

echo "-- sequence: counter 23 then reached / held (reset, no blind) --"
new_state
printf '23' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 0 "$REACHED"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "23-then-reached: counter reset" "absent" "$(counter ghcr.io)"
check "23-then-reached: no blind event" "0" "$(ev_count ghcr_deny_probe_blind)"
new_state
printf '23' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "23-then-held: counter reset" "absent" "$(counter ghcr.io)"
check "23-then-held: no event (a reset counter of 0 is not a multiple to emit on)" "0" "$(ev_count)"

echo "-- held resets a prior counter (must-PASS non-canonical row) --"
new_state
printf '7' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
mock_probe ghcr.io 28 "0.012 0.000000 "; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "rc28 nl=0.012 tc=0 with prior 7: held, counter reset" "absent" "$(counter ghcr.io)"
check "...and no event" "0" "$(ev_count)"

echo "-- blind: inconclusive runs, first emit at 12, hourly re-emit at every multiple --"
new_state
mock_probe ghcr.io 127 ""; mock_probe docker.pkg.github.com 28 "0.000000 0.000000 "
now=10000
for _ in $(seq 1 11); do run_ghcr_probe "$now"; now=$((now + 300)); done
check "11 inconclusive runs: no blind event yet" "0" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"; now=$((now + 300))
check "12th inconclusive run: one blind event per name (2)" "2" "$(ev_count ghcr_deny_probe_blind)"
check "blind reason is inconclusive" "inconclusive," "$(blind_reasons)"
run_ghcr_probe "$now"; now=$((now + 300))
check "13th run: not re-emitted" "2" "$(ev_count ghcr_deny_probe_blind)"
for _ in $(seq 14 23); do run_ghcr_probe "$now"; now=$((now + 300)); done
check "23rd run: still only the first emission (13..23 silent)" "2" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"; now=$((now + 300))
check "24th run: re-emitted once per name (hourly, a failed POST is retried)" "4" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"; now=$((now + 300))
check "25th run: silent again" "4" "$(ev_count ghcr_deny_probe_blind)"
blind_msgs="$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $2 }' "$EVENTS" | sort -u | wc -l)"
check "blind message is one static literal" "1" "$blind_msgs"
if awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $2 }' "$EVENTS" | grep -qE '[$]|ghcr[.]io'; then rc_static=1; else rc_static=0; fi
okc "blind message has no \$ / name" "$rc_static"
check "blind extra.last_rc" "127" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .last_rc)"
check "blind extra.name present" "ghcr.io" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .name)"

new_state
printf '35' > "$FAILCOUNT_DIR/ghcr_probe.ghcr.io.blind"
printf '34' > "$FAILCOUNT_DIR/ghcr_probe.docker.pkg.github.com.blind"
mock_probe ghcr.io 127 ""; mock_probe docker.pkg.github.com 127 ""
run_ghcr_probe 10000
check "counter 35 -> 36 emits (a multiple of 12, not just 12 and 24); counter 34 -> 35 does not" "1" "$(ev_count ghcr_deny_probe_blind)"
check "...and it is the name at 36" "ghcr.io" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .name)"

echo "-- blind: container absent x12 (counted skip, not silent) --"
new_state
CONTAINER_UP=0
now=10000
for _ in $(seq 1 11); do run_ghcr_probe "$now"; now=$((now + 300)); done
check "11 absent runs: no blind event yet" "0" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe "$now"
check "12th absent run: blind event per name" "2" "$(ev_count ghcr_deny_probe_blind)"
check "absent runs never touch docker" "0" "$(docker_calls)"
check "blind reason is container_absent" "container_absent," "$(blind_reasons)"
check "absent skip never emits lost" "0" "$(ev_count ghcr_deny_lost)"

echo "-- blind: budget skips x12, x24 (a probe that never runs is not silent) --"
new_state
mock_probe ghcr.io 28 "$HELD"; mock_probe docker.pkg.github.com 28 "$HELD"
SECONDS=45
for _ in $(seq 1 11); do run_ghcr_probe 10000; done
check "11 budget-skipped ticks: no blind event yet" "0" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe 10000
check "12th budget-skipped tick: blind event per name" "2" "$(ev_count ghcr_deny_probe_blind)"
check "blind reason is budget_skipped" "budget_skipped," "$(blind_reasons)"
check "budget-skip blind extra.last_rc is '-' (no probe ran)" "-" "$(awk -F'\t' '$1 == "ghcr_deny_probe_blind" { print $3; exit }' "$EVENTS" | jq -r .last_rc)"
for _ in $(seq 13 23); do run_ghcr_probe 10000; done
check "budget skips 13..23 silent" "2" "$(ev_count ghcr_deny_probe_blind)"
run_ghcr_probe 10000
check "24th budget-skipped tick: re-emitted" "4" "$(ev_count ghcr_deny_probe_blind)"
check "budget skips never touch docker" "0" "$(docker_calls)"
check "budget skips never emit lost" "0" "$(ev_count ghcr_deny_lost)"

echo "-- hostile probe output through dispatch --"
new_state
mock_probe ghcr.io 28 '0.012 a[$(touch '"$WORK"'/PWNED)] 1.2.3.4'
mock_probe docker.pkg.github.com 0 "$TENKB"
run_ghcr_probe 10000
check "hostile outputs: inconclusive, no event" "0" "$(ev_count)"
check "hostile outputs counted toward blind" "1" "$(counter ghcr.io)"
[[ ! -e "$WORK/PWNED" ]] && c=0 || c=1; okc "dispatch executed nothing from hostile output" "$c"

echo "-- independent per-name state --"
new_state
mock_probe ghcr.io 127 ""; mock_probe docker.pkg.github.com 28 "$HELD"
run_ghcr_probe 10000
check "ghcr.io inconclusive counter" "1" "$(counter ghcr.io)"
check "docker.pkg.github.com held counter" "absent" "$(counter docker.pkg.github.com)"

# --- 4. sampler filter -----------------------------------------------------------------------
echo "-- filter_ghcr_probe_drops --"
assert_fixture_dir "$WORK"
cat > "$CIDR_FIXTURE" <<'CIDR_EOF'
# Container egress CIDR allowlist (synthesized fixture)
# Excluded (GitHub Packages frontends): 140.82.121.33/32
# Excluded (GitHub Packages frontends): 140.82.121.34/32
# Excluded (GitHub Packages frontends): 192.30.255.164/31
140.82.112.0/20
CIDR_EOF
kline() { # kline spt dpt dst [src]
  printf 'Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 SRC=%s DST=%s LEN=60 TOS=0x00 PROTO=TCP SPT=%s DPT=%s WINDOW=64240 SYN\n' "${4:-172.17.0.2}" "$3" "$1" "$2"
}
S_LABEL=(); S_LINE=(); S_WANT=()
sadd() { S_LABEL+=("$1"); S_LINE+=("$2"); S_WANT+=("$3"); }
sadd "probe SYN to carved /32 is dropped"                    "$(kline 49150 443 140.82.121.34)" drop
sadd "probe SYN to the other carved /32 is dropped"          "$(kline 49150 443 140.82.121.33)" drop
sadd "probe SYN to first address of the /31 is dropped"      "$(kline 49150 443 192.30.255.164)" drop
sadd "probe SYN to second address of the /31 is dropped"     "$(kline 49150 443 192.30.255.165)" drop
sadd "address after the /31 stays counted"                   "$(kline 49150 443 192.30.255.166)" keep
sadd "address before the /31 stays counted"                  "$(kline 49150 443 192.30.255.163)" keep
sadd "neighbour .32 of a carved /32 stays counted"           "$(kline 49150 443 140.82.121.32)" keep
sadd "neighbour .35 of a carved /32 stays counted"           "$(kline 49150 443 140.82.121.35)" keep
sadd "sub-mutation: in-range SPT to an unrelated DST stays counted" "$(kline 49150 443 8.8.8.8)" keep
sadd "sub-mutation: carved DST from a non-probe port stays counted" "$(kline 40000 443 140.82.121.34)" keep
sadd "carved DST, in-range SPT, wrong DPT stays counted"     "$(kline 49150 80 140.82.121.34)" keep
sadd "SPT just below the range stays counted"                "$(kline 49099 443 140.82.121.34)" keep
sadd "SPT just above the range stays counted"                "$(kline 49200 443 140.82.121.34)" keep
sadd "SPT at range low bound is dropped"                     "$(kline 49100 443 140.82.121.34)" drop
sadd "SPT at range high bound is dropped"                    "$(kline 49199 443 140.82.121.34)" drop
sadd "carved address only as SRC (not DST) stays counted"    "$(kline 49150 443 10.0.0.1 140.82.121.34)" keep
sadd "dns-exfil line from the range, DPT 53, stays counted"  "Oct  1 12:00:00 host kernel: egress-dns-exfil: IN=docker0 SRC=172.17.0.2 DST=9.9.9.9 PROTO=UDP SPT=49150 DPT=53" keep
sadd "line with no SPT/DPT/DST fields stays counted"         "Oct  1 12:00:00 host kernel: egress-blocked: garbled" keep
# Assumed format is nf_log_ipv4's: `... SRC=<a> DST=<b> LEN=.. TOS=.. PREC=.. TTL=.. ID=.. DF PROTO=TCP SPT=.. DPT=.. WINDOW=.. RES=.. SYN URGP=0`.
sadd "full nf_log_ipv4 line (MAC/PHYSIN/TTL/DF) from a probe is still dropped" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 PHYSIN=veth1a2b MAC=02:42:ac:11:00:02:02:42:ac:11:00:01:08:00 SRC=172.17.0.2 DST=140.82.121.34 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=1234 DF PROTO=TCP SPT=49150 DPT=443 WINDOW=64240 RES=0x00 SYN URGP=0" drop
sadd "UDP/443 to a carved address from the probe range stays counted (QUIC is not the probe)" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 SRC=172.17.0.2 DST=140.82.121.34 LEN=60 TOS=0x00 PROTO=UDP SPT=49150 DPT=443 LEN=40" keep
sadd "ICMP-error inner-header forgery (outer DST off the carve) stays counted" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 SRC=172.17.0.2 DST=8.8.8.8 LEN=88 TOS=0x00 PROTO=ICMP TYPE=3 CODE=1 [SRC=8.8.8.8 DST=140.82.121.34 LEN=60 TOS=0x00 PROTO=TCP SPT=49150 DPT=443 WINDOW=64240 ]" keep
sadd "defence in depth: a TCP line carrying any '[SRC=' inner header is never discarded" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 OUT=eth0 SRC=172.17.0.2 DST=140.82.121.34 PROTO=TCP SPT=49150 DPT=443 [SRC=1.1.1.1 DST=2.2.2.2 ]" keep
sadd "FIRST SPT/DPT/DST win: trailing forged tokens cannot turn an off-carve connect into a probe" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=8.8.8.8 PROTO=TCP SPT=40000 DPT=80 SPT=49150 DPT=443 DST=140.82.121.34" keep
sadd "FIRST PROTO wins: a later PROTO=TCP cannot rescue a UDP line" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=140.82.121.34 PROTO=UDP SPT=49150 DPT=443 PROTO=TCP" keep

# One token at a time: each row duplicates exactly ONE of SPT/DPT/DST so that only that token's
# first-vs-last choice decides the verdict (a combined row lets the other tokens mask the mutant).
sadd "FIRST SPT wins on its own (later in-range SPT cannot make a 40000 connect a probe)" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=140.82.121.34 PROTO=TCP SPT=40000 DPT=443 SPT=49150" keep
sadd "FIRST DPT wins on its own (later DPT=443 cannot make a port-80 connect a probe)" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=140.82.121.34 PROTO=TCP SPT=49150 DPT=80 DPT=443" keep
sadd "FIRST DST wins on its own (later carved DST cannot hide an off-carve destination)" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=8.8.8.8 PROTO=TCP SPT=49150 DPT=443 DST=140.82.121.34" keep
sadd "SCTP to a carved address from the probe range stays counted (only PROTO=TCP is the probe)" \
  "Oct  1 12:00:00 host kernel: egress-blocked: IN=docker0 SRC=172.17.0.2 DST=140.82.121.34 PROTO=SCTP SPT=49150 DPT=443" keep

run_filter() { printf '%s\n' "$1" | filter_ghcr_probe_drops; }
SROWS=0
table_sampler() { # table_sampler tag
  local i out got
  SROWS=0
  for i in "${!S_LABEL[@]}"; do
    SROWS=$((SROWS + 1))
    out="$(run_filter "${S_LINE[$i]}")"
    if [[ -z "$out" ]]; then got=drop; else got=keep; fi
    check "${1}sampler: ${S_LABEL[$i]}" "${S_WANT[$i]}" "$got"
  done
}
table_sampler ""
check "sampler table instrument: every row ran" "${#S_LABEL[@]}" "$SROWS"
if [[ "$SROWS" -lt 28 ]]; then
  printf '[FATAL] sampler table: only %d rows ran, expected >= 28.\n' "$SROWS" >&2
  exit 1
fi

echo "-- filter against header variants (the file's own parse decides) --"
ONE="$(kline 49150 443 140.82.121.34)"
CIDR_ROWS=0
cidr_case() { # cidr_case label want(keep|drop) line   <fixture file content on stdin>
  assert_fixture_dir "$WORK"
  cat > "$CIDR_FIXTURE"
  CIDR_ROWS=$((CIDR_ROWS + 1))
  local out got
  out="$(run_filter "$3")"
  if [[ -z "$out" ]]; then got=drop; else got=keep; fi
  check "cidr: $1" "$2" "$got"
}
H='# Excluded (GitHub Packages frontends): '
cidr_case "no Excluded header at all: no suppression" keep "$ONE" <<<$'140.82.112.0/20'
cidr_case "header /16 (shorter than /28): no suppression" keep "$ONE" <<<"${H}140.82.0.0/16"
cidr_case "header /0: no suppression" keep "$ONE" <<<"${H}0.0.0.0/0"
cidr_case "header /27: no suppression" keep "$ONE" <<<"${H}140.82.121.32/27"
cidr_case "header not a CIDR: no suppression" keep "$ONE" <<<"${H}garbage"
cidr_case "header with a leading-zero octet: no suppression" keep "$ONE" <<<"${H}140.82.121.034/32"
cidr_case "header octet 300: no suppression" keep "$ONE" <<<"${H}140.82.121.300/32"
cidr_case "header octet 256 (one past the bound): no suppression" keep "$(kline 49150 443 140.82.122.0)" <<<"${H}140.82.121.256/32"
cidr_case "header octet 255 (the bound is valid): suppresses" drop "$(kline 49150 443 255.255.255.255)" <<<"${H}255.255.255.255/32"
cidr_case "header with trailing junk: no suppression" keep "$ONE" <<<"${H}140.82.121.34/32 trailing"
cidr_case "one good header plus one bad CIDR length: no suppression" keep "$ONE" <<<"${H}140.82.121.33/32"$'\n'"${H}140.82.121.34/99"
cidr_case "GOOD header covering the probed address, then a header with an unparsable IP: whole filter fails toward counting" keep "$ONE" <<<"${H}140.82.121.34/32"$'\n'"${H}garbage/32"
cidr_case "unparsable-IP header FIRST, then a good header covering the address: still counted" keep "$ONE" <<<"${H}garbage/32"$'\n'"${H}140.82.121.34/32"
cidr_case "GOOD header, then a header with octet 999: counted" keep "$ONE" <<<"${H}140.82.121.34/32"$'\n'"${H}999.1.1.1/32"
cidr_case "GOOD header covering the address plus a /33 header: whole file rejected, counted" keep "$ONE" <<<"${H}140.82.121.34/32"$'\n'"${H}140.82.121.40/33"
cidr_case "empty header value: no suppression" keep "$ONE" <<<"$H"
cidr_case "header with a different label: no suppression" keep "$ONE" <<<'# Excluded (Other): 140.82.121.34/32'
cidr_case "header missing the space after #: no suppression" keep "$ONE" <<<'#Excluded (GitHub Packages frontends): 140.82.121.34/32'
cidr_case "header /33 (longer than /32): no suppression" keep "$ONE" <<<"${H}140.82.121.34/33"
cidr_case "/28 header: an address inside the hole (.40) is dropped" drop "$(kline 49150 443 140.82.121.40)" <<<"${H}140.82.121.32/28"
cidr_case "/28 header: last address of the hole (.47) is dropped" drop "$(kline 49150 443 140.82.121.47)" <<<"${H}140.82.121.32/28"
cidr_case "/28 header: first address of the hole (.32) is dropped" drop "$(kline 49150 443 140.82.121.32)" <<<"${H}140.82.121.32/28"
cidr_case "/28 header: .31 below the hole stays counted" keep "$(kline 49150 443 140.82.121.31)" <<<"${H}140.82.121.32/28"
cidr_case "/28 header: .48 above the hole stays counted" keep "$(kline 49150 443 140.82.121.48)" <<<"${H}140.82.121.32/28"
cidr_case "DST octet 256 does not alias onto the next /24 (.121.256 != .122.0)" keep "$(kline 49150 443 140.82.121.256)" <<<"${H}140.82.122.0/32"
cidr_case "DST leading-zero octet is not read as decimal (.034 != .34)" keep "$(kline 49150 443 140.82.121.034)" <<<"${H}140.82.121.34/32"
CIDR_FILE="$WORK/does-not-exist.txt"
CIDR_ROWS=$((CIDR_ROWS + 1))
if [[ -n "$(run_filter "$ONE")" ]]; then got=keep; else got=drop; fi
check "cidr: CIDR file missing: no suppression" keep "$got"
CIDR_FILE="$CIDR_FIXTURE"
# control: the same single-line fixture, well-formed, MUST suppress (else the rows above prove nothing)
cidr_case "control: a well-formed single header DOES suppress the probe SYN" drop "$ONE" <<<"${H}140.82.121.34/32"
if [[ "$CIDR_ROWS" -lt 28 ]]; then
  printf '[FATAL] header-variant table: only %d rows ran, expected >= 28.\n' "$CIDR_ROWS" >&2
  exit 1
fi

echo "-- filter vs the COMMITTED generator output (real header format <-> resolver parser) --"
HDRS="$(sed -n 's/^# Excluded (GitHub Packages frontends): *//p' "$COMMITTED_CIDR")"
HDR_FIRST="$(sed -n 1p <<<"$HDRS")"
[[ -n "$HDR_FIRST" ]]; okc "committed CIDR file carries at least one '# Excluded (GitHub Packages frontends):' header" $?
FIRST_IP="${HDR_FIRST%/*}"
NEIGHBOUR="${FIRST_IP%.*}.7"
if grep -qF "${NEIGHBOUR}/" <<<"$HDRS"; then
  printf '[FATAL] parity setup: neighbour %s is itself an excluded header; pick another probe address.\n' "$NEIGHBOUR" >&2
  exit 1
fi
CIDR_FILE="$COMMITTED_CIDR"
if [[ -z "$(run_filter "$(kline 49150 443 "$FIRST_IP")")" ]]; then got=drop; else got=keep; fi
check "parity: SYN to the first committed '# Excluded' address ($FIRST_IP) from SPT 49150 is dropped" drop "$got"
if [[ -z "$(run_filter "$(kline 49150 443 "$NEIGHBOUR")")" ]]; then got=drop; else got=keep; fi
check "parity: SYN to a non-excluded neighbour ($NEIGHBOUR) is kept" keep "$got"
missed=""
while IFS= read -r h; do
  [[ -n "$h" ]] || continue
  if [[ -n "$(run_filter "$(kline 49150 443 "${h%/*}")")" ]]; then missed+="${h} "; fi
done <<<"$HDRS"
check "parity: every committed header's base address is suppressed (the whole header set parses)" "" "$missed"
CIDR_FILE="$CIDR_FIXTURE"

echo "-- filter failure fails toward counting (ghcr_probe_filter_or_keep) --"
printf '# Excluded (GitHub Packages frontends): 140.82.121.34/32\n' > "$CIDR_FIXTURE"
IN2="$ONE"$'\n'"$(kline 40000 443 8.8.8.8)"
: > "$LOGF"
check "control: with a healthy awk the probe SYN is removed, the rest kept" "$(kline 40000 443 8.8.8.8)" "$(printf '%s\n' "$IN2" | ghcr_probe_filter_or_keep)"
mkdir -p "$WORK/awkfail"
cat > "$WORK/awkfail/awk" <<'AWK_EOF'
#!/bin/sh
printf 'partial-output-that-must-not-leak\n'
exit 2
AWK_EOF
chmod +x "$WORK/awkfail/awk"
SAVED_PATH="$PATH"
PATH="$WORK/awkfail:$PATH"
fo_out="$(printf '%s\n' "$IN2" | ghcr_probe_filter_or_keep)"; fo_rc=$?
PATH="$SAVED_PATH"
check "failing awk (exit 2): every input line is KEPT, in order" "$IN2" "$fo_out"
check "failing awk: the wrapper itself returns 0" "0" "$fo_rc"
if grep -qF 'partial-output-that-must-not-leak' <<<"$fo_out"; then got=leaked; else got=clean; fi
check "failing awk: its partial output is not mixed into the result" "clean" "$got"
grep -q 'WARN: GHCR drop filter failed' "$LOGF"; okc "failing awk: a WARN is logged" $?
check "failing awk with ZERO input lines is still not a crash" "0" "$(PATH="$WORK/awkfail:$PATH"; printf '' | ghcr_probe_filter_or_keep >/dev/null; echo $?)"

echo "-- strict_ipv4_lines (container-supplied IPs, nft batch safety) --"
I_LABEL=(); I_IN=(); I_WANT=()
iadd() { I_LABEL+=("$1"); I_IN+=("$2"); I_WANT+=("$3"); }
iadd "ordinary address kept"                         "10.0.0.1"          "10.0.0.1"
iadd "octet 255 is the bound and is kept"            "255.255.255.255"   "255.255.255.255"
iadd "all-zero octets kept (single 0 is not a leading zero)" "0.0.0.0"   "0.0.0.0"
iadd "octet 256 is dropped"                          "1.2.3.256"         ""
iadd "first octet 256 is dropped"                    "256.1.1.1"         ""
iadd "999.1.1.1 is dropped (would abort nft -f)"     "999.1.1.1"         ""
iadd "leading-zero octet is dropped"                 "01.2.3.4"          ""
iadd "trailing leading-zero octet is dropped"        "1.2.3.04"          ""
iadd "three fields dropped"                          "1.2.3"             ""
iadd "five fields dropped"                           "1.2.3.4.5"         ""
iadd "shell metachar tail dropped"                   "1.2.3.4;rm"        ""
iadd "trailing space dropped"                        "1.2.3.4 "          ""
iadd "empty field dropped"                           "1..3.4"            ""
iadd "non-numeric dropped"                           "a.b.c.d"           ""
iadd "IPv6 dropped"                                  "::1"               ""
iadd "sign dropped"                                  "-1.2.3.4"          ""
iadd "mixed lines: only the bad one goes"            $'1.1.1.1\n999.1.1.1\n2.2.2.2' $'1.1.1.1\n2.2.2.2'
table_ipv4() { # table_ipv4 tag
  local i got
  IROWS=0
  for i in "${!I_LABEL[@]}"; do
    IROWS=$((IROWS + 1))
    got="$(printf '%s\n' "${I_IN[$i]}" | strict_ipv4_lines)"
    check "${1}strict_ipv4: ${I_LABEL[$i]}" "${I_WANT[$i]}" "$got"
  done
}
table_ipv4 ""
check "strict_ipv4 table instrument: every row ran" "${#I_LABEL[@]}" "$IROWS"
if [[ "$IROWS" -lt 17 ]]; then
  printf '[FATAL] strict_ipv4 table: only %d rows ran, expected >= 17.\n' "$IROWS" >&2
  exit 1
fi
for site in \
  'DESIRED_ALLOW="$(echo "$DESIRED_ALLOW" | strict_ipv4_lines | sort -u || true)"' \
  'RETAINED="$(echo "$RETAINED" | strict_ipv4_lines | sort -u || true)"' \
  'DNS_IPS="$(echo "$DNS_IPS" | strict_ipv4_lines | sort -u || true)"'; do
  grep -qF -- "$site" "$RESOLVER"; okc "wiring: ${site%%=*} is filtered through strict_ipv4_lines before the nft batch" $?
done
# by-name allow wins by order (plan Cut List): nothing here may subtract carved IPs from the by-name set
SPAN="$(sed -n '/^DESIRED_ALLOW=""$/,/^RETAINED="\$DESIRED_ALLOW"$/p' "$RESOLVER")"
[[ "$(wc -l <<<"$SPAN")" -ge 20 ]] && c=0 || c=1; okc "by-name span (DESIRED_ALLOW build .. RETAINED) located non-vacuously" "$c"
if grep -qiE 'carve|CIDR_FILE|Excluded' <<<"$SPAN"; then got=filtered; else got=untouched; fi
check "by-name allow set is not filtered against the carved prefixes (decision: by-name wins)" "untouched" "$got"

# --- mawk (the prod host is Ubuntu 24.04 / mawk): re-run the awk-heavy tables under it ------------
echo "-- mawk dialect --"
MAWK_BIN="${MAWK:-$(command -v mawk || true)}"
if [[ -n "$MAWK_BIN" && -x "$MAWK_BIN" ]]; then
  mkdir -p "$WORK/mawkshim"
  printf '#!/bin/sh\nexec "%s" "$@"\n' "$MAWK_BIN" > "$WORK/mawkshim/awk"
  chmod +x "$WORK/mawkshim/awk"
  CIDR_FILE="$CIDR_FIXTURE"
  printf '%s\n%s\n%s\n' "${H}140.82.121.33/32" "${H}140.82.121.34/32" "${H}192.30.255.164/31" > "$CIDR_FIXTURE"
  SAVED_PATH="$PATH"
  PATH="$WORK/mawkshim:$PATH"
  table_verdict "mawk "
  table_sampler "mawk "
  table_ipv4 "mawk "
  PATH="$SAVED_PATH"
  echo "  (mawk: $MAWK_BIN)"
else
  echo "  SKIP: mawk not installed; the sampler/strict/verdict tables ran under $(awk --version 2>&1 | head -1)"
fi

# --- 5. resolver wiring (static anchors for what the extraction cannot see) ---------------
echo "-- resolver wiring --"
ln_call="$(grep -n '^run_ghcr_probe ||' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_heal="$(grep -n 'enforcement rules missing' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_drops="$(grep -n 'ghcr_probe_filter_or_keep)"' "$RESOLVER" | head -1 | cut -d: -f1)"
ln_ok="$(grep -n '^sentry_checkin ok' "$RESOLVER" | head -1 | cut -d: -f1)"
[[ -n "$ln_call" && -n "$ln_heal" && -n "$ln_drops" && -n "$ln_ok" && "$ln_heal" -lt "$ln_call" && "$ln_call" -lt "$ln_drops" && "$ln_drops" -lt "$ln_ok" ]] && c=0 || c=1
okc "probe call sits after self-heal, before the drop sampler and sentry_checkin ok (heal=$ln_heal call=$ln_call drops=$ln_drops ok=$ln_ok)" "$c"
if grep -qE '\| *filter_ghcr_probe_drops *\|\| *true' "$RESOLVER"; then got=fail-open; else got=fail-toward-counting; fi
check "sampler call site does not swallow a filter failure with '|| true'" "fail-toward-counting" "$got"
n_lo="$(grep -cF 'GHCR_PROBE_PORT_LO' "$RESOLVER")"
[[ "$n_lo" -ge 3 ]]; okc "GHCR_PROBE_PORT_LO referenced at definition, curl flag and sampler ($n_lo)" $?
grep -qF -- '--local-port "${GHCR_PROBE_PORT_LO}-${GHCR_PROBE_PORT_HI}"' "$RESOLVER"; okc "curl --local-port derives from the constants" $?
grep -qF -- '-v plo="$GHCR_PROBE_PORT_LO" -v phi="$GHCR_PROBE_PORT_HI"' "$RESOLVER"; okc "sampler awk derives from the constants" $?
grep -qE "egress-\(blocked\|dns-exfil\): " "$RESOLVER"; okc "both drop prefixes (trailing space) still counted" $?

# --- end of run: accounting identity, then the outer floor ---------------------------------
echo
echo "ghcr-probe suite: $PASS passed, $FAIL failed ($CASES cases)"
# Every verdict is recorded through check()/okc(), each bumping CASES at the call site and then
# exactly one of PASS/FAIL. A branch that records nothing (or a stray direct pass/fail) breaks it.
if [[ $((PASS + FAIL)) -ne "$CASES" ]]; then
  printf '\n[FATAL] accounting identity: PASS(%d) + FAIL(%d) != CASES(%d). A call site recorded no verdict or more than one.\n' "$PASS" "$FAIL" "$CASES" >&2
  exit 1
fi
# Anti-vacuity floor (ADR-193): CI reads only the exit status, so a deleted row would vanish
# green. Reported directly with printf + exit, never through the pass()/fail() accounting it
# backstops. Ratchet when adding rows. (Counted without the optional mawk re-run.)
if [[ $((PASS + FAIL)) -lt 256 ]]; then
  printf '\n[FATAL] anti-vacuity floor: only %d verdict(s) recorded, expected >= 256. A row was deleted.\n' "$((PASS + FAIL))" >&2
  exit 1
fi
if [[ "$FAIL" -gt 0 ]]; then exit 1; fi
exit 0
