#!/usr/bin/env bash
# Behavioural table for the resolver's enforcement self-heal read (op=enforcement_missing, #9392).
#
# WHAT IT PROVES. `enforcement_probe` (extracted from cron-egress-resolve.sh, NO logic copy) reads the two
# enforcement rules with capture-then-match instead of `nft ... | grep -q` under `set -euo pipefail`, and is
# THREE-valued per rule: present / absent / unreadable. A failed read is never reported as an absent rule.
# Each case runs the extracted function in its own `bash -c 'set -euo pipefail'` subprocess so errexit semantics
# are the resolver's, against an `nft` shim on PATH whose output and exit status are per-scenario files.
#
# The ONE permitted logic copy is the OLD pipeline form in the SIGPIPE control row: it no longer exists in the
# resolver, so the control inlines it to prove the reproducer really yields rc 141 (a reproducer that does not
# reproduce makes the new-form row vacuous).
#
# Accounting: every verdict goes through check()/okc(), each bumping CASES at the call site. The suite end asserts
# PASS + FAIL == CASES; the helpers are negative-controlled first; mutation rows mutate a COPY of the extracted
# library and require a discriminating row to change.
# shellcheck disable=SC2016,SC2329  # payloads are intentionally single-quoted; cleanup is invoked via trap
set -uo pipefail

export TMPDIR="${TMPDIR:-/var/tmp}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLVER="${RESOLVER:-$SCRIPT_DIR/cron-egress-resolve.sh}"

PASS=0
FAIL=0
CASES=0
pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }
check() { # check "label" want got
  CASES=$((CASES + 1))
  if [[ "$2" == "$3" ]]; then pass "$1"; else fail "$1 (want='$2' got='$3')"; fi
}
okc() { # okc "label" <exit status of the test just run>  (0 = holds)
  CASES=$((CASES + 1))
  if [[ "$2" == "0" ]]; then pass "$1"; else fail "$1"; fi
}

assert_fixture_dir() {
  case "${1-}" in
    "") printf 'FATAL: fixture dir is EMPTY; git -C "" would operate on %s\n' "$PWD" >&2; exit 2 ;;
    */../*|*/..) printf 'FATAL: fixture dir %s contains ..; refusing\n' "$1" >&2; exit 2 ;;
    /proc/*|/sys/*|/dev/*) printf 'FATAL: fixture dir %s is a synthetic-fs path; refusing\n' "$1" >&2; exit 2 ;;
    /|//|/.) printf 'FATAL: fixture dir resolves to the filesystem root; refusing\n' >&2; exit 2 ;;
    /*) : ;;
    *)  printf 'FATAL: fixture dir %s is RELATIVE; refusing\n' "$1" >&2; exit 2 ;;
  esac
}

WORK="$(mktemp -d "${TMPDIR}/self-heal-test.XXXXXX")"
assert_fixture_dir "$WORK"
cleanup() { assert_fixture_dir "$WORK"; rm -rf "$WORK"; }
trap cleanup EXIT

[[ -f "$RESOLVER" ]] || { echo "FATAL: resolver not found: $RESOLVER" >&2; exit 2; }

# --- negative control of the verdict-owning helpers --------------------------------------------
nc_p=$PASS; nc_f=$FAIL; nc_c=$CASES
check "negative-control mismatch" "want-A" "got-B" > "$WORK/nc1.out"
okc "negative-control failing condition" 1 > "$WORK/nc2.out"
check "negative-control match" "same" "same" > "$WORK/nc3.out"
okc "negative-control holding condition" 0 > "$WORK/nc4.out"
if (( FAIL - nc_f != 2 || PASS - nc_p != 2 || CASES - nc_c != 4 )) \
  || ! grep -q '^  FAIL: negative-control mismatch' "$WORK/nc1.out" \
  || ! grep -q '^  PASS: negative-control holding condition' "$WORK/nc4.out"; then
  printf '[FATAL] negative control: check()/okc() did not record the expected PASS/FAIL.\n' >&2
  exit 1
fi
PASS=$nc_p; FAIL=$nc_f; CASES=$nc_c

# --- extraction (no logic copy) ----------------------------------------------------------------
extract_fn() { # extract_fn name  (definition line `name() {` through the closing `}` at col 0)
  awk -v n="$1" '
    $0 == n "() {" { p = 1 }
    p { print }
    p && $0 == "}" { exit }' "$RESOLVER"
}
LIB="$WORK/lib.sh"
LIB_FNS="enforcement_probe enforcement_extra"
EXTRACT_ROWS=0
{
  echo '# generated by cron-egress-self-heal.test.sh from cron-egress-resolve.sh'
  for fn in $LIB_FNS; do extract_fn "$fn"; done
} > "$LIB"
echo "-- extraction (non-vacuous) --"
for fn in $LIB_FNS; do
  EXTRACT_ROWS=$((EXTRACT_ROWS + 1))
  n="$(extract_fn "$fn" | wc -l)"
  [[ "$n" -ge 15 ]]; okc "extracted $fn ($n lines; expected >= 15)" $?
done
bash -n "$LIB"; okc "extracted library parses" $?
if [[ "$EXTRACT_ROWS" -lt 2 ]]; then
  printf '[FATAL] extraction table ran %d rows, expected >= 2.\n' "$EXTRACT_ROWS" >&2
  exit 1
fi

# --- shims -------------------------------------------------------------------------------------
SHIM="$WORK/shim"
assert_fixture_dir "$WORK"
mkdir -p "$SHIM"
cat > "$SHIM/nft" <<'SHIM_EOF'
#!/usr/bin/env bash
chain="${*: -1}"
case "$chain" in DOCKER-USER) k=jump ;; SOLEUR-EGRESS) k=chain ;; *) echo "nft shim: unhandled: $*" >&2; exit 99 ;; esac
n=$(( $(cat "$SC/$k.n" 2>/dev/null || echo 0) + 1 )); echo "$n" > "$SC/$k.n"
ff="$(cat "$SC/$k.failfirst" 2>/dev/null || echo 0)"
if (( n <= ff )); then echo "netlink: Resource busy" >&2; exit 1; fi
if [[ -f "$SC/$k.sigpipe" ]]; then
  cat "$SC/$k.out"; sleep 0.3; head -c 204800 /dev/zero | tr '\0' 'x'; echo
  exit "$(cat "$SC/$k.rc" 2>/dev/null || echo 0)"
fi
[[ -f "$SC/$k.out" ]] && cat "$SC/$k.out"
exit "$(cat "$SC/$k.rc" 2>/dev/null || echo 0)"
SHIM_EOF
cat > "$SHIM/systemctl" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$SC/systemctl.calls"
[[ -f "$SC/systemctl.fail" ]] && exit 1
echo "Fri 2026-10-02 10:00:00 UTC"
SHIM_EOF
cat > "$SHIM/timeout" <<'SHIM_EOF'
#!/usr/bin/env bash
echo "$*" >> "$SC/timeout.calls"
shift
exec "$@"
SHIM_EOF
chmod +x "$SHIM/nft" "$SHIM/systemctl" "$SHIM/timeout"

JUMP_PRESENT='table ip filter {
	chain DOCKER-USER {
		iifname "docker0" counter packets 1 bytes 60 jump SOLEUR-EGRESS comment "soleur-egress: jump"
	}
}'
JUMP_ABSENT='table ip filter {
	chain DOCKER-USER {
		counter packets 0 bytes 0 return
	}
}'
CHAIN_FULL='table ip filter {
	chain SOLEUR-EGRESS {
		ip daddr @soleur_egress_allow accept comment "soleur-egress: allowlist"
		limit rate 10/minute burst 50 packets log prefix "egress-blocked: " level notice comment "soleur-egress: default drop log"
		counter packets 3 bytes 180 drop comment "soleur-egress: default drop"
	}
}'
CHAIN_NODROP='table ip filter {
	chain SOLEUR-EGRESS {
		ip daddr @soleur_egress_allow accept comment "soleur-egress: allowlist"
		limit rate 10/minute burst 50 packets log prefix "egress-blocked: " level notice comment "soleur-egress: default drop log"
	}
}'
CHAIN_EMPTY='table ip filter {
	chain SOLEUR-EGRESS {
	}
}'
CHAIN_NOISY="$(printf 'table ip filter {\n\tchain SOLEUR-EGRESS {\n'; for i in $(seq 1 400); do printf '\t\tip daddr 10.%d.%d.1 tcp dport 443 accept comment "soleur-egress: noise"\n' "$((i / 250))" "$((i % 250))"; done; printf '\t\tlimit rate 10/minute burst 50 packets log prefix "egress-blocked: " level notice comment "soleur-egress: default drop log"\n\t\tcounter packets 3 bytes 180 drop comment "soleur-egress: default drop"\n\t}\n}')"

# scenario <name> <jump-out> <chain-out> <failfirst-jump> <failfirst-chain> <rc-jump> <rc-chain> [sigpipe-jump]
scenario() {
  local d="$WORK/sc.$1"
  assert_fixture_dir "$WORK"
  rm -rf "$d"; mkdir -p "$d"
  printf '%s\n' "$2" > "$d/jump.out"
  printf '%s\n' "$3" > "$d/chain.out"
  echo "$4" > "$d/jump.failfirst"; echo "$5" > "$d/chain.failfirst"
  echo "$6" > "$d/jump.rc"; echo "$7" > "$d/chain.rc"
  [[ -n "${8:-}" ]] && : > "$d/jump.sigpipe"
  echo "$d"
}
# probe_out <lib> <scenario-dir>  -> "J|D|L|rcj|rcd|read_failed|read_retried|heal"; the subprocess rc lands in $WORK/probe.rc
probe_out() {
  local out
  out="$(env -i PATH="$SHIM:/usr/bin:/bin" SC="$2" ENF_RETRY_SLEEP=0 LIB="$1" bash -c '
    set -euo pipefail
    source "$LIB"
    enforcement_probe
    printf "%s|%s|%s|%s|%s|%s|%s|%s\n" "$ENF_JUMP" "$ENF_DROP" "$ENF_LOG" "$ENF_RC_JUMP" "$ENF_RC_DROP" "$ENF_READ_FAILED" "$ENF_READ_RETRIED" "$ENF_HEAL"
  ' 2>"$WORK/probe.err")" && echo 0 > "$WORK/probe.rc" || echo $? > "$WORK/probe.rc"
  printf '%s' "$out"
}

echo "-- three-valued read table (each case: its own set -euo pipefail subprocess) --"
TABLE_ROWS=0
row() { # row "label" want jump chain ffj ffc rcj rcc [sigpipe]
  TABLE_ROWS=$((TABLE_ROWS + 1))
  local d got
  d="$(scenario "r$TABLE_ROWS" "$3" "$4" "$5" "$6" "$7" "$8" "${9:-}")"
  got="$(probe_out "$LIB" "$d")"
  check "$1" "$2" "$got"
  check "$1 (subprocess survives errexit)" "0" "$(cat "$WORK/probe.rc")"
}
#   label                                                   want J|D|L|rcj|rcd|failed|retried|heal       jump         chain        ffj ffc rcj rcc
row "both rules present: no heal"                           "present|present|present|0|0|false|false|false" "$JUMP_PRESENT" "$CHAIN_FULL"   0 0 0 0
row "jump absent: heal"                                     "absent|present|present|0|0|false|false|true"   "$JUMP_ABSENT"  "$CHAIN_FULL"   0 0 0 0
row "drop absent, LOG rule still there: heal (old check read this as healthy)" \
                                                            "present|absent|present|0|0|false|false|true"   "$JUMP_PRESENT" "$CHAIN_NODROP"  0 0 0 0
row "both absent, every status 0 (a real external flush)"   "absent|absent|absent|0|0|false|false|true"    "$JUMP_ABSENT"  "$CHAIN_EMPTY"   0 0 0 0
row "noisy 400-rule chain around the needle: present"       "present|present|present|0|0|false|false|false" "$JUMP_PRESENT" "$CHAIN_NOISY"   0 0 0 0
row "nft fails persistently (rc 1, empty): unreadable, never absent" \
                                                            "unreadable|unreadable|unreadable|1|1|true|true|true" "" ""                       9 9 1 1
row "jump read fails once then succeeds: retried, no heal"  "present|present|present|0|0|false|true|false"  "$JUMP_PRESENT" "$CHAIN_FULL"   1 0 0 0
row "chain read fails once then succeeds: retried, no heal" "present|present|present|0|0|false|true|false"  "$JUMP_PRESENT" "$CHAIN_FULL"   0 1 0 0
row "read fails once then succeeds and the rule IS absent"  "absent|present|present|0|0|false|true|true"    "$JUMP_ABSENT"  "$CHAIN_FULL"   1 0 0 0
row "nonzero status with a matching partial listing is still unreadable" \
                                                            "unreadable|present|present|1|0|true|true|true" "$JUMP_PRESENT" "$CHAIN_FULL"   0 0 1 0
row "SIGPIPE reproducer on the jump listing: new form reads present" \
                                                            "present|present|present|0|0|false|false|false" "$JUMP_PRESENT" "$CHAIN_FULL"   0 0 0 0 sigpipe

# Control: the reproducer really reproduces. The OLD form on the SAME shim reads rc 141 under pipefail.
d="$(scenario control "$JUMP_PRESENT" "$CHAIN_FULL" 0 0 0 0 sigpipe)"
old_rc=0
env -i PATH="$SHIM:/usr/bin:/bin" SC="$d" bash -c 'set -o pipefail; nft list chain ip filter DOCKER-USER | grep -q "jump SOLEUR-EGRESS"' || old_rc=$?
check "control: the OLD 'nft | grep -q' form on the reproducer shim returns 141 (SIGPIPE read as missing)" "141" "$old_rc"

# --- the extra payload -----------------------------------------------------------------------
echo "-- enforcement_extra --"
extra_json() { # extra_json <scenario-dir> [fault]  -> compact JSON on stdout
  local d="$1" fault="${2:-}"
  rm -f "$d/systemctl.fail" "$d/systemctl.calls" "$d/timeout.calls"
  [[ "$fault" == "systemctl-fail" ]] && : > "$d/systemctl.fail"
  local shim="$SHIM"
  if [[ "$fault" == "jq-fail" ]]; then
    shim="$WORK/shim-jq"; mkdir -p "$shim"; cp "$SHIM"/* "$shim"/
    printf '#!/usr/bin/env bash\nexit 1\n' > "$shim/jq"; chmod +x "$shim/jq"
  fi
  env -i PATH="$shim:/usr/bin:/bin" SC="$d" ENF_RETRY_SLEEP=0 LIB="$LIB" bash -c '
    set -euo pipefail
    source "$LIB"
    enforcement_probe
    enforcement_extra
  ' 2>/dev/null
}
d="$(scenario extra "$JUMP_ABSENT" "$CHAIN_FULL" 0 0 0 0)"
j="$(extra_json "$d")"
keys="$(printf '%s' "$j" | python3 -c 'import json,sys; print(",".join(sorted(json.load(sys.stdin))))' 2>/dev/null || echo INVALID)"
check "extra: exact key set" "docker_since,drop_present,host,jump_present,loader_since,log_present,rc_drop,rc_jump,read_failed,read_retried,remediation" "$keys"
typ="$(printf '%s' "$j" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(type(d["read_failed"]).__name__, type(d["read_retried"]).__name__, type(d["rc_jump"]).__name__, d["jump_present"], d["drop_present"])' 2>/dev/null || echo INVALID)"
check "extra: booleans and ints are typed, rule states flow from the probe" "bool bool int absent present" "$typ"
grep -q 'timeout 2 systemctl show' "$d/timeout.calls" 2>/dev/null || grep -q '^2 systemctl' "$d/timeout.calls" 2>/dev/null
okc "extra: both systemctl reads are wrapped in timeout 2" $?
check "extra: two systemctl reads" "2" "$(wc -l < "$d/systemctl.calls" 2>/dev/null | tr -d ' ')"
j="$(extra_json "$d" systemctl-fail)"
since="$(printf '%s' "$j" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["docker_since"], d["loader_since"])' 2>/dev/null || echo INVALID)"
check "extra: a failing systemctl read degrades to unknown, never aborts" "unknown unknown" "$since"
j="$(extra_json "$d" jq-fail)"
rem="$(printf '%s' "$j" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(sorted(d))' 2>/dev/null || echo INVALID)"
check "extra: a jq failure falls back to the minimal remediation object (valid JSON, post never aborts)" "['remediation']" "$rem"

# --- mutation rows: mutate a COPY of the extracted library; a discriminating row must change --------------------
echo "-- mutation rows --"
MUT_ROWS=0
mutate() { # mutate "label" <sed-expr> <scenario-name> <want-for-pristine>
  MUT_ROWS=$((MUT_ROWS + 1))
  local mlib="$WORK/mut.$MUT_ROWS.sh" dd got
  cp "$LIB" "$mlib"
  sed -i "$2" "$mlib"
  if cmp -s "$LIB" "$mlib"; then printf '[FATAL] mutation row %d did not land: %s\n' "$MUT_ROWS" "$1" >&2; exit 2; fi
  bash -n "$mlib" 2>/dev/null || { printf '[FATAL] mutation row %d does not parse: %s\n' "$MUT_ROWS" "$1" >&2; exit 2; }
  dd="$(scenario "m$MUT_ROWS" "$JUMP_PRESENT" "$CHAIN_NODROP" 0 0 0 0)"
  got="$(probe_out "$mlib" "$dd")"
  [[ "$got" != "present|absent|present|0|0|false|false|true" ]]; okc "mutant caught: $1" $?
}
mutate "drop matched on the log prefix instead of the drop rule" 's#comment "soleur-egress: default drop"#egress-blocked#'
MUT_ROWS=$((MUT_ROWS + 0))
retry_d="$(scenario mretry "$JUMP_PRESENT" "$CHAIN_FULL" 1 0 0 0)"
MUT_ROWS=$((MUT_ROWS + 1))
mlib="$WORK/mut.retry.sh"; cp "$LIB" "$mlib"; sed -i 's/for attempt in 1 2; do/for attempt in 1; do/' "$mlib"
if cmp -s "$LIB" "$mlib"; then printf '[FATAL] retry mutation did not land\n' >&2; exit 2; fi
got="$(probe_out "$mlib" "$retry_d")"
[[ "$got" != "present|present|present|0|0|false|true|false" ]]; okc "mutant caught: the retry is removed (a one-off read failure is no longer absorbed)" $?
MUT_ROWS=$((MUT_ROWS + 1))
mlib="$WORK/mut.sig.sh"; cp "$LIB" "$mlib"
sed -i 's/out_jump="$(nft list chain ip filter DOCKER-USER 2>\/dev\/null)" || ENF_RC_JUMP=$?/out_jump="$(nft list chain ip filter DOCKER-USER 2>\/dev\/null | grep -m1 "jump SOLEUR-EGRESS")" || ENF_RC_JUMP=$?/' "$mlib"
if cmp -s "$LIB" "$mlib"; then printf '[FATAL] pipeline mutation did not land\n' >&2; exit 2; fi
bash -n "$mlib" || { printf '[FATAL] pipeline mutation does not parse\n' >&2; exit 2; }
sd="$(scenario msig "$JUMP_PRESENT" "$CHAIN_FULL" 0 0 0 0 sigpipe)"
got="$(probe_out "$mlib" "$sd")"
[[ "$got" != "present|present|present|0|0|false|false|false" ]]; okc "mutant caught: the capture is re-introduced as an early-exiting pipeline (SIGPIPE row changes)" $?
if [[ "$MUT_ROWS" -lt 3 ]]; then printf '[FATAL] mutation rows: only %d ran, expected >= 3.\n' "$MUT_ROWS" >&2; exit 1; fi

# --- the call site in the resolver (what no shimmed row can observe) ---------------------------------------------
echo "-- resolver call site --"
HEAL_BLOCK="$(awk '/^# --- Self-heal: assert the enforcement rules are still live/{p=1} /^# --- GHCR deny probe/{p=0} p' "$RESOLVER" | grep -vE '^[[:space:]]*#')"
check "call site: the self-heal block has no 'nft ... | grep' pipeline left" "0" "$(printf '%s\n' "$HEAL_BLOCK" | grep -cE 'nft .*\|[[:space:]]*grep')"
check "call site: enforcement_probe is a BARE statement (errexit-visible, not an if/|| operand)" "1" "$(printf '%s\n' "$HEAL_BLOCK" | grep -cE '^[[:space:]]+enforcement_probe$')"
post_line="$(printf '%s\n' "$HEAL_BLOCK" | grep -nE 'sentry_event[[:space:]]*\\?$|sentry_event "' | head -1 | cut -d: -f1)"
loader_line="$(printf '%s\n' "$HEAL_BLOCK" | grep -nF '"$LOADER" || fail' | head -1 | cut -d: -f1)"
[[ -n "$post_line" && -n "$loader_line" && "$post_line" -lt "$loader_line" ]]; okc "call site: the event is posted BEFORE the loader re-run (a failed self-heal still reports)" $?
grep -qE '^[[:space:]]+"cron-egress-firewall: enforcement rules were MISSING at tick \(jump/drop absent\) — loader re-run triggered" \\$' "$RESOLVER"; okc "call site: the event message is byte-identical (same Sentry group)" $?
grep -qE '^[[:space:]]+"enforcement_missing" \\$' "$RESOLVER"; okc "call site: op literal stays top-level (the op-contract parser reads it)" $?

echo
echo "self-heal suite: $PASS passed, $FAIL failed ($CASES cases)"
if [[ $((PASS + FAIL)) -ne "$CASES" ]]; then
  printf '\n[FATAL] accounting identity: PASS(%d) + FAIL(%d) != CASES(%d).\n' "$PASS" "$FAIL" "$CASES" >&2
  exit 1
fi
if [[ $((PASS + FAIL)) -lt 40 ]]; then
  printf '\n[FATAL] anti-vacuity floor: only %d verdict(s) recorded, expected >= 40. A row was deleted.\n' "$((PASS + FAIL))" >&2
  exit 1
fi
if [[ "$FAIL" -gt 0 ]]; then exit 1; fi
exit 0
