/**
 * Layer-1 constraint gate — client -> server-secret import boundary.
 *
 * GENERATED by `plugins/soleur/skills/constraint-scaffold` (ADR-071, Option D).
 * The agent — never the founder — owns this file. Recovery is automatic: when
 * this gate trips on a PR, the two-stage auto-recovery dispatcher
 * (fix-constraints-stage-a/b, ADR-074) fixes the offending import and opens a
 * follow-up PR if it is auto-fixable; a real leak the agent cannot fix is
 * surfaced for a maintainer (who re-runs the constraint-scaffold skill locally,
 * or runs `--refresh-baseline`). The gate stays informational/non-blocking. Do NOT hand-edit.
 *
 * Mechanism: dependency-cruiser matches modules by PATH and cannot see the
 * `"use client"` directive, so this config is executable CommonJS that computes
 * the client-module `from` set at require-time by scanning `app/**` + `components/**`
 * for a leading `"use client"` directive. The set is RECOMPUTED every run and
 * NEVER committed as a static list — a stale list would be blind to a newly added
 * client file (the exact leak this gate exists to catch). An empty from-set while
 * `"use client"` files exist is a HARD ERROR, not a silently-disabled rule.
 *
 * Two rules (ADR-071 + the 2026-07-01 #5777 amendment):
 *   1. `no-client-to-server-secret` — DIRECT edges: a "use client" module
 *      value-imports `server/**` directly.
 *   2. `no-client-to-server-secret-transitive` — TRANSITIVE reach: a "use client"
 *      module reaches `server/**` through a chain of value imports (e.g. a
 *      non-client `lib/` helper that value-imports a server secret). This is the
 *      dependency hop the direct rule is blind to (#5777, NG5 of #5765).
 *
 * `options.tsPreCompilationDeps` is `false` (v1 set it `true`): dependency-cruiser
 * v16 `reachable` rules are schema-locked to `{path,pathNot,reachable}` and CANNOT
 * filter `dependencyTypesNot` per-rule, so the ONLY way to keep the transitive rule
 * from following a build-time-erased `import type` hop is to elide type-only edges
 * from the graph GLOBALLY. With type-only edges gone, the direct rule no longer
 * needs `dependencyTypesNot:["type-only"]` (its violation set is byte-identical
 * before/after the flip — proven at build time, locked by boundary.test.sh). Both
 * rules therefore ignore type-only imports for free. See ADR-071 §Amendment 2026-07-01.
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const CLIENT_DIRS = ["app", "components"];
const SOURCE_EXT = /\.(?:tsx?|jsx?|mjs|cjs)$/;
// The secret set: the whole server tree is server-only (reads server-only secrets).
const SECRET_PATH = "^server/";
// Value-safe server modules the TRANSITIVE rule excludes via `to.pathNot`. These
// carry NO secret values — they are code-static registries / editorial metadata a
// client may legitimately reach through a helper:
//   server/domain-leaders.ts            — static leader array, no secrets
//   server/providers.ts                 — env-var NAMES as metadata (never reads process.env)
//   server/team-names-validation.ts     — pure validation, no secrets
//   server/scope-grants/action-class-map.ts — code-static action-class registry (no imports, no env)
// COUPLING: this is the SAME "known value-safe server modules" set the DIRECT rule
// grandfathers via its baseline (.dependency-cruiser-known-violations.json). Two
// hand-maintained copies that can drift — a future editor MUST update both, and any
// module added here MUST be security-reviewed value-safe (no process.env value read,
// no secret import) and covered by the boundary.test.sh drift guard (D4). Excluding a
// module here does NOT blind a client to OTHER server modules (it is a `to` filter,
// never a `from` filter). See ADR-071 §Amendment 2026-07-01 and the D3c drift guard.
// SOLEUR-DEBT: pathNot allowlist is a hand-maintained fail-open backstopped only by the
// D4 content-invariant drift guard; relocate these 4 modules OUT of server/** so the
// exclusion is enforced by LOCATION (deletes pathNot + the guard). Upgrade trigger: next
// time one of the 4 is edited to add a runtime value, OR a 5th value-safe module would
// need adding here. Tracked: #5850.
// End-anchored to the exact module file (`\.<ext>$`) — a bare trailing `\.` would
// prefix-match dot-suffixed SIBLINGS (`server/providers.server.ts`,
// `server/domain-leaders.data.ts`) and silently exempt them from the transitive
// rule too; those are natural Next.js names and must stay WATCHED.
const VALUE_SAFE_PATH =
  "^server/(domain-leaders|providers|team-names-validation|scope-grants/action-class-map)\\.(?:[cm]?[jt]sx?)$";

function walk(dir, acc) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    if (e && e.code === "ENOENT") return acc; // dir absent is fine; cwd check below
    throw e;
  }
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".next") continue;
    const full = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) {
      // A symlinked source file is neither isFile() nor isDirectory() as a
      // Dirent, so the branches below would silently DROP it from the scan —
      // excluding it from the client from-set = fail open (a symlinked client
      // module could leak unflagged). Resolve the link; hard-error on a
      // symlinked source file rather than skipping it.
      let target;
      try {
        target = fs.statSync(full); // follows the symlink
      } catch (e) {
        continue; // broken/dangling link: not a readable source file
      }
      if (target.isFile() && SOURCE_EXT.test(entry.name)) {
        throw new Error(
          "constraint-scaffold: symlinked source file " +
            full +
            " — refusing to silently skip it (would fail the import-boundary scan open)",
        );
      }
      continue; // symlinked directory / non-source: not scanned (out of v1 scope)
    }
    if (entry.isDirectory()) {
      walk(full, acc);
    } else if (entry.isFile() && SOURCE_EXT.test(entry.name)) {
      acc.push(full);
    }
  }
  return acc;
}

function isUseClient(file) {
  let rest = fs.readFileSync(file, "utf8");
  // Skip leading blank lines and leading comments before the directive. A
  // license/eslint banner (`// ...` line-comment or `/* ... */` block-comment)
  // before `"use client"` is valid Next.js; treating such a file as non-client
  // would leave its server value-imports UNFLAGGED (a silent leak).
  for (;;) {
    rest = rest.replace(/^\s+/, "");
    if (rest.startsWith("//")) {
      const nl = rest.indexOf("\n");
      if (nl === -1) return false;
      rest = rest.slice(nl + 1);
      continue;
    }
    if (rest.startsWith("/*")) {
      const end = rest.indexOf("*/");
      if (end === -1) return false;
      rest = rest.slice(end + 2);
      continue;
    }
    break;
  }
  // The directive, allowing a trailing `;` and/or a trailing line/block comment
  // on the same line: `"use client"; // hydration`.
  const firstLine = rest.split(/\r?\n/, 1)[0];
  return /^(['"])use client\1\s*;?\s*(?:\/\/.*|\/\*.*)?$/.test(firstLine);
}

function reEscape(s) {
  // Escape every regex metacharacter — route groups like `app/(dashboard)/`
  // carry `(` / `)` and filenames carry `.`.
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function computeClientFromSet() {
  // A wrong cwd (config required from outside the target root) would make the
  // whole scan blind. Require at least one client dir to exist — else hard fail.
  const presentDirs = CLIENT_DIRS.filter((d) => fs.existsSync(path.join(ROOT, d)));
  if (presentDirs.length === 0) {
    throw new Error(
      "constraint-scaffold: neither app/ nor components/ found under " +
        ROOT +
        " — gate cannot scan client modules (wrong cwd or empty input)",
    );
  }
  const files = [];
  for (const d of presentDirs) walk(path.join(ROOT, d), files);
  const clientFiles = files.filter(isUseClient);
  let fromSet = clientFiles.map((f) => {
    const rel = path.relative(ROOT, f).split(path.sep).join("/");
    return "^" + reEscape(rel) + "$";
  });
  // Test seam: simulate a scan-vs-map divergence (found client files but the
  // mapped set came back empty) to prove the guard below is live. Test-only.
  if (process.env.CONSTRAINT_SCAFFOLD_TEST_FORCE_EMPTY === "1") fromSet = [];
  if (clientFiles.length > 0 && fromSet.length === 0) {
    throw new Error(
      "constraint-scaffold: client-module from-set is empty while " +
        clientFiles.length +
        ' "use client" files exist — refusing to emit a silently-disabled rule',
    );
  }
  // No client modules at all: match nothing (a regex that never matches) rather
  // than `[]`, which dependency-cruiser would treat as match-anything.
  if (fromSet.length === 0) fromSet = ["(?!)"];
  return fromSet;
}

// Compute the client-module from-set ONCE and share it across both rules so the
// fail-closed guards inside computeClientFromSet (empty-from-set hard error, the
// `(?!)` never-match sentinel, the "neither app/ nor components/" hard error, the
// symlinked-source hard error) apply to BOTH rules identically.
const clientFrom = computeClientFromSet();

module.exports = {
  forbidden: [
    {
      name: "no-client-to-server-secret",
      severity: "error",
      comment:
        'A "use client" module must not take a value (non-type-only) import on the ' +
        "server-only tree (server/**) — that ships a server secret into the browser " +
        "bundle. Use `import type` for types, or move the value behind a server boundary.",
      from: { path: clientFrom },
      // No `dependencyTypesNot:["type-only"]` — type-only edges are elided globally
      // by `tsPreCompilationDeps:false` (see header), so this rule flags exactly the
      // value edges it flagged under v1's `true` + `dependencyTypesNot` (proven
      // byte-identical; a flip regression could only SHRINK the value-edge set, so
      // boundary.test.sh floors the direct baseline at >=10).
      to: { path: SECRET_PATH },
    },
    {
      name: "no-client-to-server-secret-transitive",
      severity: "error",
      comment:
        'A "use client" module must not TRANSITIVELY reach the server-only tree ' +
        "(server/**) through a chain of value imports — a non-client helper that " +
        "value-imports a server secret ships that secret into the browser bundle. " +
        "Break the chain, or use `import type`. (Type-only hops are elided globally, " +
        "so a client -> `import type` helper -> server chain does NOT flag.)",
      from: { path: clientFrom },
      // `pathNot` excludes the known value-safe server modules (VALUE_SAFE_PATH) so
      // the reachable baseline stays EMPTY: dependency-cruiser softens `reachability`
      // violations per-ORIGIN (`from`+rule name only, ignoring `to`/`via`), so
      // baselining even one value-safe transitive path would blind that client to
      // EVERY future transitive secret. We never baseline a reachability entry — we
      // exclude value-safe targets here and FIX real leaks (D2/D3, ADR-071 amendment).
      to: { path: SECRET_PATH, pathNot: VALUE_SAFE_PATH, reachable: true },
    },
  ],
  options: {
    tsConfig: { fileName: "tsconfig.json" },
    // false (v1: true) — elide type-only edges globally so the reachable rule cannot
    // follow a build-time-erased `import type` hop (its `to` is schema-locked and
    // cannot filter dependency-types per-rule). The direct rule's output is unchanged.
    tsPreCompilationDeps: false,
    doNotFollow: { path: "node_modules" },
  },
};
