#!/usr/bin/env bash
# Shared constraint-gates runner — owns the single pinned dependency-cruiser
# invocation. CI and (future) pre-commit both exec THIS file, so the gate's
# command line lives in exactly one place.
#
# GENERATED by `plugins/soleur/skills/constraint-scaffold` (ADR-071). The agent
# — never the founder — owns this file. To recover a tripped gate, re-run the
# constraint-scaffold skill (the agent fixes the import or runs
# `--refresh-baseline`). The `/soleur fix constraints` comment-dispatcher is
# PLANNED (#5791), not yet wired; until it lands the agent owns recovery
# directly and the gate stays informational/non-blocking. Do NOT hand-edit.
#
# Exit-reason matrix (every non-zero exit is a hard FAIL — fail-closed):
#   0  — clean: no new client->server-secret value-import violations beyond the
#        committed baseline.
#   1  — FAIL. Either (a) real boundary violation(s), or (b) a dependency-cruiser
#        config/binary error. We discriminate the two only to print the right
#        recovery annotation; both block the merge.
#
# Note on dependency-cruiser exit codes (empirically verified, v16): depcruise
# exits with the *error count* on violations (e.g. rc=10 for ten) and rc=1 on a
# config/parse/load error. So a non-zero rc alone cannot tell "N violations"
# from "config error" — we discriminate on whether the report contains the
# "dependency violations" summary line. ANY non-zero rc fails the gate closed.
set -euo pipefail

# App root: this script lives in <app>/scripts/constraint-gates.sh. The
# CONSTRAINT_GATES_DIR override points the runner at a synthesized fixture app
# root for the skill self-tests; in CI it is unset and resolves to <app>.
APP_DIR="${CONSTRAINT_GATES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$APP_DIR"

DEPCRUISE="./node_modules/.bin/depcruise"
CONFIG=".dependency-cruiser.cjs"
BASELINE=".dependency-cruiser-known-violations.json"

if [[ ! -x "$DEPCRUISE" ]]; then
  echo "::error::constraint-gates: dependency-cruiser not found at ${APP_DIR}/${DEPCRUISE} — run 'bun install' (or 'npm ci'). To recover, re-run the constraint-scaffold skill (the agent fixes the import or runs --refresh-baseline); the '/soleur fix constraints' auto-dispatcher is planned (#5791), not yet wired." >&2
  exit 1
fi
if [[ ! -f "$BASELINE" ]]; then
  echo "::error::constraint-gates: baseline ${APP_DIR}/${BASELINE} missing — regenerate with constraint-scaffold.sh. To recover, re-run the constraint-scaffold skill (the agent fixes the import or runs --refresh-baseline); the '/soleur fix constraints' auto-dispatcher is planned (#5791), not yet wired." >&2
  exit 1
fi

set +e
OUT="$("$DEPCRUISE" --config "$CONFIG" --ignore-known "$BASELINE" --output-type err app components server 2>&1)"
RC=$?
set -e
printf '%s\n' "$OUT"

if [[ "$RC" -eq 0 ]]; then
  # Baseline-clean. Real-tree alias-resolution self-check (fail-closed): the
  # whole gate is BLIND if `@/server` imports stop resolving (a tsconfig
  # baseUrl/paths regression) — an unresolved edge never matches the
  # `to: ^server/` rule, so a real client->server-secret leak would read green.
  # The synthetic boundary.test.sh fixture asserts couldNotResolve==0, but a
  # change to the REAL app's tsconfig is invisible there. Assert it here on the
  # real tree: 0 couldNotResolve edges whose target is the server tree.
  set +e
  JSON_OUT="$("$DEPCRUISE" --config "$CONFIG" --output-type json app components server 2>/dev/null)"
  set -e
  UNRESOLVED="$(
    printf '%s' "$JSON_OUT" | node -e '
      let s = ""; process.stdin.on("data", (d) => (s += d)); process.stdin.on("end", () => {
        let n = 0;
        try {
          const j = JSON.parse(s);
          for (const m of j.modules || [])
            for (const dep of m.dependencies || [])
              if (dep.couldNotResolve &&
                  /(?:^|[@/])server\//.test((dep.module || "") + "\n" + (dep.resolved || ""))) n++;
        } catch (e) { n = -1; }
        process.stdout.write(String(n));
      });
    ' 2>/dev/null
  )"
  if [[ "$UNRESOLVED" != "0" ]]; then
    echo "::error::constraint-gates: ${UNRESOLVED} unresolved (couldNotResolve) import(s) target the server tree on the real app — @/* alias resolution is broken (tsconfig baseUrl/paths/@ regression?), so the import-boundary gate is BLIND to client->server-secret leaks. Failing closed. To recover, re-run the constraint-scaffold skill (the agent fixes the tsconfig/import); the '/soleur fix constraints' auto-dispatcher is planned (#5791), not yet wired." >&2
    exit 1
  fi
  exit 0
fi

if printf '%s' "$OUT" | grep -q 'dependency violations'; then
  echo "::error::constraint-gates: client->server-secret import-boundary violation(s) detected — a \"use client\" module value-imports the server-only tree (server/**), which would ship a server secret into the browser bundle. To recover, re-run the constraint-scaffold skill (the agent fixes the import or runs --refresh-baseline); the '/soleur fix constraints' auto-dispatcher is planned (#5791), not yet wired." >&2
else
  echo "::error::constraint-gates: dependency-cruiser failed to run (config/binary error, rc=${RC}) — gate fails closed. To recover, re-run the constraint-scaffold skill (the agent fixes the import or runs --refresh-baseline); the '/soleur fix constraints' auto-dispatcher is planned (#5791), not yet wired." >&2
fi
exit 1
