name: Bug Report
description: Report a bug in the Soleur plugin
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `/soleur:...`
        2. ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: "Run `claude plugin list` to check"
      placeholder: "2.1.0"
    validations:
      required: true
  - type: input
    id: claude-version
    attributes:
      label: Claude Code version
      placeholder: "1.0.0"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: component
    attributes:
      label: Affected component
      description: Which command, skill, or agent is affected?
      placeholder: "/soleur:work"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any error messages or console output
      render: text
    validations:
      required: false
