#!/usr/bin/env bash
# SOLEUR-GENERATED-OPERATOR-SCRIPT v1
#
# Generated by `soleur:operator-bootstrap` from
# plugins/soleur/skills/operator-bootstrap/template.sh.
#
# This header marker identifies the file as a generated operator script. It does
# NOT pin a byte-identical library region: there is one distribution mode and the
# script SOURCES the library, so there is no copy to drift from.
#
# <!-- Inspired by mattpocock/skills/skills/engineering/wizard/ (MIT, Copyright (c) 2026 Matt Pocock). -->
#
# WHAT TO EDIT: only `main()` and the `stage_*` functions below it, plus the
# ONE generation-time substitution of SOLEUR_OP_LIB_BAKED. Everything else above
# `main()` is the contract the library expects. NEVER hand-edit
# plugins/soleur/scripts/lib/operator-script.sh — the library is one file and
# every generated script shares it.
#
# Exit codes and stdout markers: the library header ("EXIT CODES" and "STDOUT
# MARKERS" in plugins/soleur/scripts/lib/operator-script.sh) is the single
# source. Do not restate the table here.
set -euo pipefail

# --- PROLOGUE (must stay ABOVE the `source` line) ----------------------------
# Duplicated here, never moved into the library — see "SOURCING PRECONDITIONS"
# §2 in the library header for why. Stdout, not stderr: agent runtimes surface
# stdout and swallow stderr.
case "$-" in
  *x*)
    printf '[FATAL] refusing to run under xtrace: this script handles a live credential and -x would print it (see #7797)\n'
    exit 78
    ;;
esac

# SSLKEYLOGFILE writes TLS session keys to disk; nothing a stage runs should
# inherit it. The CA-pool variables (SSL_CERT_FILE, SSL_CERT_DIR,
# CURL_CA_BUNDLE) are deliberately NOT stripped: `gh` and `hcloud` are Go
# clients that read them for their root pool, and a founder behind a
# TLS-inspecting proxy needs them (the credential linter requires only the
# xtrace refusal above — measured).
unset SSLKEYLOGFILE

# --- library resolution ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GENERATION-TIME SUBSTITUTION. The generator (operator-bootstrap/SKILL.md §3)
# replaces the placeholder below with the ABSOLUTE path of the library resolved
# at generation time — `realpath "${CLAUDE_PLUGIN_ROOT}/scripts/lib/operator-
# script.sh"`. A generated script lives at
# knowledge-base/project/specs/feat-<name>/bootstrap.sh in the FOUNDER's repo,
# where no relative path to the plugin exists and CLAUDE_PLUGIN_ROOT is unset in
# a founder's terminal; without the bake the only reachable outcome from that
# location was LIB_MISSING (measured, review F1). An unsubstituted placeholder
# is not an absolute path, so the loop below treats it as "not baked", never as
# a path — and the loop deliberately does not spell the placeholder, so a global
# substitution cannot rewrite the guard along with the value.
SOLEUR_OP_LIB_BAKED="/home/jean/.local/share/devin/cli/plugins/cache/github.com_jikig-ai_soleur_plugins_soleur-5a09ea60/0.0.0-unversioned/scripts/lib/operator-script.sh"

# Resolution order, most explicit first:
#   1. SOLEUR_OP_LIB      — explicit env override (a moved plugin, a test). Must
#                           be ABSOLUTE: `-r` tests a relative name against cwd
#                           while `source` searches PATH for it, two different
#                           files.
#   2. CLAUDE_PLUGIN_ROOT — a script run from inside a Claude Code session: the
#                           LIVE plugin, which beats a bake that may point at a
#                           stale marketplace cache hash.
#   3. the baked path     — what a generated script runs on in a founder's
#                           terminal, where 2 is unset.
#   4. hard exit 64, naming the LAST candidate that was rejected.
SOLEUR_OP_LIB="${SOLEUR_OP_LIB:-}"
last_rejected="<no candidate was absolute>"
if [[ -n "$SOLEUR_OP_LIB" && "$SOLEUR_OP_LIB" != /* ]]; then
  last_rejected="$SOLEUR_OP_LIB (SOLEUR_OP_LIB must be an absolute path)"
  SOLEUR_OP_LIB=""
fi
if [[ -z "$SOLEUR_OP_LIB" ]]; then
  for candidate in \
    "${CLAUDE_PLUGIN_ROOT:-/nonexistent}/scripts/lib/operator-script.sh" \
    "$SOLEUR_OP_LIB_BAKED"
  do
    [[ "$candidate" == /* ]] || continue
    if [[ -r "$candidate" ]]; then SOLEUR_OP_LIB="$candidate"; break; fi
    last_rejected="$candidate"
  done
fi

# HARD EXIT, never a stub. ADR-178 Context §1 records what fail-closed stubs did
# to `cleanup-merged`: it refused to reap forever while reporting success.
if [[ -z "$SOLEUR_OP_LIB" || ! -r "$SOLEUR_OP_LIB" ]]; then
  printf 'SOLEUR_BOOTSTRAP_LIB_MISSING path=%s\n' "${SOLEUR_OP_LIB:-$last_rejected}"
  printf 'Install or update the Soleur plugin, or set SOLEUR_OP_LIB to the absolute path of the library.\n'
  exit 64
fi
unset last_rejected

# shellcheck source=../../scripts/lib/operator-script.sh disable=SC1091
source "$SOLEUR_OP_LIB"

# API contract (library header §API). EQUALITY: the library auto-updates with
# the plugin while this script is frozen in the founder's repository, so
# "library newer than script" is the only incompatibility that can occur, and
# `-ge` admitted exactly that (measured: a v2 library that had renamed a helper
# passed the gate, wrote run_begin and stage 1, then died at the call — the
# mid-stage death this check exists to prevent). Refused BEFORE any ledger
# write.
[[ ${SOLEUR_OP_LIB_API:-0} -eq 1 ]] || {
  printf 'SOLEUR_BOOTSTRAP_LIB_INCOMPATIBLE need=1 got=%s\n' "${SOLEUR_OP_LIB_API:-0}"
  exit 64
}

# --- configuration -----------------------------------------------------------
SLUG="${SLUG:-feat-8450-ci-concurrency}"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
: "${SOLEUR_BOOTSTRAP_LEDGER:=${SCRIPT_DIR}/bootstrap-runs.jsonl}"
export SOLEUR_BOOTSTRAP_LEDGER
TOTAL_STAGES=4

usage() {
  cat <<USAGE
Usage: bootstrap.sh [--reset <KEY>] [--help]

  --reset <KEY>   Forget a persisted .env value so the next run re-asks for it.
                  A wrong credential is otherwise permanent: the value is stored
                  before it can be validated, and the environment-first ladder
                  means a re-run never re-prompts.
  --help          This text.

Environment:
  SOLEUR_BOOTSTRAP_LEDGER=<path>     Run ledger (default: beside this script).
  SOLEUR_OP_LIB=<abs-path>           Override the library path baked at generation.
  SOLEUR_BOOTSTRAP_UPGRADE_NOT_BEFORE=<ISO-8601 Z>
                                   Pin the soak cutoff to the billing-receipt
                                   time instead of the plan-verification time.

Skip variables — one per class-1/class-3 prompt in THIS script, derived from
its source so the list cannot drift (naming convention: SOLEUR_BOOTSTRAP_<WHAT>
for a value, SOLEUR_BOOTSTRAP_SKIP_<WHAT>_BARRIER for a barrier). The
destructive-write acknowledgement has NONE, by rule:
$(grep -oE '^[[:space:]]*soleur_op_(barrier|value) SOLEUR_BOOTSTRAP_[A-Z0-9_]+' "${BASH_SOURCE[0]}" | awk '{print "  " $2}' | sort -u)
USAGE
}

# --- argument validation -----------------------------------------------------
# Deliberately ABOVE the EXIT trap installed below: a usage error must print no
# "Stopped during stage" banner, and `--reset` is not a stage.
RESET_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset) RESET_KEY="${2:-}"; [[ -n "$RESET_KEY" ]] || { echo "Error: --reset needs a KEY" >&2; usage >&2; exit 1; }; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

# --- the credentials file must be ignored by git ------------------------------
# This script lives in a TRACKED directory (SKILL.md §Where), and its .env holds
# live credentials. A .gitignore that does not cover it turns the founder's next
# `git add .` into a pushed token (review P1-1). Checked BEFORE the first write —
# `--reset` writes too — on the .env AND on the `.tmp.XXXXXX` sibling the upsert
# creates beside it, which a bare `.env` pattern does not cover. Outside a git
# work tree (or without git) there is nothing to commit, so the check passes.
#
# PROBE THE RESOLVED PATH — the writer does. `soleur_op_env_upsert` and
# `soleur_op_env_reset` both `readlink -f` before writing, so probing the link
# NAME asks git about a file the write never touches: a founder who symlinks
# .env at a shared credentials file gets an ignored name, a passing probe, and
# the value written to a target git reports as untracked-and-not-ignored. The
# `.tmp.XXXXXX` sibling is created beside the RESOLVED file too, so it is
# derived from the resolved path rather than from $ENV_FILE. Confirmed against
# a fixture; Guard 7's symlink rows pin it.
env_not_ignored() {
  local dir; dir="$(dirname "$1")"
  git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 1
  ! git -C "$dir" check-ignore -q "$1"
}
ENV_FILE_RESOLVED="$(readlink -f -- "$ENV_FILE" 2>/dev/null || printf '%s' "$ENV_FILE")"
for probe in "$ENV_FILE_RESOLVED" "${ENV_FILE_RESOLVED}.tmp.XXXXXX"; do
  if env_not_ignored "$probe"; then
    printf 'SOLEUR_BOOTSTRAP_ENV_NOT_IGNORED path=%s\n' "$probe"
    printf 'The credentials file would be committed. Add it to .gitignore first (a pattern such as .env* covers both the file and its temp sibling).\n'
    exit 64
  fi
done
unset probe

if [[ -n "$RESET_KEY" ]]; then
  soleur_op_env_reset "$ENV_FILE" "$RESET_KEY"
  soleur_op_green "Forgot ${RESET_KEY}. Re-run to be asked for it again."
  exit 0
fi

# --- terminal outcome --------------------------------------------------------
# ONE trap. On a non-zero exit inside a stage it tells the founder which stage
# stopped, that nothing else was changed, and the one command that resumes —
# and it settles the stage in the ledger as `failed` with the exit code, so the
# ledger can say something other than "ok" (review P2-12). A library refusal
# (INPUT_REQUIRED, ABORTED) has already printed its own marker and sentence and
# written its `run_halt` line before this fires; the trap adds the stage context.
SCRIPT_PATH="${SCRIPT_DIR}/$(basename "${BASH_SOURCE[0]}")"
CURRENT_STAGE_INDEX=0
CURRENT_STAGE_NAME=""
on_exit() {
  local rc=$?
  [[ "$rc" -ne 0 && "$CURRENT_STAGE_INDEX" -gt 0 ]] || return 0
  # "Nothing else was changed" is FALSE on one path the library documents: a
  # secret whose write returned 0 and whose read-back did not confirm it may be
  # live (SOLEUR_BOOTSTRAP_SECRET_VERIFY_FAILED). Telling the founder nothing
  # changed is precisely what stops them revoking it, so the library raises a
  # flag and this sentence defers to it.
  if [[ -n "${SOLEUR_OP_WRITE_MAY_HAVE_LANDED:-}" ]]; then
    printf 'Stopped during stage %s (%s). A credential may already have been written — check it and revoke it if you did not mean to. Run: bash %s — already-done steps are skipped.\n' \
      "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" "$SCRIPT_PATH"
  else
    printf 'Stopped during stage %s (%s). Nothing else was changed. Run: bash %s — already-done steps are skipped.\n' \
      "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" "$SCRIPT_PATH"
  fi
  soleur_op_stage_end "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" failed "$rc"
}
trap on_exit EXIT

# run_stage <index> <name> <function>
#   Begin/settle around every stage, and the context the EXIT trap reports.
run_stage() {
  CURRENT_STAGE_INDEX="$1"; CURRENT_STAGE_NAME="$2"
  soleur_op_stage_begin "$1" "$2"
  "$3"
  soleur_op_stage_end "$1" "$2" ok 0
  CURRENT_STAGE_INDEX=0; CURRENT_STAGE_NAME=""
}

# =============================================================================
# STAGES — everything below this line is yours. Replace the examples.
# =============================================================================
#
# Each stage: precondition first ("already satisfied?"), then the action, then an
# independent verification. Re-run is not idempotent over a non-idempotent create
# unless the precondition makes it so, and a founder who is interrupted has no
# safe action without it.
#
# The library sets `umask 077`, and every child a stage starts INHERITS it: a
# file a stage writes for someone else (a public key, a config the vendor CLI
# reads) lands 0600. Escape per command, never globally:
#   (umask 022; printf '%s\n' "$pubkey" > "$HOME/.ssh/id.pub")
#
# Feature: #8450 / PR #8472 — GitHub Actions concurrency ceiling.
# One human act (the paid org plan upgrade) blocks four scriptable steps:
# verify + record UPGRADE_NOT_BEFORE, flip the expense ledger, dispatch the
# Sentry monitor transition, and enroll the queue-tail soak probe. The prose
# form of this procedure is operator-upgrade-steps.md beside this script;
# this file is the runnable form hr-multi-step-post-merge-bootstrap-script
# requires.

REPO="jikig-ai/soleur"
ISSUE_NUM=8450
PR_NUM=8472
LEDGER_BRANCH="ops-8450-team-upgrade-ledger"
EXPENSES_PATH="knowledge-base/operations/expenses.md"
MEASUREMENTS_PATH="knowledge-base/project/specs/feat-8450-ci-concurrency/measurements.md"
PROBE_SCRIPT="scripts/followthroughs/actions-queue-tail-8450.sh"
MONITOR_WORKFLOW="apply-sentry-infra.yml"

# ISO-8601 UTC ("YYYY-MM-DDTHH:MM:SSZ") -> epoch. GNU `date -d` first, BSD/macOS
# `date -j -f` fallback — the founder's terminal may be either.
iso_epoch() {
  date -u -d "$1" +%s 2>/dev/null && return 0
  date -u -j -f '%Y-%m-%dT%H:%M:%SZ' "$1" +%s 2>/dev/null
}

# The timestamp recorded by stage 1. Read per call so a re-run that resumes
# mid-list sees the value stage 1 persisted rather than a stale global.
upgrade_not_before() {
  if [[ -f "$ENV_FILE" ]]; then
    grep -a '^UPGRADE_NOT_BEFORE=' "$ENV_FILE" | tail -1 | cut -d= -f2-
  fi
}

# --- Stage 1: the paid plan upgrade (class-3 barrier + independent verify) ---
# The upgrade is a payment authorization in the GitHub billing UI — the one
# step no API reaches. The barrier attests the human did it; the `plan.name`
# read immediately after is what proves it. UPGRADE_NOT_BEFORE is stamped at
# first successful verification and persisted, so a re-run keeps the original
# boundary (the soak probe rejects samples that predate it).
stage_1_team_upgrade() {
  local plan
  plan="$(gh api orgs/jikig-ai --jq .plan.name)"
  if [[ "$plan" == "team" && -n "$(upgrade_not_before)" ]]; then
    soleur_op_yellow "  already satisfied: plan.name=team and UPGRADE_NOT_BEFORE is recorded"
    return 0
  fi

  if [[ "$plan" != "team" ]]; then
    echo "  1. GitHub -> org 'jikig-ai' -> Settings -> Billing -> Upgrade to Team."
    echo "     ~\$4/user/month (1 seat today; annual prepay ~\$3.67/seat/mo)."
    echo "     Payment-card entry is the human gate — no API or Terraform resource reaches it."
    soleur_op_barrier SOLEUR_BOOTSTRAP_SKIP_TEAM_UPGRADE_BARRIER "  Org upgraded to Team? Type 'yes' to continue: "
    plan="$(gh api orgs/jikig-ai --jq .plan.name)"
    if [[ "$plan" != "team" ]]; then
      soleur_op_red "plan.name is still '${plan}' — the barrier attested nothing."
      soleur_op_red "If the upgrade just completed, wait a minute and re-run."
      return 1
    fi
  fi

  # Timestamp: explicit override > persisted value > now. The override is for
  # an operator who wants earliest= pinned to the billing-receipt time rather
  # than verification time; it is read from the environment, not prompted.
  local ts="${SOLEUR_BOOTSTRAP_UPGRADE_NOT_BEFORE:-}"
  [[ -n "$ts" ]] || ts="$(upgrade_not_before)"
  [[ -n "$ts" ]] || ts="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  # The value lands verbatim in the stage-4 `earliest=` directive and in
  # measurements.md — a malformed stamp is worse than none (the probe's
  # string-compare cutoff would misfilter silently), so validate the format.
  [[ "$ts" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || {
    soleur_op_red "UPGRADE_NOT_BEFORE '${ts}' is not ISO-8601 UTC (YYYY-MM-DDTHH:MM:SSZ)"
    return 1
  }
  soleur_op_env_upsert "$ENV_FILE" UPGRADE_NOT_BEFORE "$ts"
  soleur_op_green "  plan.name=team verified; UPGRADE_NOT_BEFORE=${ts}"
}

# --- Stage 2: expense ledger + measurements record (lands as a small PR) ------
# Two tracked-file writes. Done through the contents API so the script does not
# depend on which worktree or checkout the founder runs it from — the only
# durable path is a PR against main (ruleset: no direct pushes).
fetch_file() { # <path> <ref> -> decoded content on stdout
  gh api "repos/${REPO}/contents/$1?ref=$2" --jq .content | base64 -d
}

stage_2_ledger() {
  # The GitHub Team row lands on main only via PR #8472 — the flip is post-merge.
  local pr_state
  pr_state="$(gh pr view "$PR_NUM" --repo "$REPO" --json state --jq .state)"
  if [[ "$pr_state" != "MERGED" ]]; then
    soleur_op_red "  PR #${PR_NUM} is ${pr_state} — the ledger row lands with it. Merge it, then re-run."
    return 1
  fi

  local ts; ts="$(upgrade_not_before)"
  [[ -n "$ts" ]] || { soleur_op_red "UPGRADE_NOT_BEFORE missing — stage 1 did not record it"; return 1; }
  # A hand-edited or stale .env value flows verbatim into sed transforms, the
  # ledger PR body, and the stage-3 directive — re-validate on the read path
  # (the stage-1 early-return arm never re-checked it).
  [[ "$ts" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || {
    soleur_op_red "persisted UPGRADE_NOT_BEFORE '${ts}' is not ISO-8601 UTC — fix .env or --reset UPGRADE_NOT_BEFORE"; return 1; }
  local upg_date="${ts%%T*}"

  # Already satisfied? Ask the vendor (main), never a local marker.
  if fetch_file "$EXPENSES_PATH" main | grep 'GitHub Team (org plan, jikig-ai)' | grep -q '| active |'; then
    soleur_op_yellow "  already satisfied: ledger row is 'active' on main"
    return 0
  fi
  # An open PR from the ledger branch satisfies the stage only if the branch
  # actually carries the flip — a stale or hand-made PR with wrong content
  # must not count. Remember it exists: `gh pr create` below would fail on an
  # existing PR, aborting under set -e AFTER the contents PUTs already landed
  # (and the trap's "Nothing else was changed" would be a lie).
  local pr_preexisting=""
  if [[ -n "$(gh pr list --repo "$REPO" --head "$LEDGER_BRANCH" --state open --json number --jq '.[0].number // empty')" ]]; then
    if fetch_file "$EXPENSES_PATH" "$LEDGER_BRANCH" | grep 'GitHub Team (org plan, jikig-ai)' | grep -q '| active |'; then
      soleur_op_yellow "  already satisfied: ledger PR from ${LEDGER_BRANCH} carries the flip"
      return 0
    fi
    pr_preexisting=1
    soleur_op_yellow "  ledger PR exists but lacks the flip — rewriting ${LEDGER_BRANCH} content"
  fi

  echo "  Flipping the expenses.md GitHub Team row to 'active' and recording"
  echo "  UPGRADE_NOT_BEFORE=${ts} in measurements.md — via a PR on ${LEDGER_BRANCH}."

  local main_sha
  main_sha="$(gh api "repos/${REPO}/git/ref/heads/main" --jq .object.sha)"
  if ! gh api "repos/${REPO}/git/ref/heads/${LEDGER_BRANCH}" >/dev/null 2>&1; then
    gh api -X POST "repos/${REPO}/git/refs" -f ref="refs/heads/${LEDGER_BRANCH}" -f sha="$main_sha" >/dev/null
  fi

  local tmp; tmp="$(mktemp)"

  # expenses.md — flip only the GitHub Team row. The transform input is MAIN
  # (SHA-pinned — immutable, so no read race and no stale-branch base), not
  # the ledger branch: a partially-applied branch must re-derive cleanly.
  fetch_file "$EXPENSES_PATH" "$main_sha" \
    | sed "/GitHub Team (org plan, jikig-ai)/ s/approved-not-billing | -/active | ${upg_date}/" > "$tmp"
  grep -q "GitHub Team (org plan, jikig-ai) | GitHub | dev-tools | 4.00 | active | ${upg_date} |" "$tmp" \
    || { soleur_op_red "expenses.md transform produced no 'active' row — ledger format drifted"; rm -f "$tmp"; return 1; }
  local expenses_sha
  expenses_sha="$(gh api "repos/${REPO}/contents/${EXPENSES_PATH}?ref=${LEDGER_BRANCH}" --jq .sha)"
  gh api -X PUT "repos/${REPO}/contents/${EXPENSES_PATH}" \
    -f message="chore(8450): flip GitHub Team ledger row to active" \
    -f content="$(base64 < "$tmp" | tr -d '\n')" \
    -f branch="$LEDGER_BRANCH" -f sha="$expenses_sha" >/dev/null

  # measurements.md — fill the UPGRADE_NOT_BEFORE TBD slot (anchored to its
  # line so no other **TBD** is touched).
  fetch_file "$MEASUREMENTS_PATH" "$main_sha" \
    | sed "/UPGRADE_NOT_BEFORE/ s/\*\*TBD\*\*/\`${ts}\`/" > "$tmp"
  grep -q "UPGRADE_NOT_BEFORE.*${ts}" "$tmp" \
    || { soleur_op_red "measurements.md transform produced no timestamp — format drifted"; rm -f "$tmp"; return 1; }
  local meas_sha
  meas_sha="$(gh api "repos/${REPO}/contents/${MEASUREMENTS_PATH}?ref=${LEDGER_BRANCH}" --jq .sha)"
  gh api -X PUT "repos/${REPO}/contents/${MEASUREMENTS_PATH}" \
    -f message="chore(8450): record UPGRADE_NOT_BEFORE=${ts}" \
    -f content="$(base64 < "$tmp" | tr -d '\n')" \
    -f branch="$LEDGER_BRANCH" -f sha="$meas_sha" >/dev/null
  rm -f "$tmp"

  if [[ -z "$pr_preexisting" ]]; then
    gh pr create --repo "$REPO" --base main --head "$LEDGER_BRANCH" \
      --title "chore(8450): GitHub Team ledger flip + UPGRADE_NOT_BEFORE" \
      --body "Ref #8450

Post-upgrade bookkeeping generated by knowledge-base/project/specs/feat-8450-ci-concurrency/bootstrap.sh:

- expenses.md: GitHub Team (org plan, jikig-ai) approved-not-billing -> active (${upg_date})
- measurements.md: UPGRADE_NOT_BEFORE := ${ts} (gh api orgs/jikig-ai plan.name == team verification time)" >/dev/null
  fi

  # Verify the PR exists.
  local pr_url
  pr_url="$(gh pr list --repo "$REPO" --head "$LEDGER_BRANCH" --state open --json url --jq '.[0].url // empty')"
  [[ -n "$pr_url" ]] || { soleur_op_red "branch pushed but no open PR found for ${LEDGER_BRANCH}"; return 1; }
  soleur_op_green "  ledger PR: ${pr_url}"
}

# --- Stage 3: enroll the queue-tail soak probe --------------------------------
# Post-merge only (the sweeper runs probe scripts from main). The directive goes
# in the ISSUE BODY, unfenced at column 0 — the sweeper skips fenced/indented
# blocks and never reads comments for enrollment
# (runbooks/followthrough-convention.md §4). Runs BEFORE the class-2 dispatch so
# a non-TTY run completes every automatable step before the human gate.
stage_3_probe_directive() {
  local pr_state
  pr_state="$(gh pr view "$PR_NUM" --repo "$REPO" --json state --jq .state)"
  if [[ "$pr_state" != "MERGED" ]]; then
    soleur_op_red "  PR #${PR_NUM} is ${pr_state} — this step is post-merge. Merge it, then re-run."
    return 1
  fi

  local ts; ts="$(upgrade_not_before)"
  [[ -n "$ts" ]] || { soleur_op_red "UPGRADE_NOT_BEFORE missing — stage 1 did not record it"; return 1; }
  # Same re-validation as stage 2: the persisted value lands verbatim in the
  # directive's earliest= token.
  [[ "$ts" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || {
    soleur_op_red "persisted UPGRADE_NOT_BEFORE '${ts}' is not ISO-8601 UTC — fix .env or --reset UPGRADE_NOT_BEFORE"; return 1; }
  local directive="<!-- soleur:followthrough script=${PROBE_SCRIPT} earliest=${ts} secrets=GH_TOKEN -->"

  # follow-through label must exist before the edit can apply it.
  gh label list --repo "$REPO" --json name --jq '.[].name' | grep -qx 'follow-through' \
    || gh label create follow-through --repo "$REPO" --color '0E8A16' --description 'Sweeper-verified deferred follow-through' >/dev/null

  local body
  body="$(gh issue view "$ISSUE_NUM" --repo "$REPO" --json body --jq .body)"
  if printf '%s\n' "$body" | grep -qxF "$directive"; then
    soleur_op_yellow "  already satisfied: directive present in #${ISSUE_NUM} body"
    gh issue edit "$ISSUE_NUM" --repo "$REPO" --add-label follow-through >/dev/null
    return 0
  fi
  # First-wins: the sweeper honors only the FIRST soleur:followthrough in a
  # body and skips fenced copies — a fenced or foreign directive would shadow
  # the one we append while our own grep reports success.
  local n_directives
  n_directives="$(printf '%s\n' "$body" | grep -c 'soleur:followthrough' || true)"
  if [[ "$n_directives" != "0" ]]; then
    soleur_op_red "  #${ISSUE_NUM} body already contains ${n_directives} soleur:followthrough mention(s) — the sweeper honors the first only. Inspect/remove it, then re-run."
    return 1
  fi

  gh issue edit "$ISSUE_NUM" --repo "$REPO" --add-label follow-through \
    --body "$(printf '%s\n\n%s\n' "$body" "$directive")" >/dev/null

  # Verify the directive landed as an exact whole line (unfenced, column 0).
  gh issue view "$ISSUE_NUM" --repo "$REPO" --json body --jq .body \
    | grep -qxF "$directive" \
    || { soleur_op_red "directive did not land at column 0 in the issue body"; return 1; }
  soleur_op_green "  directive enrolled on #${ISSUE_NUM} (earliest=${ts})"
}

# --- Stage 4: Sentry monitor transition dispatch (class-2 ack, prod apply) ---
# Post-merge only: shortens the zot_restart_loop_alarm transition gap to the new
# hourly cadence. One transient missed-check-in issue is EXPECTED until this
# apply lands (operator-upgrade-steps.md Step 4). Deliberately LAST: it is the
# only stage behind an unbypassable class-2 ack, so an unattended run still
# completes stages 1-3 first.
stage_4_monitor_dispatch() {
  local pr_state merged_at
  read -r pr_state merged_at < <(gh pr view "$PR_NUM" --repo "$REPO" --json state,mergedAt --jq '"\(.state) \(.mergedAt)"')
  if [[ "$pr_state" != "MERGED" ]]; then
    soleur_op_red "  PR #${PR_NUM} is ${pr_state} — this step is post-merge. Merge it, then re-run."
    return 1
  fi
  local merge_epoch
  merge_epoch="$(iso_epoch "$merged_at")"
  [[ -n "$merge_epoch" ]] || { soleur_op_red "could not parse PR mergedAt '${merged_at}'"; return 1; }

  # Already satisfied = a SUCCESSFUL apply registered AFTER the merge — the
  # merge-triggered run is the normal satisfier. Anchored to mergedAt, not
  # UPGRADE_NOT_BEFORE: an apply between upgrade and merge applied the OLD
  # crontabs, and a failed apply leaves the monitor/workflow skew open.
  local latest_ok
  latest_ok="$(gh run list --repo "$REPO" --workflow "$MONITOR_WORKFLOW" --limit 10 \
    --json createdAt,conclusion \
    --jq '[.[] | select(.conclusion == "success")] | .[0].createdAt // empty')"
  if [[ -n "$latest_ok" ]] && [[ "$(iso_epoch "$latest_ok")" -ge "$merge_epoch" ]]; then
    soleur_op_yellow "  already satisfied: ${MONITOR_WORKFLOW} applied successfully at ${latest_ok} (>= merge)"
    return 0
  fi

  echo "  This dispatches ${MONITOR_WORKFLOW}: a Terraform apply against shared prod"
  echo "  Sentry monitors (transition gap -> hourly). Until it lands, one transient"
  echo "  missed-check-in issue on zot_restart_loop_alarm is EXPECTED."
  soleur_op_ack_or_die "  Dispatch it now? Type 'yes': "

  local dispatch_epoch
  dispatch_epoch="$(date -u +%s)"
  gh workflow run "$MONITOR_WORKFLOW" --repo "$REPO" -f reason="post-8450 monitor transition (bootstrap)"

  # Verify a new run registered (bounded poll — dispatch is near-instant; the
  # apply's own conclusion is tracked on the Actions tab, the stage only
  # asserts registration).
  local tries=0 latest_created
  while [[ $tries -lt 8 ]]; do
    sleep 15
    latest_created="$(gh run list --repo "$REPO" --workflow "$MONITOR_WORKFLOW" --limit 1 --json createdAt --jq '.[0].createdAt // empty')"
    if [[ -n "$latest_created" ]] && [[ "$(iso_epoch "$latest_created")" -ge "$dispatch_epoch" ]]; then
      soleur_op_green "  dispatched; latest run registered at ${latest_created}"
      return 0
    fi
    tries=$((tries + 1))
  done
  soleur_op_red "  dispatch returned ok but no new run appeared within 2 minutes — check the Actions tab."
  return 1
}

main() {
  soleur_op_require_bins grep mktemp sed date gh base64 git tr sleep awk sort cut tail readlink dirname basename
  soleur_op_ledger_init "$TOTAL_STAGES" "bootstrap.sh"

  # No resume index: every stage's precondition makes a re-run from stage 1
  # skip what is already done, so re-run IS resume.
  run_stage 1 "GitHub Team upgrade (paid)" stage_1_team_upgrade
  run_stage 2 "expense ledger + measurements record" stage_2_ledger
  run_stage 3 "enroll queue-tail soak probe" stage_3_probe_directive
  run_stage 4 "Sentry monitor transition dispatch" stage_4_monitor_dispatch

  soleur_op_summary_begin "BOOTSTRAP COMPLETE."
  soleur_op_summary_line "Values were written to ${ENV_FILE} (mode 600)."
  soleur_op_summary_line "Run ledger: ${SOLEUR_BOOTSTRAP_LEDGER}"
  soleur_op_summary_line "Remaining: merge the ${LEDGER_BRANCH} PR, then the sweeper auto-runs ${PROBE_SCRIPT} once >=5 post-upgrade samples exist."
}

main "$@"
