#!/usr/bin/env bash
# SOLEUR-GENERATED-OPERATOR-SCRIPT v2
#
# Generated by `soleur:operator-bootstrap` from
# plugins/soleur/skills/operator-bootstrap/template.sh.
#
# This header marker identifies the file as a generated operator script. It does
# NOT pin a byte-identical library region: there is one distribution mode and the
# script SOURCES the library, so there is no copy to drift from.
#
# <!-- Inspired by mattpocock/skills/skills/engineering/wizard/ (MIT, Copyright (c) 2026 Matt Pocock). -->
#
# THE CONTRACT (ADR-264): an AGENT runs this script, one stage at a time, with no
# terminal. A human acknowledges every production write, but at the harness
# approval prompt on the exact command, not at a typed `yes` (this guards against an
# agent acting on a mistaken instruction, not a compromised one; headless, bypass-mode
# and no-hook surfaces defer or refuse and never auto-approve — ADR-264):
#   bash bootstrap.sh --list                                        the stages (static; no credentials)
#   bash bootstrap.sh --stage <name>                                read stage: runs; write stage: prints the PLAN
#   bash bootstrap.sh --stage <name> --apply --plan-digest <d>      write stage: the approved write
# There is no run-all mode and no `--yes`. Every stage is idempotent: a re-run
# of a satisfied stage changes nothing and needs no approval.
#
# WHAT TO EDIT: the `# SOLEUR-STAGE` lines and the `read_*` / `plan_*` / `apply_*`
# functions below them, plus the ONE generation-time substitution of
# SOLEUR_OP_LIB_BAKED. Everything above the STAGES banner is the contract the
# library expects. NEVER hand-edit plugins/soleur/scripts/lib/operator-script.sh
# — the library is one file and every generated script shares it.
#
# Exit codes and stdout markers: the library header ("EXIT CODES" and "STDOUT
# MARKERS" in plugins/soleur/scripts/lib/operator-script.sh) is the single
# source. Do not restate the table here.
set -euo pipefail

# --- PROLOGUE (must stay ABOVE the `source` line) ----------------------------
# Duplicated here, never moved into the library — see "SOURCING PRECONDITIONS"
# §2 in the library header for why. Stdout, not stderr: agent runtimes surface
# stdout and swallow stderr.
case "$-" in
  *x*)
    printf '[FATAL] refusing to run under xtrace: this script handles a live credential and -x would print it (see #7797)\n'
    exit 78
    ;;
esac

# SSLKEYLOGFILE writes TLS session keys to disk; nothing a stage runs should
# inherit it. The CA-pool variables (SSL_CERT_FILE, SSL_CERT_DIR,
# CURL_CA_BUNDLE) are deliberately NOT stripped: `gh` and `hcloud` are Go
# clients that read them for their root pool, and a founder behind a
# TLS-inspecting proxy needs them (the credential linter requires only the
# xtrace refusal above — measured).
unset SSLKEYLOGFILE

# No pathname expansion anywhere below: stage code loops over vendor-supplied names
# (`for s in $SLUGS`), and a name such as `*` must stay a name, never a file glob.
set -f

# --- the stage table ---------------------------------------------------------
# ONE source of truth: --list prints it, the dispatcher validates `--stage`
# against it, and the approval hook reads these same lines (statically; it never
# executes this script) to show the human the impact and rollback they are
# approving. Format:  name|class|impact|rollback   (class: read | write).
# A write stage's impact and rollback are one plain sentence each, written for a
# founder, with no `|` in them.
#
# SOLEUR-STAGE preflight|read|Nothing changes: this only checks Doppler, GitHub and the two source values.|None needed.
# SOLEUR-STAGE copy-app-values|write|Copies the release App's id and private key into a second Doppler project (soleur-infra-app); nothing reads the copy yet, so releases are unaffected.|Delete the copied values from the soleur-infra-app prd config; the soleur-infra-privileged source is untouched.
# SOLEUR-STAGE prove-live-app|read|Nothing changes: this signs a short-lived token with the copied key and asks GitHub whether it is the live App.|None needed.
# SOLEUR-STAGE mint-and-store-token|write|Creates a read-only Doppler token for soleur-infra-app and saves it as the GitHub secret DOPPLER_TOKEN_INFRA_APP (infra-privileged environment), then revokes older tokens of the same name; once releases use it, a rotation replaces the token they read.|Before releases use it: revoke the release-app-mint token on soleur-infra-app prd and delete DOPPLER_TOKEN_INFRA_APP from the infra-privileged environment. Afterwards: run the stage again with --rotate-token instead.
# SOLEUR-STAGE verify|read|Nothing changes: this lists names only and never prints a value.|None needed.

# `--list` is a STATIC read of the table above: no library, no credentials, no
# network, so an agent can probe it first. It sits BELOW the xtrace refusal and
# ABOVE library resolution (the linter allows no command above the refusal).
if [[ "${1:-}" == "--list" ]]; then
  grep -a '^# SOLEUR-STAGE ' "${BASH_SOURCE[0]}" | sed 's/^# SOLEUR-STAGE //' | while IFS='|' read -r list_stage list_class _; do
    printf 'SOLEUR_BOOTSTRAP_STAGE_DECL stage=%s class=%s\n' "$list_stage" "$list_class"
  done
  exit 0
fi

# --- library resolution ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GENERATION-TIME SUBSTITUTION. The generator (operator-bootstrap/SKILL.md §3)
# replaces the placeholder below with the ABSOLUTE path of the library resolved
# at generation time — `realpath "${CLAUDE_PLUGIN_ROOT}/scripts/lib/operator-
# script.sh"`. A generated script lives at
# knowledge-base/project/specs/feat-<name>/bootstrap.sh in the FOUNDER's repo,
# where no relative path to the plugin exists and CLAUDE_PLUGIN_ROOT may be unset;
# without the bake the only reachable outcome from that location was LIB_MISSING
# (measured, review F1). An unsubstituted placeholder is not an absolute path, so
# the loop below treats it as "not baked", never as a path — and the loop
# deliberately does not spell the placeholder, so a global substitution cannot
# rewrite the guard along with the value.
SOLEUR_OP_LIB_BAKED="/data/git-repositories/jikig-ai/soleur/plugins/soleur/scripts/lib/operator-script.sh"

# Resolution order, most explicit first:
#   1. SOLEUR_OP_LIB      — explicit env override (a moved plugin, a test). Must
#                           be ABSOLUTE: `-r` tests a relative name against cwd
#                           while `source` searches PATH for it, two different
#                           files.
#   2. CLAUDE_PLUGIN_ROOT — a script run from inside a Claude Code session: the
#                           LIVE plugin, which beats a bake that may point at a
#                           stale marketplace cache hash.
#   3. the baked path     — what a generated script runs on where 2 is unset.
#   4. hard exit 64, naming the LAST candidate that was rejected.
# A candidate that does not define the staged gate (a stale cached library) is
# skipped BEFORE it is sourced, so it can never shadow a newer baked one.
SOLEUR_OP_LIB="${SOLEUR_OP_LIB:-}"
last_rejected="<no candidate was absolute>"
if [[ -n "$SOLEUR_OP_LIB" && "$SOLEUR_OP_LIB" != /* ]]; then
  last_rejected="$SOLEUR_OP_LIB (SOLEUR_OP_LIB must be an absolute path)"
  SOLEUR_OP_LIB=""
fi
# An override is held to the same test as every other candidate (a readable regular
# file named operator-script.sh that defines the gate): a stray value cannot make this
# script source an arbitrary file. HONEST LIMIT: a process that can write such a file
# and set this variable can also edit this script; that is the hijacked-agent case the
# approval receipt does not claim to resist (ADR-264).
if [[ -n "$SOLEUR_OP_LIB" ]] && ! { [[ -f "$SOLEUR_OP_LIB" && ! -L "$SOLEUR_OP_LIB" && -r "$SOLEUR_OP_LIB" && "${SOLEUR_OP_LIB##*/}" == "operator-script.sh" ]] && grep -aq '^soleur_op_stage_gate()' "$SOLEUR_OP_LIB"; }; then
  last_rejected="$SOLEUR_OP_LIB (SOLEUR_OP_LIB must name a regular readable operator-script.sh that defines the staged gate)"
  SOLEUR_OP_LIB=""
fi
if [[ -z "$SOLEUR_OP_LIB" ]]; then
  for candidate in \
    "${CLAUDE_PLUGIN_ROOT:-/nonexistent}/scripts/lib/operator-script.sh" \
    "$SOLEUR_OP_LIB_BAKED"
  do
    [[ "$candidate" == /* ]] || continue
    if [[ -r "$candidate" ]] && grep -aq '^soleur_op_stage_gate()' "$candidate"; then SOLEUR_OP_LIB="$candidate"; break; fi
    last_rejected="$candidate"
  done
fi

# HARD EXIT, never a stub. ADR-178 Context §1 records what fail-closed stubs did
# to `cleanup-merged`: it refused to reap forever while reporting success.
if [[ -z "$SOLEUR_OP_LIB" || ! -r "$SOLEUR_OP_LIB" ]]; then
  printf 'SOLEUR_BOOTSTRAP_LIB_MISSING path=%s\n' "${SOLEUR_OP_LIB:-$last_rejected}"
  printf 'Install or update the Soleur plugin, or set SOLEUR_OP_LIB to the absolute path of the library.\n'
  exit 64
fi
unset last_rejected

# shellcheck source=../../scripts/lib/operator-script.sh disable=SC1091
source "$SOLEUR_OP_LIB"

# API contract (library header §API). EQUALITY: the library auto-updates with
# the plugin while this script is frozen in the founder's repository, so
# "library newer than script" is the only incompatibility that can occur, and
# `-ge` admitted exactly that. Refused BEFORE any ledger write.
[[ ${SOLEUR_OP_LIB_API:-0} -eq 1 ]] || {
  printf 'SOLEUR_BOOTSTRAP_LIB_INCOMPATIBLE need=1 got=%s\n' "${SOLEUR_OP_LIB_API:-0}"
  exit 64
}
# The staged-contract capability is detected by the function itself, never by a
# second API number (the frozen legacy scripts assert API equality).
declare -F soleur_op_stage_gate >/dev/null 2>&1 || {
  printf 'SOLEUR_BOOTSTRAP_LIB_INCOMPATIBLE need=stage-1 got=%s\n' "${SOLEUR_OP_LIB_API:-0}"
  exit 64
}

# --- configuration -----------------------------------------------------------
SLUG="${SLUG:-9321-scoped-app-token-doppler}"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
: "${SOLEUR_BOOTSTRAP_LEDGER:=${SCRIPT_DIR}/bootstrap-runs.jsonl}"
export SOLEUR_BOOTSTRAP_LEDGER

usage() {
  cat <<USAGE
Usage: bootstrap.sh --list
       bootstrap.sh --stage <name>
       bootstrap.sh --stage <name> --apply --plan-digest <digest> [--rotate-token]
       bootstrap.sh --reset <KEY> | --help

  --list          The stages and their class (read or write). Static; needs nothing.
  --stage <name>  A READ stage runs. A WRITE stage prints its PLAN (what it would
                  change, in plain words, and the exact apply command) and changes nothing.
  --apply         With --stage <name> --plan-digest <digest>: perform the write. The
                  person approves the exact command at the harness prompt first.
  --plan-digest   The digest the plan printed. The script recomputes the plan; a
                  mismatch (the state moved) exits 75 and writes nothing.
  --reset <KEY>   Forget a persisted .env value so the next run re-asks for it.
  --help          This text.

There is no run-all mode and no flag that approves a write by itself.

Environment:
  SOLEUR_BOOTSTRAP_LEDGER=<path>     Run ledger (default: beside this script).
  SOLEUR_OP_LIB=<abs-path>           Override the library path baked at generation.

Skip variables — one per class-1/class-3 prompt in THIS script, derived from
its source so the list cannot drift (naming convention: SOLEUR_BOOTSTRAP_<WHAT>
for a value, SOLEUR_BOOTSTRAP_SKIP_<WHAT>_BARRIER for a barrier):
$(grep -oE '^[[:space:]]*soleur_op_(barrier|value) SOLEUR_BOOTSTRAP_[A-Z0-9_]+' "${BASH_SOURCE[0]}" | awk '{print "  " $2}' | sort -u | grep . || echo '  (none: this script has no class-1 or class-3 prompt)')
USAGE
}

# --- argument validation -----------------------------------------------------
# Deliberately ABOVE the EXIT trap installed below: a usage error must print no
# "Stopped during stage" banner, and `--reset` is not a stage. ORIG_ARGV keeps the
# invocation exactly as the shell handed it over: the approval receipt is bound to
# it (so `"a b"` and `"a" "b"` differ).
ORIG_ARGV=("$@")
STAGE=""
APPLY=0
PLAN_DIGEST=""
ROTATE_TOKEN=0
RESET_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage) STAGE="${2:-}"; [[ -n "$STAGE" ]] || { echo "Error: --stage needs a stage name (--list shows them)" >&2; usage >&2; exit 1; }; shift 2 ;;
    --apply) APPLY=1; shift ;;
    --plan-digest) PLAN_DIGEST="${2:-}"; [[ -n "$PLAN_DIGEST" ]] || { echo "Error: --plan-digest needs the digest the plan printed" >&2; usage >&2; exit 1; }; shift 2 ;;
    --rotate-token) ROTATE_TOKEN=1; shift ;;
    --reset) RESET_KEY="${2:-}"; [[ -n "$RESET_KEY" ]] || { echo "Error: --reset needs a KEY" >&2; usage >&2; exit 1; }; shift 2 ;;
    --list) soleur_op_list "${BASH_SOURCE[0]}"; exit 0 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

# --- the credentials file must be ignored by git ------------------------------
# This script lives in a TRACKED directory (SKILL.md §Where), and its .env holds
# recorded values. A .gitignore that does not cover it turns the founder's next
# `git add .` into a pushed token (review P1-1). Checked BEFORE the first write —
# `--reset` writes too — on the .env AND on the `.tmp.XXXXXX` sibling the upsert
# creates beside it, which a bare `.env` pattern does not cover. Outside a git
# work tree (or without git) there is nothing to commit, so the check passes.
#
# PROBE THE RESOLVED PATH — the writer does. `soleur_op_env_upsert` and
# `soleur_op_env_reset` both `readlink -f` before writing, so probing the link
# NAME asks git about a file the write never touches: a founder who symlinks
# .env at a shared credentials file gets an ignored name, a passing probe, and
# the value written to a target git reports as untracked-and-not-ignored. The
# `.tmp.XXXXXX` sibling is created beside the RESOLVED file too, so it is
# derived from the resolved path rather than from $ENV_FILE. Confirmed against
# a fixture; Guard 7's symlink rows pin it.
env_not_ignored() {
  local dir; dir="$(dirname "$1")"
  git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 1
  ! git -C "$dir" check-ignore -q "$1"
}
ENV_FILE_RESOLVED="$(readlink -f -- "$ENV_FILE" 2>/dev/null || printf '%s' "$ENV_FILE")"
for probe in "$ENV_FILE_RESOLVED" "${ENV_FILE_RESOLVED}.tmp.XXXXXX"; do
  if env_not_ignored "$probe"; then
    printf 'SOLEUR_BOOTSTRAP_ENV_NOT_IGNORED path=%s\n' "$probe"
    printf 'The credentials file would be committed. Add it to .gitignore first (a pattern such as .env* covers both the file and its temp sibling).\n'
    exit 64
  fi
done
unset probe

if [[ -n "$RESET_KEY" ]]; then
  soleur_op_env_reset "$ENV_FILE" "$RESET_KEY"
  soleur_op_green "Forgot ${RESET_KEY}. Re-run the stage to be asked for it again."
  exit 0
fi

if [[ -z "$STAGE" ]]; then
  printf 'SOLEUR_BOOTSTRAP_STAGE_REQUIRED\n'
  printf 'Pick one stage with --stage <name>; this script has no run-all mode. The stages are:\n'
  soleur_op_list "${BASH_SOURCE[0]}"
  exit 64
fi

# --- terminal outcome --------------------------------------------------------
# ONE trap. On a non-zero exit inside a stage it prints the STAGE_FAILED marker,
# tells the founder which stage stopped and the one command that resumes, and
# settles the stage in the ledger as `failed`. A refusal that already printed its
# own marker and sentence (approval required / invalid / plan drift, a precondition,
# a missing digest) raised the library's SOLEUR_OP_REFUSED flag and settles as
# `refused`, adding nothing. The flag, not the exit code, decides: a vendor CLI that
# exits 75 mid-write is a failure.
SCRIPT_PATH="${SCRIPT_DIR}/$(basename "${BASH_SOURCE[0]}")"
SCRIPT_REAL="$(soleur_approval_realpath "${BASH_SOURCE[0]}")"
CURRENT_STAGE_INDEX=0
CURRENT_STAGE_NAME=""
STAGE_CHANGED=""
mark_changed() { STAGE_CHANGED="${STAGE_CHANGED:+${STAGE_CHANGED}; }$1"; }
on_exit() {
  local rc=$?
  [[ "$rc" -ne 0 && "$CURRENT_STAGE_INDEX" -gt 0 ]] || return 0
  if [[ -n "${SOLEUR_OP_REFUSED:-}" ]]; then
    soleur_op_stage_end "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" refused "$rc"
    return 0
  fi
  printf 'SOLEUR_BOOTSTRAP_STAGE_FAILED stage=%s rc=%s\n' "$CURRENT_STAGE_NAME" "$rc"
  # "Nothing else was changed" is FALSE on one path the library documents: a
  # secret whose write returned 0 and whose read-back did not confirm it may be
  # live (SOLEUR_BOOTSTRAP_SECRET_VERIFY_FAILED). The library raises a flag and
  # this sentence defers to it.
  if [[ -n "${SOLEUR_OP_WRITE_MAY_HAVE_LANDED:-}" ]]; then
    printf 'Stopped during stage %s. A credential may already have been written — check it and revoke it if you did not mean to. Run the stage again to see where it stands: bash %s --stage %s\n' \
      "$CURRENT_STAGE_NAME" "$SCRIPT_PATH" "$CURRENT_STAGE_NAME"
  elif [[ -n "$STAGE_CHANGED" ]]; then
    printf 'Stopped during stage %s AFTER it may have changed production: %s. Read the lines above before re-running. Run the stage again to see where it stands: bash %s --stage %s\n' \
      "$CURRENT_STAGE_NAME" "$STAGE_CHANGED" "$SCRIPT_PATH" "$CURRENT_STAGE_NAME"
  else
    printf 'Stopped during stage %s. Nothing else was changed. Run the stage again: bash %s --stage %s\n' \
      "$CURRENT_STAGE_NAME" "$SCRIPT_PATH" "$CURRENT_STAGE_NAME"
  fi
  soleur_op_stage_end "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" failed "$rc"
}
trap on_exit EXIT

# =============================================================================
# STAGES - #9321 (ADR-241 D11): give the two App-token release jobs a Doppler
# credential that reads ONLY the two soleur-infra App values.
#
# CANONICAL SEQUENCE: knowledge-base/engineering/operations/runbooks/infra-credential-tiers-8209.md
# section "Release-job App source (#9321)". This script is the runnable form
# hr-multi-step-post-merge-bootstrap-script requires; it does not restate the runbook's reasoning.
#
# AGENT-RUN, ONE STAGE AT A TIME (ADR-264). The agent runs the stages in this order; each re-proves
# what it depends on, so an interrupted run resumes by running the stage again:
#   --list
#   --stage preflight                                              read: checks Doppler, GitHub and the two sources
#   --stage copy-app-values                                        write: prints the plan; the apply is approved by the person
#   --stage copy-app-values --apply --plan-digest <digest>
#   --stage prove-live-app                                         read: a real RS256 JWT from the copy against GitHub
#   --stage mint-and-store-token                                   write: plan, then apply as above ([--rotate-token] to rotate)
#   --stage mint-and-store-token --apply --plan-digest <digest>
#   --stage verify                                                 read: names only; prints SOLEUR_BOOTSTRAP_READY_FOR_PR2
#
# RUN IT AFTER the PR that adds Terraform's two empty containers has merged and its push apply
# succeeded (preflight fails with a named cause otherwise), and BEFORE the second PR (the switch of
# the composite action, the two release workflows and their suites) is merged.
#
# No stage prints a secret value: values and the token move only through pipes, a child's environment
# or a stdin body, and no hash of a secret is ever printed (the digest covers operation names and slugs).
# An UNREADABLE or INCONCLUSIVE read is never a PASS and never produces a plan digest.
#
# Needs, on the machine that runs it: doppler (logged in with access to soleur-infra-privileged and
# soleur-infra-app), gh (authenticated as a repo admin), jq, curl, openssl, sha256sum.
# =============================================================================

REPO="jikig-ai/soleur"
SRC_PROJECT="soleur-infra-privileged"
DST_PROJECT="soleur-infra-app"
CFG="prd"
GH_ENVIRONMENT="infra-privileged"
ENV_SECRET="DOPPLER_TOKEN_INFRA_APP"
READ_TOKEN_NAME="release-app-mint"
APP_SLUG="soleur-infra"
ID_NAME="GITHUB_INFRA_APP_ID"
PEM_NAME="GITHUB_INFRA_APP_PRIVATE_KEY"
# What a project-scoped read token's own download lists besides the secrets.
DOPPLER_META='["DOPPLER_CONFIG","DOPPLER_ENVIRONMENT","DOPPLER_PROJECT"]'
RUNBOOK="knowledge-base/engineering/operations/runbooks/infra-credential-tiers-8209.md"

# --- small helpers -------------------------------------------------------------

env_get() { # <KEY> -> the recorded non-secret value, or empty
  [[ -f "$ENV_FILE" ]] || return 0
  { grep -a "^$1=" "$ENV_FILE" || true; } | tail -1 | cut -d= -f2-
}

STAGE_FAILS=0
check() { # <label> <0|1>
  if [[ "$2" == "0" ]]; then soleur_op_green "  PASS: $1"; else soleur_op_red "  FAIL: $1"; STAGE_FAILS=$((STAGE_FAILS + 1)); fi
}
stage_verdict() { # returns 1 when any check in the stage failed
  local n="$STAGE_FAILS"; STAGE_FAILS=0
  [[ "$n" -eq 0 ]] || { soleur_op_red "  ${n} check(s) failed - see the runbook section before re-running."; return 1; }
}

now_iso() { soleur_op_now; }

# val_hash <project> <name> -> sha256 of the value (trailing newlines stripped), or EMPTY when the
# read failed or the value is empty. The hash is compared in-process and NEVER printed or logged.
val_hash() {
  local v
  v="$(doppler secrets get "$2" -p "$1" -c "$CFG" --plain 2>/dev/null)" || return 0
  [[ -n "$v" ]] || return 0
  printf '%s' "$v" | sha256sum | cut -d' ' -f1
}

# Name lists. A failed read prints nothing and returns non-zero: an unreadable list is
# INCONCLUSIVE, never "the name is absent".
env_secret_names() { gh api "repos/${REPO}/environments/${GH_ENVIRONMENT}/secrets" --paginate --jq '.secrets[].name' 2>/dev/null; }
repo_secret_names() { gh api "repos/${REPO}/actions/secrets" --paginate --jq '.secrets[].name' 2>/dev/null; }
org_secret_names() { gh api "orgs/${REPO%%/*}/actions/secrets" --paginate --jq '.secrets[].name' 2>/dev/null; }

token_slugs() { # slugs of the tokens named READ_TOKEN_NAME on the isolated project's prd config
  doppler configs tokens -p "$DST_PROJECT" -c "$CFG" --json 2>/dev/null \
    | jq -r --arg n "$READ_TOKEN_NAME" '.[] | select(.name == $n) | .slug' 2>/dev/null
}
token_names_all() { # every token name on the config, sorted, comma-joined; fails when unreadable
  doppler configs tokens -p "$DST_PROJECT" -c "$CFG" --json 2>/dev/null \
    | jq -er '[.[].name] | sort | join(",")' 2>/dev/null
}

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# app_probe <app id> <pem> -> "<http code> <slug> <id>" from GET /app with an RS256 App JWT
# (iat=now-60, exp=now+300). The JWT goes to curl as a header on stdin, never argv.
app_probe() {
  local now hdr pl sig jwt body code
  now="$(date +%s)"
  hdr="$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)"
  pl="$(printf '{"iat":%d,"exp":%d,"iss":"%s"}' $((now - 60)) $((now + 300)) "$1" | b64url)"
  sig="$(printf '%s.%s' "$hdr" "$pl" | openssl dgst -sha256 -binary -sign <(printf '%s\n' "$2") | b64url)" || sig=""
  [[ -n "$sig" ]] || { printf '000 - -'; return 0; }
  jwt="${hdr}.${pl}.${sig}"
  body="$(mktemp)"
  code="$(printf 'Authorization: Bearer %s\nAccept: application/vnd.github+json\n' "$jwt" \
    | curl --disable --noproxy '*' --proto '=https' -sS --max-time 15 -o "$body" -w '%{http_code}' -H @- \
      "https://api.github.com/app" 2>/dev/null)" || code="000"
  unset jwt
  printf '%s %s %s' "$code" "$(jq -r '.slug // "-"' "$body" 2>/dev/null || echo -)" "$(jq -r '.id // "-"' "$body" 2>/dev/null || echo -)"
  rm -f "$body"
}

# live_app_ok -> 0 only when a JWT from the DESTINATION copy gets 200 from GET /app with the expected
# slug and id. Used by the read stage and, in-process, by the write stage's plan (stages are separately
# addressable, so the later stage re-proves it instead of trusting that the earlier one ran).
live_app_ok() {
  local id pem probe
  id="$(doppler secrets get "$ID_NAME" -p "$DST_PROJECT" -c "$CFG" --plain 2>/dev/null)" || id=""
  pem="$(doppler secrets get "$PEM_NAME" -p "$DST_PROJECT" -c "$CFG" --plain 2>/dev/null)" || pem=""
  [[ -n "$id" && -n "$pem" ]] || return 1
  probe="$(app_probe "$id" "$pem")"; unset pem
  [[ "$probe" == "200 ${APP_SLUG} ${id}" ]]
}

# copy_equal <name> -> 0 only when the destination holds a readable, non-empty value equal to the source.
copy_equal() {
  local src dst
  src="$(val_hash "$SRC_PROJECT" "$1")"
  dst="$(val_hash "$DST_PROJECT" "$1")"
  [[ -n "$src" && -n "$dst" && "$src" == "$dst" ]]
}

# =============================================================================
# preflight (read)
# =============================================================================
# shellcheck disable=SC2319 # check() takes the condition's own status by design
read_preflight() {
  doppler projects get "$DST_PROJECT" --json >/dev/null 2>&1 \
    || { soleur_op_red "  Doppler project ${DST_PROJECT} is not readable. Either the merged PR's push apply (apply-web-platform-infra.yml) has not run or failed, or this Doppler login cannot see it. Fix that, then run this stage again."; return 1; }
  doppler secrets -p "$DST_PROJECT" -c "$CFG" --only-names >/dev/null 2>&1 \
    || { soleur_op_red "  ${DST_PROJECT}/${CFG} is not readable - the apply creates the prd environment with the project; check the run, then run this stage again."; return 1; }
  check "${SRC_PROJECT}/${CFG} holds a readable ${ID_NAME}" "$([[ -n "$(val_hash "$SRC_PROJECT" "$ID_NAME")" ]]; echo $?)"
  check "${SRC_PROJECT}/${CFG} holds a readable ${PEM_NAME}" "$([[ -n "$(val_hash "$SRC_PROJECT" "$PEM_NAME")" ]]; echo $?)"

  local policy custom names
  policy="$(gh api "repos/${REPO}/environments/${GH_ENVIRONMENT}/deployment-branch-policies" --jq '[.branch_policies[] | select((.type // "branch") == "branch") | .name] | sort | join(",")' 2>/dev/null)" || policy=""
  custom="$(gh api "repos/${REPO}/environments/${GH_ENVIRONMENT}" --jq '.deployment_branch_policy.custom_branch_policies' 2>/dev/null)" || custom=""
  check "environment ${GH_ENVIRONMENT} is restricted to custom branch policies" "$([[ "$custom" == "true" ]]; echo $?)"
  check "environment ${GH_ENVIRONMENT}'s only deployment branch is main (got '${policy:-unreadable}')" "$([[ "$policy" == "main" ]]; echo $?)"

  # A same-named secret at repository or organisation level is reachable from any branch's workflow.
  if names="$(repo_secret_names)"; then
    check "no repository-level secret named ${ENV_SECRET} (it would be branch-reachable)" "$(grep -qxF "$ENV_SECRET" <<<"$names"; echo $((1 - $? )))"
  else
    check "the repository-level secret list is readable (INCONCLUSIVE otherwise)" 1
  fi
  if names="$(org_secret_names)"; then
    check "no organisation-level secret named ${ENV_SECRET}" "$(grep -qxF "$ENV_SECRET" <<<"$names"; echo $((1 - $? )))"
  else
    soleur_op_yellow "  INCONCLUSIVE: the organisation-level secret list is not readable with this gh login (needs org admin). Check Settings -> Secrets on the organisation for ${ENV_SECRET} before relying on the narrowing."
  fi
  stage_verdict
}

# =============================================================================
# copy-app-values (write): copy the two App values into the isolated project
# =============================================================================
# The values that still differ. A source that cannot be read is INCONCLUSIVE, never "nothing to copy".
COPY_TODO=""
compute_copy_todo() {
  local name src dst
  COPY_TODO=""
  for name in "$ID_NAME" "$PEM_NAME"; do
    src="$(val_hash "$SRC_PROJECT" "$name")"
    dst="$(val_hash "$DST_PROJECT" "$name")"
    [[ -n "$src" ]] || return 1
    [[ -n "$dst" && "$src" == "$dst" ]] || COPY_TODO="${COPY_TODO:+${COPY_TODO} }${name}"
  done
}

plan_copy_app_values() {
  local name
  compute_copy_todo || soleur_op_precondition_failed copy-app-values preflight "A source value is not readable from ${SRC_PROJECT}/${CFG}, so there is nothing safe to copy and no plan. Run the preflight stage and fix what it names."
  for name in $COPY_TODO; do
    soleur_op_plan_op copy-secret "${name}:${SRC_PROJECT}->${DST_PROJECT}/${CFG}"
  done
}

copy_one() { # <name>
  doppler secrets get "$1" -p "$SRC_PROJECT" -c "$CFG" --plain \
    | doppler secrets set "$1" -p "$DST_PROJECT" -c "$CFG" --silent >/dev/null
}

# shellcheck disable=SC2319 # check() takes the condition's own status by design
apply_copy_app_values() {
  local name
  compute_copy_todo || { soleur_op_red "  a source value became unreadable; nothing was copied."; return 1; }
  mark_changed "${COPY_TODO} may have been written to ${DST_PROJECT}/${CFG}"
  for name in $COPY_TODO; do copy_one "$name"; done
  for name in "$ID_NAME" "$PEM_NAME"; do
    check "${name}: the copy equals its source (hash compared in-process)" "$(copy_equal "$name"; echo $?)"
  done
  stage_verdict
}

# =============================================================================
# prove-live-app (read): prove the copy is the live App
# =============================================================================
# shellcheck disable=SC2319 # check() takes the condition's own status by design
read_prove_live_app() {
  local id pem probe
  id="$(doppler secrets get "$ID_NAME" -p "$DST_PROJECT" -c "$CFG" --plain 2>/dev/null)" || id=""
  pem="$(doppler secrets get "$PEM_NAME" -p "$DST_PROJECT" -c "$CFG" --plain 2>/dev/null)" || pem=""
  [[ -n "$id" && -n "$pem" ]] || { soleur_op_red "  the copies are not readable from ${DST_PROJECT}/${CFG}; run the copy-app-values stage."; return 1; }
  probe="$(app_probe "$id" "$pem")"; unset pem
  case "$probe" in
    "200 ${APP_SLUG} ${id}") check "a JWT from the copy gets 200 from GET /app with slug=${APP_SLUG} id=${id}" 0 ;;
    401\ *) soleur_op_red "  GitHub answered 401: the copy is a stale or wrong key. Fix the source, then run copy-app-values again (it re-copies on a hash difference)."; check "a JWT from the copy is accepted by GitHub" 1 ;;
    *) check "GET /app with the copy gave a verdict (got '${probe%% *}'; a timeout or another App's answer is INCONCLUSIVE)" 1 ;;
  esac
  stage_verdict
}

# =============================================================================
# mint-and-store-token (write): mint the read token, prove its reach, store it as an ENVIRONMENT secret
# =============================================================================
# tok_verify <token> -> the reach checks; the token travels only in a child's environment.
# shellcheck disable=SC2319 # check() takes the condition's own status by design
tok_verify() {
  local names out rc refused target
  names="$(DOPPLER_TOKEN="$1" doppler secrets download --no-file --no-fallback --format json --project "$DST_PROJECT" --config "$CFG" 2>/dev/null \
    | jq -er --argjson meta "$DOPPLER_META" 'keys - $meta | sort | join(",")' 2>/dev/null)" || names=""
  check "the token lists exactly ${ID_NAME},${PEM_NAME} in ${DST_PROJECT}/${CFG} (got '${names:-unreadable}')" \
    "$([[ "$names" == "${ID_NAME},${PEM_NAME}" ]]; echo $?)"
  # "refused" means a recognised access-denied answer. A transport error or an unknown shape is
  # INCONCLUSIVE, never a pass.
  for target in "${SRC_PROJECT}:${ID_NAME}" "soleur:GITHUB_APP_ID"; do
    refused=1
    rc=0
    out="$(DOPPLER_TOKEN="$1" doppler secrets get "${target#*:}" --plain --project "${target%%:*}" --config "$CFG" 2>&1)" || rc=$?
    if [[ "$rc" -ne 0 ]] && grep -qiE 'access|permission|forbidden|unauthori[sz]ed|not authori[sz]ed' <<<"$out"; then refused=0; fi
    unset out
    check "the token is REFUSED on ${target%%:*}/${CFG} (a recognised access-denied answer)" "$refused"
  done
}

# has_env_secret -> 0 present, 1 absent, 2 UNREADABLE. An unreadable list is INCONCLUSIVE, never "absent".
has_env_secret() {
  local names
  names="$(env_secret_names)" || return 2
  grep -qxF "$ENV_SECRET" <<<"$names" && return 0
  return 1
}

# revoke_confirmed <slug> -> 0 only when the slug is gone afterwards. A failed revoke is never reported as done.
revoke_confirmed() {
  local left
  doppler configs tokens revoke "$1" -p "$DST_PROJECT" -c "$CFG" >/dev/null 2>&1 || true
  left="$(token_slugs)" || { soleur_op_red "  could not re-list the tokens after revoking ${1}; check ${DST_PROJECT}/${CFG} before relying on it."; return 1; }
  if grep -qxF "$1" <<<"$left"; then
    soleur_op_red "  COULD NOT revoke token ${1}. Run: doppler configs tokens revoke ${1} -p ${DST_PROJECT} -c ${CFG}"
    return 1
  fi
}

# The decision, computed from VENDOR state (the token list and the environment-secret list) plus the
# slugs this script recorded. Both the plan and the apply derive it, so they cannot disagree:
#   TP_MODE   satisfied | finish-rotation | mint
#   TP_SLUGS  the live tokens named READ_TOKEN_NAME
#   TP_PREV   the slugs to revoke AFTER the new token is stored (new before old)
TP_MODE=""; TP_SLUGS=""; TP_PREV=""
decide_token_plan() {
  local count recorded stored has_rc=0 s
  TP_SLUGS="$(token_slugs)" || return 1
  count="$(grep -c . <<<"$TP_SLUGS" || true)"
  recorded="$(env_get TOKEN_SLUG)"
  stored="$(env_get TOKEN_STORED)"
  has_env_secret || has_rc=$?
  [[ "$has_rc" -ne 2 ]] || return 2
  TP_PREV=""
  # Exactly one token, it is the one this script recorded AND stored (TOKEN_STORED is written only after the
  # store and the listing check succeed), and the environment secret exists. Environment secrets are
  # write-only, so the name is all GitHub shows; the stored marker is what ties it to this token.
  if [[ "$ROTATE_TOKEN" != "1" && "$count" == "1" && "$has_rc" -eq 0 && -n "$recorded" && "$TP_SLUGS" == "$recorded" && "$stored" == "$recorded" ]]; then
    TP_MODE="satisfied"
    return 0
  fi
  # A rotation that crashed AFTER storing the new token leaves older tokens live: the stored one is proven by the
  # marker, so every other token named READ_TOKEN_NAME is revocable without touching the stored one.
  if [[ "$ROTATE_TOKEN" != "1" && "$count" -gt 1 && "$has_rc" -eq 0 && -n "$recorded" && "$stored" == "$recorded" ]] && grep -qxF "$recorded" <<<"$TP_SLUGS"; then
    TP_MODE="finish-rotation"
    for s in $TP_SLUGS; do [[ "$s" == "$recorded" ]] || TP_PREV="${TP_PREV:+${TP_PREV} }${s}"; done
    return 0
  fi
  # Nothing proves any existing token is the stored one (a lost .env, a crash between steps, or an explicit
  # rotation): mint and store a new token FIRST, then revoke the others.
  TP_MODE="mint"
  for s in $TP_SLUGS; do TP_PREV="${TP_PREV:+${TP_PREV} }${s}"; done
  return 0
}

plan_mint_and_store_token() {
  local rc=0 name s
  decide_token_plan || rc=$?
  case "$rc" in
    1) soleur_op_precondition_failed mint-and-store-token preflight "Cannot list the tokens on ${DST_PROJECT}/${CFG} - an unreadable list is not 'none', so there is no plan." ;;
    2) soleur_op_precondition_failed mint-and-store-token preflight "The ${GH_ENVIRONMENT} environment secret list is not readable with this gh login - INCONCLUSIVE, not 'absent', so there is no plan." ;;
  esac
  [[ "$TP_MODE" != "satisfied" ]] || return 0    # already satisfied: no operation, no approval, no network proof needed
  # The earlier stages' work is re-proved here, in-process, not trusted from a previous run.
  # Finishing a rotation only revokes tokens that are already superseded by the stored one,
  # so it needs neither proof (an unrelated GitHub outage must not keep a stale token live).
  if [[ "$TP_MODE" != "finish-rotation" ]]; then
    for name in "$ID_NAME" "$PEM_NAME"; do
      copy_equal "$name" || soleur_op_precondition_failed mint-and-store-token copy-app-values "${name} in ${DST_PROJECT}/${CFG} is missing or differs from ${SRC_PROJECT}/${CFG}. Run copy-app-values first."
    done
    live_app_ok || soleur_op_precondition_failed mint-and-store-token prove-live-app "A JWT from the copied key was not accepted by GitHub as the ${APP_SLUG} App (or the check could not finish). Run prove-live-app and fix what it names."
  fi
  if [[ -n "$(env_get TOKEN_MINT_ATTEMPTED)" ]]; then
    soleur_op_plan_op recover-interrupted-mint "${DST_PROJECT}/${CFG}"
  fi
  case "$TP_MODE" in
    finish-rotation)
      for s in $TP_PREV; do soleur_op_plan_op revoke-token "$s"; done
      ;;
    mint)
      soleur_op_plan_op mint-read-token "${READ_TOKEN_NAME}@${DST_PROJECT}/${CFG}"
      soleur_op_plan_op store-environment-secret "${ENV_SECRET}@${GH_ENVIRONMENT}"
      for s in $TP_PREV; do soleur_op_plan_op revoke-token "$s"; done
      ;;
  esac
}

# shellcheck disable=SC2319 # check() takes the condition's own status by design
apply_mint_and_store_token() {
  local before old_recorded old_stored new_slug tokval="" s
  decide_token_plan || { soleur_op_red "  the vendor state could not be read; nothing was changed."; return 1; }
  if [[ "$TP_MODE" == "finish-rotation" ]]; then
    mark_changed "superseded token(s) ${TP_PREV} may have been revoked"
    soleur_op_yellow "  finishing an interrupted rotation: revoking the superseded token(s) ${TP_PREV}"
    for s in $TP_PREV; do revoke_confirmed "$s" || return 1; done
    return 0
  fi
  [[ "$TP_MODE" == "mint" ]] || return 0
  mark_changed "a read token may have been minted on ${DST_PROJECT}/${CFG} and stored as ${ENV_SECRET}"
  before="$TP_SLUGS"
  old_recorded="$(env_get TOKEN_SLUG)"
  old_stored="$(env_get TOKEN_STORED)"
  soleur_op_env_upsert "$ENV_FILE" TOKEN_MINT_ATTEMPTED "$(now_iso)"
  tokval="$(doppler configs tokens create "$READ_TOKEN_NAME" -p "$DST_PROJECT" -c "$CFG" --access read --plain 2>/dev/null | tr -d '\n')" || tokval=""
  [[ -n "$tokval" ]] || { soleur_op_red "  minting failed (if the token was created server-side, the next plan finds it by listing)."; soleur_op_env_reset "$ENV_FILE" TOKEN_MINT_ATTEMPTED; return 1; }
  # The slug is recorded BEFORE the store, so a crash between mint and store leaves a revocable
  # record, not an orphan. The new slug is the one that was not there before.
  new_slug="$(comm -13 <(sort <<<"$before") <(token_slugs | sort) | head -1)"
  [[ -n "$new_slug" ]] || { unset tokval; soleur_op_red "  minted, but the new slug could not be identified; revoke tokens named ${READ_TOKEN_NAME} on ${DST_PROJECT}/${CFG} by hand."; return 1; }
  soleur_op_env_upsert "$ENV_FILE" TOKEN_SLUG "$new_slug"
  soleur_op_env_reset "$ENV_FILE" TOKEN_STORED
  soleur_op_env_reset "$ENV_FILE" TOKEN_MINT_ATTEMPTED

  tok_verify "$tokval"
  if ! stage_verdict; then
    unset tokval
    if revoke_confirmed "$new_slug"; then
      soleur_op_red "  the new token did not verify and was revoked (slug ${new_slug})."
      if [[ -n "$old_recorded" ]]; then soleur_op_env_upsert "$ENV_FILE" TOKEN_SLUG "$old_recorded"; else soleur_op_env_reset "$ENV_FILE" TOKEN_SLUG; fi
      # The old token is still live AND still stored: put its stored marker back too, or a
      # healthy system reads as unfinished and the next plan wants to mint again.
      if [[ -n "$old_stored" ]]; then soleur_op_env_upsert "$ENV_FILE" TOKEN_STORED "$old_stored"; fi
    fi
    return 1
  fi
  if ! printf '%s' "$tokval" | gh secret set "$ENV_SECRET" --env "$GH_ENVIRONMENT" -R "$REPO" >/dev/null; then
    unset tokval
    if revoke_confirmed "$new_slug"; then
      soleur_op_red "  storing ${ENV_SECRET} failed; the new token was revoked (slug ${new_slug})."
      if [[ -n "$old_recorded" ]]; then soleur_op_env_upsert "$ENV_FILE" TOKEN_SLUG "$old_recorded"; else soleur_op_env_reset "$ENV_FILE" TOKEN_SLUG; fi
      # The old token is still live AND still stored: put its stored marker back too, or a
      # healthy system reads as unfinished and the next plan wants to mint again.
      if [[ -n "$old_stored" ]]; then soleur_op_env_upsert "$ENV_FILE" TOKEN_STORED "$old_stored"; fi
    fi
    return 1
  fi
  unset tokval
  check "${ENV_SECRET} is listed on the ${GH_ENVIRONMENT} environment" "$(has_env_secret; echo $?)"
  stage_verdict || return 1
  soleur_op_env_upsert "$ENV_FILE" TOKEN_STORED "$new_slug"
  # Rotation: the old tokens are revoked only AFTER the new one is stored (new before old).
  for s in $TP_PREV; do
    revoke_confirmed "$s" || return 1
    soleur_op_yellow "  revoked the superseded token (${s})"
  done
}

# =============================================================================
# verify (read): names only; the READY marker is derived from vendor state
# =============================================================================
# shellcheck disable=SC2319 # check() takes the condition's own status by design
read_verify() {
  local names all name org="clear"
  check "the ${GH_ENVIRONMENT} environment lists ${ENV_SECRET}" "$(has_env_secret; echo $?)"
  if names="$(repo_secret_names)"; then
    check "the repository level does NOT list ${ENV_SECRET}" "$(grep -qxF "$ENV_SECRET" <<<"$names"; echo $((1 - $? )))"
  else
    check "the repository-level secret list is readable (INCONCLUSIVE otherwise)" 1
  fi
  if names="$(org_secret_names)"; then
    [[ "$(grep -cxF "$ENV_SECRET" <<<"$names" || true)" == "0" ]] || { check "the organisation level does NOT list ${ENV_SECRET}" 1; }
  else
    org="INCONCLUSIVE"
  fi
  all="$(token_names_all)" || all=""
  check "${DST_PROJECT}/${CFG} lists exactly one token, ${READ_TOKEN_NAME} (got '${all:-unreadable}')" "$([[ "$all" == "$READ_TOKEN_NAME" ]]; echo $?)"
  check "the recorded slug is the live token and was stored" "$([[ -n "$(env_get TOKEN_SLUG)" && "$(token_slugs)" == "$(env_get TOKEN_SLUG)" && "$(env_get TOKEN_STORED)" == "$(env_get TOKEN_SLUG)" ]]; echo $?)"
  for name in "$ID_NAME" "$PEM_NAME"; do
    check "${name}: the copy equals its source" "$(copy_equal "$name"; echo $?)"
  done
  stage_verdict || return 1
  # "stored and scoped", not "works": the first proof is the first release run after the switch PR.
  printf 'SOLEUR_BOOTSTRAP_READY_FOR_PR2 repo=%s secret=%s environment=%s project=%s org_secret_list=%s\n' \
    "$REPO" "$ENV_SECRET" "$GH_ENVIRONMENT" "$DST_PROJECT" "$org"
  echo "  Stored and scoped - not yet proven by a release run. The switch PR may be merged now; the proof is its first release run (runbook ${RUNBOOK})."
  [[ "$org" != "INCONCLUSIVE" ]] || soleur_op_yellow "  The organisation-level secret list was not readable: check the organisation's Actions secrets for ${ENV_SECRET} before relying on the narrowing."
}

# --- the dispatcher: one stage per invocation --------------------------------
# Not a stage: the one place that applies the staged contract. A stage function
# never gates itself and never prints a stage marker (a marker printed inside a
# `$(...)` capture becomes the captured value).
dispatch_stage() {
  local stage="$1" class fn impact rollback flags="" n
  if ! class="$(soleur_op_stage_field "${BASH_SOURCE[0]}" "$stage" 2)"; then
    printf 'SOLEUR_BOOTSTRAP_UNKNOWN_STAGE stage=%s\n' "$stage"
    printf 'That stage is not declared by this script. The stages are:\n'
    soleur_op_list "${BASH_SOURCE[0]}"
    exit 64
  fi
  fn="${stage//-/_}"
  CURRENT_STAGE_INDEX=1; CURRENT_STAGE_NAME="$stage"; STAGE_CHANGED=""
  soleur_op_stage_begin 1 "$stage"
  case "$class" in
    read)
      "read_${fn}"
      soleur_op_stage_ok "$stage" 0
      ;;
    write)
      impact="$(soleur_op_stage_field "${BASH_SOURCE[0]}" "$stage" 3)"
      rollback="$(soleur_op_stage_field "${BASH_SOURCE[0]}" "$stage" 4)"
      [[ "$ROTATE_TOKEN" == "1" ]] && flags="rotate-token"
      soleur_op_plan_begin
      "plan_${fn}"
      n="$(soleur_op_plan_count)"
      if [[ "$APPLY" -ne 1 ]]; then
        soleur_op_plan_emit "$SCRIPT_REAL" "$stage" "$ROTATE_TOKEN"
        if [[ "$n" -eq 0 ]]; then soleur_op_stage_ok "$stage" 0; fi
      elif [[ "$n" -eq 0 ]]; then
        soleur_op_stage_ok "$stage" 0
      else
        if [[ -z "$PLAN_DIGEST" ]]; then
          printf 'SOLEUR_BOOTSTRAP_PLAN_DIGEST_REQUIRED stage=%s\n' "$stage"
          printf 'Run the stage without --apply first, then run the apply command exactly as the plan printed it.\n'
          SOLEUR_OP_REFUSED=1
          exit 64
        fi
        local computed
        computed="$(soleur_op_plan_digest "$SCRIPT_REAL" "$stage" "$flags" "$impact" "$rollback")"
        soleur_op_stage_gate "$SCRIPT_REAL" "$stage" "$computed" "$PLAN_DIGEST" "$impact" "$rollback" "${ORIG_ARGV[@]}"
        "apply_${fn}"
        soleur_op_stage_ok "$stage" 1 "$SOLEUR_OP_APPROVAL"
      fi
      ;;
    *)
      printf 'SOLEUR_BOOTSTRAP_UNKNOWN_STAGE stage=%s\n' "$stage"
      exit 64
      ;;
  esac
  soleur_op_stage_end 1 "$stage" ok 0
  CURRENT_STAGE_INDEX=0; CURRENT_STAGE_NAME=""; STAGE_CHANGED=""
}

main() {
  soleur_op_require_bins grep mktemp printenv sed date od id stat cut tr awk find doppler gh jq curl openssl sha256sum comm sort head
  soleur_op_ledger_init 1 "bootstrap.sh"
  dispatch_stage "$STAGE"
}

main "$@"
