#!/usr/bin/env bash
# Follow-through verification stub (template).
#
# Mirror of scripts/followthroughs/sentry-checkins-3859.sh.
# Generated by /ship Phase 7 Step 3.5; customize the TODO block below.
#
# Exit semantics (enforced by scripts/sweep-followthroughs.sh):
#   0 = PASS         (close-criteria met; sweeper closes the issue)
#   1 = FAIL         (criteria not met; sweeper comments, leaves open)
#   * = TRANSIENT    (network error, unexpected state; sweeper retries next sweep)
#
# Required secrets: declare via the directive `secrets=` clause AND add to
# .github/workflows/scheduled-followthrough-sweeper.yml env: block.
#
# Convention: knowledge-base/engineering/operations/runbooks/followthrough-convention.md

set -uo pipefail

# REFUSE TO RUN UNDER XTRACE (#7797). A probe receives its secrets from the
# sweeper's env, and tracing echoes commands AFTER expansion -- so a credential
# leaks the moment it is used, and the sweeper posts probe output into a public
# issue comment. Unconditional is the safe default for a scaffold, because the
# template cannot know which credentials this probe will end up reading.
#
# If your probe INHERITS a known, fixed set of credentials, you may narrow this
# to a hatch that keeps the script traceable when they are unset:
#
#   case "$-" in
#     *x*)
#       if [ -n "${YOUR_TOKEN:+x}" ]; then   # `:+x` -- `:-` would PRINT the value
#         printf '[FATAL] refusing to trace with a live credential set (see #7797)\n' >&2
#         exit 78
#       fi
#       ;;
#   esac
#
# Keep it directly below `set ...`: `scripts/lint-shell-trace-credential-refusal.py`
# requires the refusal in the prologue, before any command that could be traced.
case "$-" in
  *x*) printf '[FATAL] refusing to run under xtrace: this probe handles live credentials and -x would print them (see #7797)\n' >&2; exit 78 ;;
esac

# soleur:followthrough-stub v1

# TODO: replace this block with the verification body.
# Examples:
#   - HTTP probe: curl -sS -o /dev/null -w '%{http_code}' "$URL" | grep -q '^200$' && exit 0 || exit 1
#   - SQL probe:  doppler run -- psql "$SUPABASE_URL" -c "SELECT ..." | jq ... && exit 0 || exit 1
#   - GH probe:   gh run list --workflow <wf>.yml --status success --limit 1 --json conclusion | jq -e ... && exit 0 || exit 1
#   - Operator-confirmed: gh issue view <N> --comments --json comments \
#                          | jq -re '.comments[].body' | grep -qE '^RESULT: PASS$' && exit 0 || exit 1

echo "TRANSIENT: stub not customized" >&2
exit 2
