#!/usr/bin/env bash
# kb-index-render.sh — the single implementation of knowledge-base/INDEX.md's layout.
#
# WHY THIS IS ITS OWN FILE. Two programs must produce byte-identical index
# content: `scripts/generate-kb-index.sh` (which derives rows from the tree) and
# `scripts/merge-kb-index.sh` (which derives them from git's three merge inputs).
# A second copy of the layout would drift, and the drift would be invisible —
# both files would still look like an index. Sourcing one renderer makes the
# byte-identity structural, and the driver's round-trip validation re-asserts it
# on EVERY merge rather than only in a parity test.
#
# THE TSV CONTRACT. Rows arrive as `rel<TAB>title`, sorted with `LC_ALL=C sort`
# BY REL — not by rendered line. Sorting rendered lines yields a different order
# because the row renders title-first. Callers own the sort; this file never
# reorders.
#
# TITLES ARRIVE ALREADY ESCAPED. The generator escapes `[` and `]` inside the
# title before the TSV is written, so this renderer emits the title verbatim and
# performs no escaping of its own. That is what lets the driver parse a rendered
# row back to its exact TSV form without an unescape step whose asymmetry with
# the generator's escape step would be a silent corruption channel.
#
# `> Total files:` IS DERIVED FROM THE ROW COUNT, not passed in. The generator's
# own array length and its row count are equal by construction (one row per
# eligible file), so deriving it here loses nothing and makes the header
# incapable of disagreeing with the body it heads. That disagreement is the
# defect the default text merge produces: two branches that each add the same
# NUMBER of files write identical count text, git merges the line cleanly, and
# the result is wrong with no conflict and no marker.

# kb_render_index <tsv_path>
#
# Writes the complete index to stdout. Never reads or writes the tracked
# artifact; the caller decides where the bytes land.
kb_render_index() {
  local tsv="$1"
  local total
  total="$(wc -l < "$tsv")"
  total="${total//[[:space:]]/}"

  printf '# Knowledge Base Index\n'
  printf '\n'
  printf '> Auto-generated by `scripts/generate-kb-index.sh`. Do not edit manually.\n'
  printf '> Total files: %s\n' "$total"

  local current_domain="" rel title domain
  # `printf '%s'` and not `echo`: a title legitimately contains backslashes (the
  # generator escapes `[` to `\[`), and `%s` passes them through untouched while
  # `echo` is permitted to interpret them under xpg_echo.
  while IFS=$'\t' read -r rel title; do
    domain="${rel%%/*}"
    if [[ "$domain" != "$current_domain" ]]; then
      printf '\n## %s\n\n' "$domain"
      current_domain="$domain"
    fi
    printf -- '- [%s](%s)\n' "$title" "$rel"
  done < "$tsv"
}
