#!/usr/bin/env bash
# generate-kb-index.sh — Generate knowledge-base/INDEX.md from file metadata.
#
# Usage: bash scripts/generate-kb-index.sh [--help]
#
# Walks knowledge-base/**/*.md, extracts titles from YAML frontmatter
# (fallback: first # heading, then kebab-to-title-case filename), and
# outputs a flat sorted markdown list grouped by top-level domain.
#
# Excludes archive/ directories and INDEX.md itself.
#
# After merge conflicts on INDEX.md, regenerate:
#   bash scripts/generate-kb-index.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KB_DIR="$REPO_ROOT/knowledge-base"
INDEX_FILE="$KB_DIR/INDEX.md"

if [[ "${1:-}" == "--help" ]]; then
  sed -n '2,/^$/s/^# //p' "$0"
  exit 0
fi

if [[ ! -d "$KB_DIR" ]]; then
  echo "ERROR: knowledge-base/ directory not found at $KB_DIR" >&2
  exit 1
fi

# Collect all eligible .md files (exclude archive/, INDEX.md, non-.md)
mapfile -t all_files < <(
  find "$KB_DIR" -type f -name '*.md' \
    -not -path '*/archive/*' \
    -not -name 'INDEX.md' \
    | LC_ALL=C sort
)

total=${#all_files[@]}

if [[ $total -eq 0 ]]; then
  echo "WARNING: no markdown files found in $KB_DIR" >&2
  exit 0
fi

# Extract titles in parallel batches using xargs -P.
# Each batch processes ~100 files in a single bash process, 4 batches at a time.
# Output: one "rel_path\ttitle" per line, sorted.
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

printf '%s\0' "${all_files[@]}" | xargs -0 -P4 -n100 bash -c '
  KB_DIR="$1"; shift
  for f in "$@"; do
    rel="${f#"$KB_DIR/"}"
    title="" heading="" fm=0 nr=0
    while IFS= read -r line || [[ -n "$line" ]]; do
      ((nr++)); ((nr > 30)) && break
      if [[ "$line" == "---" ]]; then ((fm++)); ((fm >= 2)) && break; continue; fi
      if ((fm == 1)) && [[ "$line" == title:* ]]; then
        title="${line#title:}"; title="${title# }"
        title="${title#\"}"; title="${title%\"}"
        title="${title#\x27}"; title="${title%\x27}"
        break
      fi
      [[ -z "$heading" && "$line" == "# "* ]] && heading="${line#\# }"
    done < "$f"
    [[ -n "$title" ]] || title="$heading"
    if [[ -z "$title" ]]; then
      n=$(basename "$f" .md)
      n="${n#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-}"
      title=$(printf "%s" "$n" | tr "-" " " | sed "s/\b./\U&/g")
    fi
    printf "%s\t%s\n" "$rel" "$title"
  done
' _ "$KB_DIR" | LC_ALL=C sort > "$tmpfile"

# Build the index from the sorted entries
{
  echo "# Knowledge Base Index"
  echo ""
  echo "> Auto-generated by \`scripts/generate-kb-index.sh\`. Do not edit manually."
  echo "> Total files: $total"

  current_domain=""
  while IFS=$'\t' read -r rel title; do
    domain="${rel%%/*}"
    if [[ "$domain" != "$current_domain" ]]; then
      echo ""
      echo "## $domain"
      echo ""
      current_domain="$domain"
    fi
    echo "- [$title]($rel)"
  done < "$tmpfile"
} > "$INDEX_FILE"

echo "Generated $INDEX_FILE ($total files indexed)"
