#!/usr/bin/env bash
# SOLEUR-GENERATED-OPERATOR-SCRIPT v1
#
# Generated by `soleur:operator-bootstrap` from
# plugins/soleur/skills/operator-bootstrap/template.sh.
#
# This header marker identifies the file as a generated operator script. It does
# NOT pin a byte-identical library region: there is one distribution mode and the
# script SOURCES the library, so there is no copy to drift from.
#
# <!-- Inspired by mattpocock/skills/skills/engineering/wizard/ (MIT, Copyright (c) 2026 Matt Pocock). -->
#
# WHAT TO EDIT: only `main()` and the `stage_*` functions below it. Everything
# above `main()` is the contract the library expects. NEVER hand-edit
# plugins/soleur/scripts/lib/operator-script.sh — the library is one file and
# every generated script shares it.
#
# Exit codes: 0 ok · 1 usage/refused · 3 DPA-gate rejection · 64 missing input
# (including a prompt with no TTY) · 78 refusing to run under xtrace.
# Note: apps/cla-evidence/scripts/sentinel-pr.sh returns 3 for "missing tool on
# PATH"; this repo has both meanings of 3 live. Do not re-derive it.
set -euo pipefail

# --- PROLOGUE (must stay ABOVE the `source` line) ----------------------------
# DUPLICATED here on purpose, never moved into the library. PROLOGUE_MAX_CMDS = 0
# in scripts/lint-shell-trace-credential-refusal.py makes the `source` line
# itself a counted command, and the linter's find_preamble scans only this file's
# own lines — a caller sourcing a fully compliant library still fails Rule A.
#
# Stdout, not stderr: agent runtimes surface stdout and swallow stderr.
case "$-" in
  *x*)
    printf '[FATAL] refusing to run under xtrace: this script handles a live credential and -x would print it (see #7797)\n'
    exit 78
    ;;
esac

# `--disable` closes ~/.curlrc and `--noproxy '*'` closes the proxy vars, but
# neither touches the env that subverts TLS itself: SSLKEYLOGFILE writes the
# session keys and the CA vars substitute the trust store.
unset SSLKEYLOGFILE CURL_CA_BUNDLE SSL_CERT_FILE SSL_CERT_DIR CURL_HOME \
      HOSTALIASES LOCALDOMAIN RES_OPTIONS

# --- library resolution ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Resolution order, most explicit first. `CLAUDE_PLUGIN_ROOT` is the supported
# path for a marketplace install; the relative arm is the in-repo one. Neither
# precedent in this repo handles a non-default install root or a `sh`-invoked
# shell where BASH_SOURCE is unavailable — stated, not silently inherited.
SOLEUR_OP_LIB="${SOLEUR_OP_LIB:-}"
if [[ -z "$SOLEUR_OP_LIB" ]]; then
  for candidate in \
    "${CLAUDE_PLUGIN_ROOT:-/nonexistent}/scripts/lib/operator-script.sh" \
    "${SCRIPT_DIR}/../../scripts/lib/operator-script.sh" \
    "${SCRIPT_DIR}/.soleur/lib/operator-script.sh"
  do
    [[ -r "$candidate" ]] && { SOLEUR_OP_LIB="$candidate"; break; }
  done
fi

# HARD EXIT, never a stub. ADR-178 Context §1 records what fail-closed stubs did
# to `cleanup-merged`: it refused to reap forever while reporting success.
if [[ -z "$SOLEUR_OP_LIB" || ! -r "$SOLEUR_OP_LIB" ]]; then
  printf 'SOLEUR_BOOTSTRAP_LIB_MISSING path=%s\n' "${SOLEUR_OP_LIB:-<unresolved>}"
  printf 'Install or update the Soleur plugin, or set SOLEUR_OP_LIB to the library path.\n'
  exit 64
fi

# shellcheck source=../../scripts/lib/operator-script.sh disable=SC1091
source "$SOLEUR_OP_LIB"

# --- configuration -----------------------------------------------------------
SLUG="${SLUG:-example}"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
: "${SOLEUR_BOOTSTRAP_LEDGER:=${SCRIPT_DIR}/bootstrap-runs.jsonl}"
export SOLEUR_BOOTSTRAP_LEDGER
TOTAL_STAGES=2

usage() {
  cat <<USAGE
Usage: bootstrap.sh [--reset <KEY>] [--help]

  --reset <KEY>   Forget a persisted .env value so the next run re-asks for it.
                  A wrong credential is otherwise permanent: the value is stored
                  before it can be validated, and the environment-first ladder
                  means a re-run never re-prompts.
  --help          This text.

Environment:
  SOLEUR_BOOTSTRAP_START_STAGE=<n>   Resume: skip every stage below n.
                                     \`verify-bootstrap-run.sh --last\` prints n.
  SOLEUR_BOOTSTRAP_LEDGER=<path>     Run ledger (default: beside this script).
  <SKIP VARIABLES>                   One per class-1/class-3 prompt; see below.
                                     The destructive-write ack has NONE, by rule.
USAGE
}

# --- argument validation -----------------------------------------------------
# Deliberately ABOVE the trap: a usage error must print no teardown banner.
RESET_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset) RESET_KEY="${2:-}"; [[ -n "$RESET_KEY" ]] || { echo "Error: --reset needs a KEY" >&2; usage >&2; exit 1; }; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ -n "$RESET_KEY" ]]; then
  soleur_op_env_reset "$ENV_FILE" "$RESET_KEY"
  soleur_op_green "Forgot ${RESET_KEY}. Re-run to be asked for it again."
  exit 0
fi

# =============================================================================
# STAGES — everything below this line is yours. Replace the examples.
# =============================================================================
#
# Each stage: precondition first ("already satisfied?"), then the action, then an
# independent verification. Re-run is not idempotent over a non-idempotent create
# unless the precondition makes it so, and a founder who is interrupted has no
# safe action without it.

# EXAMPLE class-3 barrier: the founder does something outside the script, and the
# script VERIFIES it rather than believing the answer.
stage_1_account() {
  # Precondition — already satisfied?
  if [[ -f "$ENV_FILE" ]] && grep -q '^EXAMPLE_ACCOUNT_ID=' "$ENV_FILE"; then
    soleur_op_yellow "  already satisfied: EXAMPLE_ACCOUNT_ID is recorded"
    return 0
  fi

  echo "  1. Open the vendor console and create the account for '${SLUG}'."
  soleur_op_open_url "https://example.invalid/console/new?name=${SLUG}"

  # Class 3 — skippable, AND verified immediately afterwards.
  soleur_op_barrier SOLEUR_BOOTSTRAP_SKIP_ACCOUNT_BARRIER "  Account created? Type 'yes' to continue: "

  local account_id=""
  soleur_op_value SOLEUR_BOOTSTRAP_ACCOUNT_ID "  Account id: " account_id

  # Independent verification of the thing attested. Without this the barrier
  # attests nothing and skipping it is a no-op wearing a prompt.
  [[ -n "$account_id" ]] || { soleur_op_red "no account id; the barrier attested nothing"; return 1; }

  soleur_op_env_upsert "$ENV_FILE" EXAMPLE_ACCOUNT_ID "$account_id"
}

# EXAMPLE class-2 gate: a per-command acknowledgement for a destructive or
# billable write. NO SKIP VARIABLE — automation must not be able to supply it.
stage_2_provision() {
  if [[ -f "$ENV_FILE" ]] && grep -q '^EXAMPLE_PROVISIONED=' "$ENV_FILE"; then
    soleur_op_yellow "  already satisfied: resource is provisioned"
    return 0
  fi

  echo "  This creates a billable resource in the vendor account."
  soleur_op_ack_or_die "  Create it now? Type 'yes': "

  # ... the destructive write goes here ...

  soleur_op_env_upsert "$ENV_FILE" EXAMPLE_PROVISIONED "yes"
}

main() {
  soleur_op_require_bins grep mktemp awk printenv stat
  soleur_op_ledger_init "$TOTAL_STAGES" "bootstrap.sh"

  if soleur_op_stage_should_run 1; then
    soleur_op_stage_begin 1 "vendor account"
    stage_1_account
    soleur_op_stage_end 1 "vendor account" ok 0
  fi

  if soleur_op_stage_should_run 2; then
    soleur_op_stage_begin 2 "provision the resource"
    stage_2_provision
    soleur_op_stage_end 2 "provision the resource" ok 0
  fi

  soleur_op_summary_begin "BOOTSTRAP COMPLETE."
  soleur_op_summary_line "Values were written to ${ENV_FILE} (mode 600)."
  soleur_op_summary_line "Run ledger: ${SOLEUR_BOOTSTRAP_LEDGER}"
}

main "$@"
