#!/usr/bin/env bash
# SOLEUR-GENERATED-OPERATOR-SCRIPT v1
#
# Generated by `soleur:operator-bootstrap` from
# plugins/soleur/skills/operator-bootstrap/template.sh.
#
# This header marker identifies the file as a generated operator script. It does
# NOT pin a byte-identical library region: there is one distribution mode and the
# script SOURCES the library, so there is no copy to drift from.
#
# <!-- Inspired by mattpocock/skills/skills/engineering/wizard/ (MIT, Copyright (c) 2026 Matt Pocock). -->
#
# WHAT TO EDIT: only `main()` and the `stage_*` functions below it, plus the
# ONE generation-time substitution of SOLEUR_OP_LIB_BAKED. Everything else above
# `main()` is the contract the library expects. NEVER hand-edit
# plugins/soleur/scripts/lib/operator-script.sh — the library is one file and
# every generated script shares it.
#
# Exit codes and stdout markers: the library header ("EXIT CODES" and "STDOUT
# MARKERS" in plugins/soleur/scripts/lib/operator-script.sh) is the single
# source. Do not restate the table here.
set -euo pipefail

# --- PROLOGUE (must stay ABOVE the `source` line) ----------------------------
# Duplicated here, never moved into the library — see "SOURCING PRECONDITIONS"
# §2 in the library header for why. Stdout, not stderr: agent runtimes surface
# stdout and swallow stderr.
case "$-" in
  *x*)
    printf '[FATAL] refusing to run under xtrace: this script handles a live credential and -x would print it (see #7797)\n'
    exit 78
    ;;
esac

# SSLKEYLOGFILE writes TLS session keys to disk; nothing a stage runs should
# inherit it. The CA-pool variables (SSL_CERT_FILE, SSL_CERT_DIR,
# CURL_CA_BUNDLE) are deliberately NOT stripped: `gh` and `hcloud` are Go
# clients that read them for their root pool, and a founder behind a
# TLS-inspecting proxy needs them (the credential linter requires only the
# xtrace refusal above — measured).
unset SSLKEYLOGFILE

# --- library resolution ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GENERATION-TIME SUBSTITUTION. The generator (operator-bootstrap/SKILL.md §3)
# replaces the placeholder below with the ABSOLUTE path of the library resolved
# at generation time — `realpath "${CLAUDE_PLUGIN_ROOT}/scripts/lib/operator-
# script.sh"`. A generated script lives at
# knowledge-base/project/specs/feat-<name>/bootstrap.sh in the FOUNDER's repo,
# where no relative path to the plugin exists and CLAUDE_PLUGIN_ROOT is unset in
# a founder's terminal; without the bake the only reachable outcome from that
# location was LIB_MISSING (measured, review F1). An unsubstituted placeholder
# is not an absolute path, so the loop below treats it as "not baked", never as
# a path — and the loop deliberately does not spell the placeholder, so a global
# substitution cannot rewrite the guard along with the value.
SOLEUR_OP_LIB_BAKED="__SOLEUR_OP_LIB_BAKED__"

# Resolution order, most explicit first:
#   1. SOLEUR_OP_LIB      — explicit env override (a moved plugin, a test). Must
#                           be ABSOLUTE: `-r` tests a relative name against cwd
#                           while `source` searches PATH for it, two different
#                           files.
#   2. CLAUDE_PLUGIN_ROOT — a script run from inside a Claude Code session: the
#                           LIVE plugin, which beats a bake that may point at a
#                           stale marketplace cache hash.
#   3. the baked path     — what a generated script runs on in a founder's
#                           terminal, where 2 is unset.
#   4. hard exit 64, naming the LAST candidate that was rejected.
SOLEUR_OP_LIB="${SOLEUR_OP_LIB:-}"
last_rejected="<no candidate was absolute>"
if [[ -n "$SOLEUR_OP_LIB" && "$SOLEUR_OP_LIB" != /* ]]; then
  last_rejected="$SOLEUR_OP_LIB (SOLEUR_OP_LIB must be an absolute path)"
  SOLEUR_OP_LIB=""
fi
if [[ -z "$SOLEUR_OP_LIB" ]]; then
  for candidate in \
    "${CLAUDE_PLUGIN_ROOT:-/nonexistent}/scripts/lib/operator-script.sh" \
    "$SOLEUR_OP_LIB_BAKED"
  do
    [[ "$candidate" == /* ]] || continue
    if [[ -r "$candidate" ]]; then SOLEUR_OP_LIB="$candidate"; break; fi
    last_rejected="$candidate"
  done
fi

# HARD EXIT, never a stub. ADR-178 Context §1 records what fail-closed stubs did
# to `cleanup-merged`: it refused to reap forever while reporting success.
if [[ -z "$SOLEUR_OP_LIB" || ! -r "$SOLEUR_OP_LIB" ]]; then
  printf 'SOLEUR_BOOTSTRAP_LIB_MISSING path=%s\n' "${SOLEUR_OP_LIB:-$last_rejected}"
  printf 'Install or update the Soleur plugin, or set SOLEUR_OP_LIB to the absolute path of the library.\n'
  exit 64
fi
unset last_rejected

# shellcheck source=../../scripts/lib/operator-script.sh disable=SC1091
source "$SOLEUR_OP_LIB"

# API contract (library header §API). EQUALITY: the library auto-updates with
# the plugin while this script is frozen in the founder's repository, so
# "library newer than script" is the only incompatibility that can occur, and
# `-ge` admitted exactly that (measured: a v2 library that had renamed a helper
# passed the gate, wrote run_begin and stage 1, then died at the call — the
# mid-stage death this check exists to prevent). Refused BEFORE any ledger
# write.
[[ ${SOLEUR_OP_LIB_API:-0} -eq 1 ]] || {
  printf 'SOLEUR_BOOTSTRAP_LIB_INCOMPATIBLE need=1 got=%s\n' "${SOLEUR_OP_LIB_API:-0}"
  exit 64
}

# --- configuration -----------------------------------------------------------
SLUG="${SLUG:-example}"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
: "${SOLEUR_BOOTSTRAP_LEDGER:=${SCRIPT_DIR}/bootstrap-runs.jsonl}"
export SOLEUR_BOOTSTRAP_LEDGER
TOTAL_STAGES=2

usage() {
  cat <<USAGE
Usage: bootstrap.sh [--reset <KEY>] [--help]

  --reset <KEY>   Forget a persisted .env value so the next run re-asks for it.
                  A wrong credential is otherwise permanent: the value is stored
                  before it can be validated, and the environment-first ladder
                  means a re-run never re-prompts.
  --help          This text.

Environment:
  SOLEUR_BOOTSTRAP_LEDGER=<path>     Run ledger (default: beside this script).
  SOLEUR_OP_LIB=<abs-path>           Override the library path baked at generation.

Skip variables — one per class-1/class-3 prompt in THIS script, derived from
its source so the list cannot drift (naming convention: SOLEUR_BOOTSTRAP_<WHAT>
for a value, SOLEUR_BOOTSTRAP_SKIP_<WHAT>_BARRIER for a barrier). The
destructive-write acknowledgement has NONE, by rule:
$(grep -oE '^[[:space:]]*soleur_op_(barrier|value) SOLEUR_BOOTSTRAP_[A-Z0-9_]+' "${BASH_SOURCE[0]}" | awk '{print "  " $2}' | sort -u)
USAGE
}

# --- argument validation -----------------------------------------------------
# Deliberately ABOVE the EXIT trap installed below: a usage error must print no
# "Stopped during stage" banner, and `--reset` is not a stage.
RESET_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset) RESET_KEY="${2:-}"; [[ -n "$RESET_KEY" ]] || { echo "Error: --reset needs a KEY" >&2; usage >&2; exit 1; }; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

# --- the credentials file must be ignored by git ------------------------------
# This script lives in a TRACKED directory (SKILL.md §Where), and its .env holds
# live credentials. A .gitignore that does not cover it turns the founder's next
# `git add .` into a pushed token (review P1-1). Checked BEFORE the first write —
# `--reset` writes too — on the .env AND on the `.tmp.XXXXXX` sibling the upsert
# creates beside it, which a bare `.env` pattern does not cover. Outside a git
# work tree (or without git) there is nothing to commit, so the check passes.
env_not_ignored() {
  local dir; dir="$(dirname "$1")"
  git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 1
  ! git -C "$dir" check-ignore -q "$1"
}
for probe in "$ENV_FILE" "${ENV_FILE}.tmp.XXXXXX"; do
  if env_not_ignored "$probe"; then
    printf 'SOLEUR_BOOTSTRAP_ENV_NOT_IGNORED path=%s\n' "$probe"
    printf 'The credentials file would be committed. Add it to .gitignore first (a pattern such as .env* covers both the file and its temp sibling).\n'
    exit 64
  fi
done
unset probe

if [[ -n "$RESET_KEY" ]]; then
  soleur_op_env_reset "$ENV_FILE" "$RESET_KEY"
  soleur_op_green "Forgot ${RESET_KEY}. Re-run to be asked for it again."
  exit 0
fi

# --- terminal outcome --------------------------------------------------------
# ONE trap. On a non-zero exit inside a stage it tells the founder which stage
# stopped, that nothing else was changed, and the one command that resumes —
# and it settles the stage in the ledger as `failed` with the exit code, so the
# ledger can say something other than "ok" (review P2-12). A library refusal
# (INPUT_REQUIRED, ABORTED) has already printed its own marker and sentence and
# written its `run_halt` line before this fires; the trap adds the stage context.
SCRIPT_PATH="${SCRIPT_DIR}/$(basename "${BASH_SOURCE[0]}")"
CURRENT_STAGE_INDEX=0
CURRENT_STAGE_NAME=""
on_exit() {
  local rc=$?
  [[ "$rc" -ne 0 && "$CURRENT_STAGE_INDEX" -gt 0 ]] || return 0
  printf 'Stopped during stage %s (%s). Nothing else was changed. Run: bash %s — already-done steps are skipped.\n' \
    "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" "$SCRIPT_PATH"
  soleur_op_stage_end "$CURRENT_STAGE_INDEX" "$CURRENT_STAGE_NAME" failed "$rc"
}
trap on_exit EXIT

# run_stage <index> <name> <function>
#   Begin/settle around every stage, and the context the EXIT trap reports.
run_stage() {
  CURRENT_STAGE_INDEX="$1"; CURRENT_STAGE_NAME="$2"
  soleur_op_stage_begin "$1" "$2"
  "$3"
  soleur_op_stage_end "$1" "$2" ok 0
  CURRENT_STAGE_INDEX=0; CURRENT_STAGE_NAME=""
}

# =============================================================================
# STAGES — everything below this line is yours. Replace the examples.
# =============================================================================
#
# Each stage: precondition first ("already satisfied?"), then the action, then an
# independent verification. Re-run is not idempotent over a non-idempotent create
# unless the precondition makes it so, and a founder who is interrupted has no
# safe action without it.
#
# The library sets `umask 077`, and every child a stage starts INHERITS it: a
# file a stage writes for someone else (a public key, a config the vendor CLI
# reads) lands 0600. Escape per command, never globally:
#   (umask 022; printf '%s\n' "$pubkey" > "$HOME/.ssh/id.pub")

# EXAMPLE class-3 barrier: the founder does something outside the script, and the
# script VERIFIES it rather than believing the answer.
stage_1_account() {
  # Precondition — already satisfied?
  if [[ -f "$ENV_FILE" ]] && grep -aq '^EXAMPLE_ACCOUNT_ID=' "$ENV_FILE"; then
    soleur_op_yellow "  already satisfied: EXAMPLE_ACCOUNT_ID is recorded"
    return 0
  fi

  echo "  1. Open the vendor console and create the account for '${SLUG}'."
  soleur_op_open_url "https://example.invalid/console/new?name=${SLUG}"

  # Class 3 — skippable, AND verified immediately afterwards.
  soleur_op_barrier SOLEUR_BOOTSTRAP_SKIP_ACCOUNT_BARRIER "  Account created? Type 'yes' to continue: "

  local account_id=""
  soleur_op_value SOLEUR_BOOTSTRAP_ACCOUNT_ID "  Account id: " account_id

  # Independent verification of the thing attested. Without this the barrier
  # attests nothing and skipping it is a no-op wearing a prompt.
  [[ -n "$account_id" ]] || { soleur_op_red "no account id; the barrier attested nothing"; return 1; }

  soleur_op_env_upsert "$ENV_FILE" EXAMPLE_ACCOUNT_ID "$account_id"
}

# EXAMPLE class-2 gate: a per-command acknowledgement for a destructive or
# billable write. NO SKIP VARIABLE — automation must not be able to supply it.
#
# The precondition asks the VENDOR, never only a local marker written after the
# create: between "create succeeded" and "marker written" a Ctrl-C leaves a
# resource the next run cannot see, and it creates a second one (review P1-2).
# Two controls close that window here — REPLACE the vendor read, KEEP the shape:
#   1. `example_resource_exists` is the vendor-side read (hcloud server list,
#      gh api, doppler projects get). It is what makes re-run safe.
#   2. an ATTEMPTED marker is written BEFORE the create. A re-run that finds it
#      without the PROVISIONED marker stops and sends the founder to the console
#      instead of creating again; `--reset EXAMPLE_PROVISION_ATTEMPTED` clears it
#      once they have looked.
example_resource_exists() {
  # REPLACE with the vendor read. The stand-in consults the local record only
  # because this template has no vendor to ask.
  [[ -f "$ENV_FILE" ]] && grep -aq '^EXAMPLE_PROVISIONED=' "$ENV_FILE"
}

stage_2_provision() {
  if example_resource_exists "$SLUG"; then
    soleur_op_yellow "  already satisfied: the resource exists at the vendor"
    return 0
  fi
  if [[ -f "$ENV_FILE" ]] && grep -aq '^EXAMPLE_PROVISION_ATTEMPTED=' "$ENV_FILE"; then
    soleur_op_red "  A previous run started this create and was interrupted before it could record the result."
    soleur_op_red "  Check the vendor console for '${SLUG}'. If nothing exists there, run:"
    soleur_op_red "    bash ${SCRIPT_PATH} --reset EXAMPLE_PROVISION_ATTEMPTED"
    return 1
  fi

  echo "  This creates a billable resource in the vendor account."
  soleur_op_ack_or_die "  Create it now? Type 'yes': "

  soleur_op_env_upsert "$ENV_FILE" EXAMPLE_PROVISION_ATTEMPTED "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  # ... the destructive write goes here ...
  soleur_op_env_upsert "$ENV_FILE" EXAMPLE_PROVISIONED "yes"
  soleur_op_env_reset "$ENV_FILE" EXAMPLE_PROVISION_ATTEMPTED
}

main() {
  soleur_op_require_bins grep mktemp printenv sed date
  soleur_op_ledger_init "$TOTAL_STAGES" "bootstrap.sh"

  # No resume index: every stage's precondition makes a re-run from stage 1
  # skip what is already done, so re-run IS resume.
  run_stage 1 "vendor account" stage_1_account
  run_stage 2 "provision the resource" stage_2_provision

  soleur_op_summary_begin "BOOTSTRAP COMPLETE."
  soleur_op_summary_line "Values were written to ${ENV_FILE} (mode 600)."
  soleur_op_summary_line "Run ledger: ${SOLEUR_BOOTSTRAP_LEDGER}"
}

main "$@"
