name: Dependency Review

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Dependency Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          retry-on-snapshot-warnings: true
          fail-on-severity: high
          fail-on-scopes: runtime
          license-check: true
          vulnerability-check: true
          comment-summary-in-pr: on-failure
          deny-packages: |
            pkg:pypi/litellm
            pkg:npm/event-stream
